import Ledger.Feature

/-!
Ledger rows for APPNOTE. One row per clause the scope requires, plus any deeper row a note needs.
-/

namespace Ledger.Catalogue.Appnote

open Ledger

def rows0 : List Feature := [
  { standard := .appnote, ref := .clause [4, 1], title := "What is a ZIP file", status := .incomplete,
    note := "Stored and deflated entries are read and written with CRC-32 checks; encryption, other compression methods, split archives and manifest files are not supported." },
  { standard := .appnote, ref := .clause [4, 1, 1], title := "ZIP files MAY be identified by the standard .ZIP file extension", status := .outOfScope,
    note := "Introductory statement; the requirements it summarizes have their own rows under 4.3 to 4.5." },
  { standard := .appnote, ref := .clause [4, 1, 2], title := "ZIP files SHOULD contain at least one file and MAY contain", status := .outOfScope,
    note := "Introductory statement; the requirements it summarizes have their own rows under 4.3 to 4.5." },
  { standard := .appnote, ref := .clause [4, 1, 3], title := "Data compression MAY be used to reduce the size of files", status := .outOfScope,
    note := "Introductory statement; the requirements it summarizes have their own rows under 4.3 to 4.5." },
  { standard := .appnote, ref := .clause [4, 1, 4], title := "Data encryption MAY be used to protect files within a ZIP file", status := .notImplemented,
    note := "Encrypted entries are refused with Error::Encrypted (crates/docboss-zip/src/lib.rs); nothing is decrypted." },
  { standard := .appnote, ref := .clause [4, 1, 5], title := "Data integrity MUST be provided for each file using CRC32", status := .implemented,
    note := "Every entry read is checked against its CRC-32; a mismatch is an error from Archive::entry and a flag from Archive::read (test archive.rs corrupted_bytes_fail_the_crc_check)." },
  { standard := .appnote, ref := .clause [4, 1, 6], title := "Additional data integrity MAY be included through the use of", status := .outOfScope,
    note := "Introductory statement; the requirements it summarizes have their own rows under 4.3 to 4.5." },
  { standard := .appnote, ref := .clause [4, 1, 7], title := "Files MAY be placed within a ZIP file uncompressed or stored", status := .outOfScope,
    note := "Introductory statement; the requirements it summarizes have their own rows under 4.3 to 4.5." },
  { standard := .appnote, ref := .clause [4, 1, 8], title := "Each data file placed into a ZIP file MAY be compressed, stored,", status := .outOfScope,
    note := "Introductory statement; the requirements it summarizes have their own rows under 4.3 to 4.5." },
  { standard := .appnote, ref := .clause [4, 1, 9], title := "ZIP files MAY be streamed, split into segments (on fixed or on", status := .notImplemented,
    note := "Split and spanned archives are not read; only the last segment's central directory would be found." },
  { standard := .appnote, ref := .clause [4, 1, 10], title := "Extensibility is provided for platform or application specific", status := .outOfScope,
    note := "Introductory statement; the requirements it summarizes have their own rows under 4.3 to 4.5." },
  { standard := .appnote, ref := .clause [4, 1, 11], title := "Common uses for ZIP MAY also include the use of manifest files", status := .outOfScope,
    note := "Introductory statement; the requirements it summarizes have their own rows under 4.3 to 4.5." },
  { standard := .appnote, ref := .clause [4, 1, 12], title := "ZIP files MAY be placed within other ZIP files", status := .outOfScope,
    note := "Introductory statement; the requirements it summarizes have their own rows under 4.3 to 4.5." },
  { standard := .appnote, ref := .clause [4, 2], title := "ZIP Metadata", status := .outOfScope,
    note := "Introductory statement; the record types have their own rows under 4.3." },
  { standard := .appnote, ref := .clause [4, 2, 1], title := "ZIP files are identified by metadata consisting of defined record types", status := .outOfScope,
    note := "Introductory statement; the record types have their own rows under 4.3." },
  { standard := .appnote, ref := .clause [4, 3], title := "General Format of a .ZIP file", status := .incomplete,
    note := "Local headers, file data, data descriptors, the central directory, the ZIP64 records and the end record are read and written; the archive decryption header, archive extra data record and digital signature are not." },
  { standard := .appnote, ref := .clause [4, 3, 1], title := "A ZIP file MUST contain an \"end of central directory record\"", status := .outOfScope,
    note := "Normative summary of the layout that 4.3.6 to 4.3.16 specify record by record; see those rows." },
  { standard := .appnote, ref := .clause [4, 3, 2], title := "Each file placed into a ZIP file MUST be preceded by a \"local", status := .outOfScope,
    note := "Normative summary of the layout that 4.3.6 to 4.3.16 specify record by record; see those rows." },
  { standard := .appnote, ref := .clause [4, 3, 3], title := "Files MAY be stored in arbitrary order within a ZIP file", status := .outOfScope,
    note := "Normative summary of the layout that 4.3.6 to 4.3.16 specify record by record; see those rows." },
  { standard := .appnote, ref := .clause [4, 3, 4], title := "Compression MUST NOT be applied to a \"local file header\", an \"encryption", status := .outOfScope,
    note := "Normative summary of the layout that 4.3.6 to 4.3.16 specify record by record; see those rows." },
  { standard := .appnote, ref := .clause [4, 3, 5], title := "File data MAY be followed by a \"data descriptor\" for the file", status := .outOfScope,
    note := "Normative summary of the layout that 4.3.6 to 4.3.16 specify record by record; see those rows." },
  { standard := .appnote, ref := .clause [4, 3, 6], title := "Overall .ZIP file format", status := .implemented,
    note := "Entries are located through the central directory and read at their local header offsets (crates/docboss-zip/src/lib.rs central_directory, test archive.rs reads_stored_and_deflated_entries)." },
  { standard := .appnote, ref := .clause [4, 3, 7], title := "Local file header", status := .implemented,
    note := "Local headers give each entry's data offset and, when the central directory cannot be read, are scanned to recover the entries, which is reported as a diagnostic (test archive.rs recovers_from_a_missing_central_directory); the writer emits one per entry." },
  { standard := .appnote, ref := .clause [4, 3, 8], title := "File data", status := .implemented,
    note := "Stored data is borrowed from the input and deflated data inflated under the size and ratio limits of Limits (test archive.rs reads_stored_and_deflated_entries)." },
  { standard := .appnote, ref := .clause [4, 3, 9], title := "Data descriptor", status := .implemented,
    note := "General purpose bit 3 defers the CRC and sizes to a data descriptor, which recovery finds after the data (test archive.rs reads_entries_with_data_descriptors); the writer can emit descriptors (write.rs every_layout_reads_back)." },
  { standard := .appnote, ref := .clause [4, 3, 10], title := "Archive decryption header", status := .notImplemented,
    note := "The archive decryption header of central directory encryption is not read; such archives do not open." },
  { standard := .appnote, ref := .clause [4, 3, 11], title := "Archive extra data record", status := .notImplemented,
    note := "The archive extra data record is not read." },
  { standard := .appnote, ref := .clause [4, 3, 12], title := "Central directory structure", status := .implemented,
    note := "Central directory headers give each entry's name, method, flags, CRC, sizes and local header offset (test archive.rs reads_stored_and_deflated_entries); the writer emits them." },
  { standard := .appnote, ref := .clause [4, 3, 13], title := "Digital signature", status := .notImplemented,
    note := "The central directory digital signature is not read or verified." },
  { standard := .appnote, ref := .clause [4, 3, 14], title := "Zip64 end of central directory record", status := .implemented,
    note := "The ZIP64 end of central directory record gives 64-bit entry counts, directory size and offset (test archive.rs reads_zip64_archives); the writer emits it with WriteOptions::zip64." },
  { standard := .appnote, ref := .clause [4, 3, 15], title := "Zip64 end of central directory locator", status := .implemented,
    note := "The ZIP64 locator is followed to the ZIP64 end record (test archive.rs reads_zip64_archives); the writer emits it with WriteOptions::zip64." },
  { standard := .appnote, ref := .clause [4, 3, 16], title := "End of central directory record", status := .implemented,
    note := "The end of central directory record is located from the end of the file and gives the directory's offset and entry count; the writer ends every archive with one (test write.rs archive_ends_with_directory_record)." },
  { standard := .appnote, ref := .clause [4, 4], title := "Explanation of fields", status := .incomplete,
    note := "The fields needed to locate, decode and check entries are read; version, attribute, disk, date and comment fields are ignored." },
  { standard := .appnote, ref := .clause [4, 4, 1], title := "General notes on fields", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 2], title := "version made by (2 bytes)", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 3], title := "version needed to extract (2 bytes)", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 4], title := "general purpose bit flag", status := .incomplete,
    note := "Bit 0 refuses an encrypted entry, bit 3 defers sizes to a data descriptor and bit 11 selects UTF-8 names (tests archive.rs reads_entries_with_data_descriptors and decodes_name_encodings); the other bits are ignored." },
  { standard := .appnote, ref := .clause [4, 4, 5], title := "compression method", status := .incomplete,
    note := "Methods 0 (stored) and 8 (deflated) are read and written; any other method is Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [4, 4, 6], title := "date and time fields", status := .notImplemented,
    note := "Entry dates and times are not read; the writer stores 1980-01-01 00:00 so its output does not depend on the clock." },
  { standard := .appnote, ref := .clause [4, 4, 7], title := "CRC-32", status := .implemented,
    note := "Slicing-by-8 CRC-32 over the reflected polynomial (crates/docboss-zip/src/crc.rs), held to 40 vectors computed by the Lean reference (tests/ledger_vectors.rs)." },
  { standard := .appnote, ref := .clause [4, 4, 8], title := "compressed size", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 9], title := "uncompressed size", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 10], title := "file name length", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 11], title := "extra field length", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 12], title := "file comment length", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 13], title := "disk number start", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 14], title := "internal file attributes", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 15], title := "external file attributes", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 16], title := "relative offset of local header", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 17], title := "file name", status := .implemented,
    note := "Names decode as UTF-8 when bit 11 is set, else as code page 437 (crates/docboss-zip/src/cp437.rs, test archive.rs decodes_name_encodings)." },
  { standard := .appnote, ref := .clause [4, 4, 18], title := "file comment", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 19], title := "number of this disk", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 20], title := "number of the disk with the start of the central", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 21], title := "total number of entries in the central dir on", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 22], title := "total number of entries in the central dir", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 23], title := "size of the central directory", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 24], title := "offset of start of central directory with respect to", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 25], title := "ZIP file comment length", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 26], title := "ZIP file comment", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 27], title := "zip64 extensible data sector (variable size)", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 4, 28], title := "extra field", status := .notImplemented,
    note := "No reader code cites this field; the reader uses it only as far as the 4.3 record rows say." },
  { standard := .appnote, ref := .clause [4, 5], title := "File uses ZIP64 format extensions", status := .incomplete,
    note := "Only the ZIP64 extended information extra field (0x0001) is read; every other extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 1], title := "In order to allow different programs and different types", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 2], title := "The current Header ID mappings defined by PKWARE are", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 3], title := "Zip64 Extended Information Extra Field (0x0001)", status := .implemented,
    note := "The ZIP64 extra field supplies 64-bit sizes and offsets when the 32-bit fields are saturated (test archive.rs reads_zip64_archives); the writer emits it with WriteOptions::zip64." },
  { standard := .appnote, ref := .clause [4, 5, 4], title := "OS/2 Extra Field (0x0009)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 5], title := "NTFS Extra Field (0x000a)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 6], title := "OpenVMS Extra Field (0x000c)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 7], title := "UNIX Extra Field (0x000d)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 8], title := "PATCH Descriptor Extra Field (0x000f)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 9], title := "PKCS#7 Store for X.509 Certificates (0x0014)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 10], title := "X.509 Certificate ID and Signature for individual file (0x0015)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 11], title := "X.509 Certificate ID and Signature for central directory (0x0016)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 12], title := "Strong Encryption Header (0x0017)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 13], title := "Record Management Controls (0x0018)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 14], title := "PKCS#7 Encryption Recipient Certificate List (0x0019)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 15], title := "MVS Extra Field (0x0065)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 16], title := "OS/400 Extra Field (0x0065)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 17], title := "Policy Decryption Key Record Extra Field (0x0021)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 18], title := "Key Provider Record Extra Field (0x0022)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 5, 19], title := "Policy Key Data Record Record Extra Field (0x0023)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6], title := "File is compressed using BZIP2 compression*", status := .notImplemented,
    note := "Only stored and deflated entries are read; the extra fields third parties define are skipped by their length." },
  { standard := .appnote, ref := .clause [4, 6, 1], title := "Third party mappings commonly used are", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 2], title := "Third-party Extra Fields MUST include a Header ID using", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 3], title := "In case two different programs appropriate the same", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 4], title := "ZipIt Macintosh Extra Field (long) (0x2605)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 5], title := "ZipIt Macintosh Extra Field (short, for files) (0x2705)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 6], title := "ZipIt Macintosh Extra Field (short, for directories) (0x2805)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 7], title := "FWKCS MD5 Extra Field (0x4b46)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 8], title := "Info-ZIP Unicode Comment Extra Field (0x6375)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 9], title := "Info-ZIP Unicode Path Extra Field (0x7075)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 10], title := "Microsoft Open Packaging Growth Hint (0xa220)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 6, 11], title := "Data Stream Alignment (Apache Commons-Compress) (0xa11e)", status := .notImplemented,
    note := "This extra field is skipped by its length." },
  { standard := .appnote, ref := .clause [4, 7], title := "Manifest Files", status := .outOfScope,
    note := "Manifest files are application data; docboss reads OPC parts by name instead." },
  { standard := .appnote, ref := .clause [4, 7, 1], title := "Applications using ZIP files MAY have a need for additional", status := .outOfScope,
    note := "Manifest files are application data; docboss reads OPC parts by name instead." },
  { standard := .appnote, ref := .clause [4, 7, 2], title := "A manifest file is a file created for the application process", status := .outOfScope,
    note := "Manifest files are application data; docboss reads OPC parts by name instead." },
  { standard := .appnote, ref := .clause [4, 7, 3], title := "Manifest files MAY be compressed or encrypted as needed for", status := .outOfScope,
    note := "Manifest files are application data; docboss reads OPC parts by name instead." },
  { standard := .appnote, ref := .clause [5, 1], title := "UnShrinking - Method 1", status := .notImplemented,
    note := "Method 1 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 2], title := "Expanding - Methods 2-5", status := .notImplemented,
    note := "Method 2 to 5 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 3], title := "Imploding - Method 6", status := .notImplemented,
    note := "Method 6 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 4], title := "Tokenizing - Method 7", status := .notImplemented,
    note := "Method 7 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 5], title := "Deflating - Method 8", status := .implemented,
    note := "Deflate streams are inflated and written through flate2's zlib-rs backend, a truncated stream keeping what it inflated (tests archive.rs truncated_deflate_keeps_the_readable_prefix and write.rs every_layout_reads_back)." },
  { standard := .appnote, ref := .clause [5, 6], title := "Enhanced Deflating - Method 9", status := .notImplemented,
    note := "Method 9 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 7], title := "BZIP2 - Method 12", status := .notImplemented,
    note := "Method 12 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 8], title := "LZMA - Method 14", status := .notImplemented,
    note := "Method 14 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 9], title := "WavPack - Method 97", status := .notImplemented,
    note := "Method 97 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 10], title := "PPMd - Method 98", status := .notImplemented,
    note := "Method 98 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 11], title := "AE-x Encryption marker - Method 99", status := .notImplemented,
    note := "Method 99 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 12], title := "JPEG variant - Method 96", status := .notImplemented,
    note := "Method 96 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 13], title := "PKWARE Data Compression Library Imploding - Method 10", status := .notImplemented,
    note := "Method 10 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 14], title := "Reserved - Method 11", status := .outOfScope,
    note := "Reserved method number with nothing to implement." },
  { standard := .appnote, ref := .clause [5, 15], title := "Reserved - Method 13", status := .outOfScope,
    note := "Reserved method number with nothing to implement." },
  { standard := .appnote, ref := .clause [5, 16], title := "Reserved - Method 15", status := .outOfScope,
    note := "Reserved method number with nothing to implement." },
  { standard := .appnote, ref := .clause [5, 17], title := "IBM z/OS CMPSC Compression - Method 16", status := .notImplemented,
    note := "Method 16 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 18], title := "Reserved - Method 17", status := .outOfScope,
    note := "Reserved method number with nothing to implement." },
  { standard := .appnote, ref := .clause [5, 19], title := "IBM TERSE - Method 18", status := .notImplemented,
    note := "Method 18 is not read; such entries fail with Error::UnsupportedMethod." },
  { standard := .appnote, ref := .clause [5, 20], title := "IBM LZ77 z Architecture - Method 19", status := .notImplemented,
    note := "Method 19 is not read; such entries fail with Error::UnsupportedMethod." }
]

/-- Every row of the APPNOTE ledger. -/
def rows : List Feature :=
  rows0

end Ledger.Catalogue.Appnote
