import Ledger.Feature

/-!
Ledger rows for APPNOTE. One row per clause the scope requires, plus any deeper row a note needs.
-/

namespace Ledger.Catalogue.Appnote

open Ledger

def rows0 : List Feature := [
  { standard := .appnote, ref := .clause [4, 1], title := "What is a ZIP file", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 1], title := "ZIP files MAY be identified by the standard .ZIP file extension", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 2], title := "ZIP files SHOULD contain at least one file and MAY contain", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 3], title := "Data compression MAY be used to reduce the size of files", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 4], title := "Data encryption MAY be used to protect files within a ZIP file", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 5], title := "Data integrity MUST be provided for each file using CRC32", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 6], title := "Additional data integrity MAY be included through the use of", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 7], title := "Files MAY be placed within a ZIP file uncompressed or stored", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 8], title := "Each data file placed into a ZIP file MAY be compressed, stored,", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 9], title := "ZIP files MAY be streamed, split into segments (on fixed or on", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 10], title := "Extensibility is provided for platform or application specific", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 11], title := "Common uses for ZIP MAY also include the use of manifest files", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 1, 12], title := "ZIP files MAY be placed within other ZIP files", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 2], title := "ZIP Metadata", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 2, 1], title := "ZIP files are identified by metadata consisting of defined record types", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3], title := "General Format of a .ZIP file", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 1], title := "A ZIP file MUST contain an \"end of central directory record\"", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 2], title := "Each file placed into a ZIP file MUST be preceded by a \"local", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 3], title := "Files MAY be stored in arbitrary order within a ZIP file", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 4], title := "Compression MUST NOT be applied to a \"local file header\", an \"encryption", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 5], title := "File data MAY be followed by a \"data descriptor\" for the file", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 6], title := "Overall .ZIP file format", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 7], title := "Local file header", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 8], title := "File data", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 9], title := "Data descriptor", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 10], title := "Archive decryption header", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 11], title := "Archive extra data record", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 12], title := "Central directory structure", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 13], title := "Digital signature", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 14], title := "Zip64 end of central directory record", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 15], title := "Zip64 end of central directory locator", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 3, 16], title := "End of central directory record", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4], title := "Explanation of fields", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 1], title := "General notes on fields", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 2], title := "version made by (2 bytes)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 3], title := "version needed to extract (2 bytes)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 4], title := "general purpose bit flag", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 5], title := "compression method", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 6], title := "date and time fields", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 7], title := "CRC-32", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 8], title := "compressed size", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 9], title := "uncompressed size", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 10], title := "file name length", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 11], title := "extra field length", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 12], title := "file comment length", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 13], title := "disk number start", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 14], title := "internal file attributes", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 15], title := "external file attributes", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 16], title := "relative offset of local header", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 17], title := "file name", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 18], title := "file comment", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 19], title := "number of this disk", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 20], title := "number of the disk with the start of the central", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 21], title := "total number of entries in the central dir on", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 22], title := "total number of entries in the central dir", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 23], title := "size of the central directory", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 24], title := "offset of start of central directory with respect to", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 25], title := "ZIP file comment length", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 26], title := "ZIP file comment", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 27], title := "zip64 extensible data sector (variable size)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 4, 28], title := "extra field", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5], title := "File uses ZIP64 format extensions", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 1], title := "In order to allow different programs and different types", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 2], title := "The current Header ID mappings defined by PKWARE are", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 3], title := "Zip64 Extended Information Extra Field (0x0001)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 4], title := "OS/2 Extra Field (0x0009)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 5], title := "NTFS Extra Field (0x000a)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 6], title := "OpenVMS Extra Field (0x000c)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 7], title := "UNIX Extra Field (0x000d)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 8], title := "PATCH Descriptor Extra Field (0x000f)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 9], title := "PKCS#7 Store for X.509 Certificates (0x0014)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 10], title := "X.509 Certificate ID and Signature for individual file (0x0015)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 11], title := "X.509 Certificate ID and Signature for central directory (0x0016)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 12], title := "Strong Encryption Header (0x0017)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 13], title := "Record Management Controls (0x0018)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 14], title := "PKCS#7 Encryption Recipient Certificate List (0x0019)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 15], title := "MVS Extra Field (0x0065)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 16], title := "OS/400 Extra Field (0x0065)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 17], title := "Policy Decryption Key Record Extra Field (0x0021)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 18], title := "Key Provider Record Extra Field (0x0022)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 5, 19], title := "Policy Key Data Record Record Extra Field (0x0023)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6], title := "File is compressed using BZIP2 compression*", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 1], title := "Third party mappings commonly used are", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 2], title := "Third-party Extra Fields MUST include a Header ID using", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 3], title := "In case two different programs appropriate the same", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 4], title := "ZipIt Macintosh Extra Field (long) (0x2605)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 5], title := "ZipIt Macintosh Extra Field (short, for files) (0x2705)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 6], title := "ZipIt Macintosh Extra Field (short, for directories) (0x2805)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 7], title := "FWKCS MD5 Extra Field (0x4b46)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 8], title := "Info-ZIP Unicode Comment Extra Field (0x6375)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 9], title := "Info-ZIP Unicode Path Extra Field (0x7075)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 10], title := "Microsoft Open Packaging Growth Hint (0xa220)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 6, 11], title := "Data Stream Alignment (Apache Commons-Compress) (0xa11e)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 7], title := "Manifest Files", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 7, 1], title := "Applications using ZIP files MAY have a need for additional", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 7, 2], title := "A manifest file is a file created for the application process", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [4, 7, 3], title := "Manifest files MAY be compressed or encrypted as needed for", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 1], title := "UnShrinking - Method 1", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 2], title := "Expanding - Methods 2-5", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 3], title := "Imploding - Method 6", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 4], title := "Tokenizing - Method 7", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 5], title := "Deflating - Method 8", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 6], title := "Enhanced Deflating - Method 9", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 7], title := "BZIP2 - Method 12", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 8], title := "LZMA - Method 14", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 9], title := "WavPack - Method 97", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 10], title := "PPMd - Method 98", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 11], title := "AE-x Encryption marker - Method 99", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 12], title := "JPEG variant - Method 96", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 13], title := "PKWARE Data Compression Library Imploding - Method 10", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 14], title := "Reserved - Method 11", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 15], title := "Reserved - Method 13", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 16], title := "Reserved - Method 15", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 17], title := "IBM z/OS CMPSC Compression - Method 16", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 18], title := "Reserved - Method 17", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 19], title := "IBM TERSE - Method 18", status := .notImplemented,
    note := "Not read yet." },
  { standard := .appnote, ref := .clause [5, 20], title := "IBM LZ77 z Architecture - Method 19", status := .notImplemented,
    note := "Not read yet." }
]

/-- Every row of the APPNOTE ledger. -/
def rows : List Feature :=
  rows0

end Ledger.Catalogue.Appnote
