import Ledger.Feature

/-!
Ledger rows for ECMA-376 Part 2. One row per clause the scope requires, plus any deeper row a note needs.
-/

namespace Ledger.Catalogue.Ecma376Part2

open Ledger

def rows0 : List Feature := [
  { standard := .ecma376Part2, ref := .clause [6, 2], title := "Parts", status := .incomplete,
    note := "Part names, media types and XML parts are read; growth hints are ignored and part name syntax is not validated." },
  { standard := .ecma376Part2, ref := .clause [6, 2, 2], title := "Part names", status := .incomplete,
    note := "Part names resolve and compare case-insensitively (test structure.rs part_names_compare_case_insensitively); their syntax is not validated, so malformed names are read as written." },
  { standard := .ecma376Part2, ref := .clause [6, 2, 3], title := "Media types", status := .implemented,
    note := "A part's media type comes from its Override, else the Default for its extension (package.rs content_type, test structure.rs part_names_compare_case_insensitively)." },
  { standard := .ecma376Part2, ref := .clause [6, 2, 4], title := "Growth hint", status := .outOfScope,
    note := "Growth hints pad parts for in-place editing; readers ignore them." },
  { standard := .ecma376Part2, ref := .clause [6, 2, 5], title := "XML usage", status := .notImplemented,
    note := "The clause's XML restrictions are not enforced: a DOCTYPE is skipped rather than refused and any encoding the tokenizer can decode is accepted." },
  { standard := .ecma376Part2, ref := .clause [6, 3], title := "Part addressing", status := .outOfScope,
    note := "Pack IRIs address parts from outside the package; docboss reads parts by name." },
  { standard := .ecma376Part2, ref := .clause [6, 3, 2], title := "Pack scheme", status := .outOfScope,
    note := "Pack IRIs address parts from outside the package; docboss reads parts by name." },
  { standard := .ecma376Part2, ref := .clause [6, 3, 3], title := "Resolving a pack IRI to a resource", status := .outOfScope,
    note := "Pack IRIs address parts from outside the package; docboss reads parts by name." },
  { standard := .ecma376Part2, ref := .clause [6, 3, 4], title := "Composing a pack IRI", status := .outOfScope,
    note := "Pack IRIs address parts from outside the package; docboss reads parts by name." },
  { standard := .ecma376Part2, ref := .clause [6, 3, 5], title := "Equivalence", status := .outOfScope,
    note := "Pack IRIs address parts from outside the package; docboss reads parts by name." },
  { standard := .ecma376Part2, ref := .clause [6, 4], title := "Resolving relative references", status := .implemented,
    note := "Relationship targets resolve against the source part's directory with dot segments removed and percent escapes decoded (package.rs resolve_target, unit test resolves_targets)." },
  { standard := .ecma376Part2, ref := .clause [6, 4, 2], title := "Base IRIs", status := .implemented,
    note := "The source part is the base IRI of its relationships (package.rs resolve_target, unit test resolves_targets)." },
  { standard := .ecma376Part2, ref := .clause [6, 4, 3], title := "Examples", status := .outOfScope,
    note := "Informative examples; the unit test resolves_targets follows them." },
  { standard := .ecma376Part2, ref := .clause [6, 5], title := "Relationships", status := .implemented,
    note := "Package and part relationships are read by id with their type, target and target mode (package.rs, tests structure.rs and package.rs names_relationship_parts)." },
  { standard := .ecma376Part2, ref := .clause [6, 5, 2], title := "Relationships part", status := .implemented,
    note := "A part's relationships part name is derived from the part name, the package's being _rels/.rels (package.rs rels_name, unit test names_relationship_parts)." },
  { standard := .ecma376Part2, ref := .clause [6, 5, 3], title := "Relationship markup", status := .implemented,
    note := "Relationship Id, Type, Target and TargetMode are read; type URIs match on their last segment, so transitional and strict types agree (test structure.rs part_names_compare_case_insensitively)." },
  { standard := .ecma376Part2, ref := .clause [6, 5, 4], title := "Examples", status := .outOfScope,
    note := "Informative examples." },
  { standard := .ecma376Part2, ref := .clause [7, 2], title := "Physical mapping guidelines", status := .incomplete,
    note := "Parts map to ZIP items by name and media types come from the Media Types stream; interleaved parts are not reassembled." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 1], title := "Using features of physical formats", status := .outOfScope,
    note := "Guidance for designers of physical formats." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 2], title := "Mapped components", status := .outOfScope,
    note := "Guidance for designers of physical formats." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 3], title := "Mapping media types to parts", status := .implemented,
    note := "[Content_Types].xml Default and Override elements are read (package.rs read_content_types, tests structure.rs part_names_compare_case_insensitively and write package.rs every_part_has_a_content_type)." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 4], title := "Interleaving", status := .notImplemented,
    note := "Interleaved parts (split into [n].piece items) are not reassembled; such a part is not found." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 5], title := "Mapping part names to physical package item names", status := .implemented,
    note := "A part name maps to the ZIP item of the same name without its leading slash (package.rs existing_name, test structure.rs part_names_compare_case_insensitively)." },
  { standard := .ecma376Part2, ref := .clause [7, 3], title := "Mapping to a ZIP file", status := .incomplete,
    note := "Parts are read from and written to ZIP items with the Media Types stream; interleaved pieces and growth hints are not handled." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 2], title := "Mapping part data", status := .implemented,
    note := "Part data is the ZIP item's data (test structure.rs part_names_compare_case_insensitively)." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 3], title := "ZIP item names", status := .implemented,
    note := "ZIP item names are decoded per APPNOTE and matched to part names (test structure.rs part_names_compare_case_insensitively)." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 4], title := "Mapping logical item names to ZIP item names", status := .implemented,
    note := "The writer stores each part under its name without the leading slash (crates/docboss-write/src/package.rs, test package.rs every_part_has_a_content_type)." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 5], title := "Mapping ZIP item names to logical item names", status := .implemented,
    note := "ZIP item names match part names case-insensitively (test structure.rs part_names_compare_case_insensitively)." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 6], title := "ZIP package limitations", status := .outOfScope,
    note := "Constraints on producers; the reader accepts ZIP64 archives and names beyond them." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 7], title := "Mapping the Media Types stream", status := .implemented,
    note := "The Media Types stream is the [Content_Types].xml item, read by the reader and written by the writer (tests structure.rs part_names_compare_case_insensitively and package.rs every_part_has_a_content_type)." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 8], title := "Mapping the growth hint", status := .outOfScope,
    note := "Growth hints pad parts for in-place editing; readers ignore them." },
  { standard := .ecma376Part2, ref := .clause [8, 2], title := "Core Properties part", status := .implemented,
    note := "The core properties part is found through the package relationship (parts.rs properties, test structure.rs document_properties)." },
  { standard := .ecma376Part2, ref := .clause [8, 3], title := "Core properties markup", status := .incomplete,
    note := "Title, subject, creator, keywords, description, lastModifiedBy, revision, created, modified and category are read; contentStatus, identifier, language, lastPrinted and version are not." },
  { standard := .ecma376Part2, ref := .clause [8, 3, 2], title := "Support for versioning and extensibility", status := .notImplemented,
    note := "Markup compatibility attributes in the core properties part are not processed." },
  { standard := .ecma376Part2, ref := .clause [8, 3, 3], title := "coreProperties element", status := .implemented,
    note := "The coreProperties root is read (test structure.rs document_properties)." },
  { standard := .ecma376Part2, ref := .clause [8, 3, 4], title := "Core property elements", status := .incomplete,
    note := "Ten core property elements are read (test structure.rs document_properties); contentStatus, identifier, language, lastPrinted and version are not." },
  { standard := .ecma376Part2, ref := .clause [10, 2], title := "Overview of OPC-specific restrictions and extensions to “XML-Signature Syntax and Processing”", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 3], title := "Choosing content to sign", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 4], title := "Digital signature parts", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 4, 2], title := "Digital Signature Origin part", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 4, 3], title := "Digital Signature XML Signature part", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 4, 4], title := "Digital Signature Certificate part", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5], title := "Digital signature markup", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 2], title := "Support for versioning and extensibility", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 3], title := "Signature element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 4], title := "SignedInfo element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 5], title := "CanonicalizationMethod element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 6], title := "SignatureMethod element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 7], title := "Reference element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 8], title := "Transform element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 9], title := "RelationshipReference element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 10], title := "RelationshipsGroupReference element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 11], title := "DigestMethod element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 12], title := "Object element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 13], title := "Manifest element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 14], title := "SignatureProperty element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 15], title := "SignatureTime element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 16], title := "Format element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 17], title := "Value element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 18], title := "XPath element", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 6], title := "Relationships transform algorithm", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 7], title := "Digital signature example", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 8], title := "Generating signatures", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." },
  { standard := .ecma376Part2, ref := .clause [10, 9], title := "Validating signatures", status := .outOfScope,
    note := "Digital signatures are not read or verified; reading content does not depend on them." }
]

/-- Every row of the ECMA-376 Part 2 ledger. -/
def rows : List Feature :=
  rows0

end Ledger.Catalogue.Ecma376Part2
