import Ledger.Feature

/-!
Ledger rows for ECMA-376 Part 1. One row per clause the scope requires, plus any deeper row a note needs.
-/

namespace Ledger.Catalogue.Ecma376Part1

open Ledger

def rows0 : List Feature := [
  { standard := .ecma376Part1, ref := .clause [11, 3], title := "Part Summary", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 1], title := "Alternative Format Import Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 2], title := "Comments Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 3], title := "Document Settings Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 4], title := "Endnotes Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 5], title := "Font Table Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 6], title := "Footer Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 7], title := "Footnotes Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 8], title := "Glossary Document Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 9], title := "Header Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 10], title := "Main Document Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 11], title := "Numbering Definitions Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 12], title := "Style Definitions Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [11, 3, 13], title := "Web Settings Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2], title := "Part Summary", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 1], title := "Additional Characteristics Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 2], title := "Audio Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 3], title := "Bibliography Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 4], title := "Content Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 5], title := "Custom XML Data Storage Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 6], title := "Custom XML Data Storage Properties Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 7], title := "Digital Signature Origin Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 8], title := "Digital Signature XML Signature Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 9], title := "Embedded Control Persistence Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 10], title := "Embedded Object Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 11], title := "Embedded Package Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 12], title := "File Properties", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 13], title := "Font Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 14], title := "Image Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 15], title := "Printer Settings Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 16], title := "Thumbnail Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [15, 2, 17], title := "Video Part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 1], title := "Table of Contents", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 2], title := "Main Document Story", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 2, 1], title := "background (Document Background)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 2, 2], title := "body (Document Body)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 2, 3], title := "document (Document)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 3], title := "Paragraphs and Rich Formatting", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 3, 1], title := "Paragraphs", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 3, 2], title := "Run", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 3, 3], title := "Run Content", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 3, 4], title := "Border Properties (CT_Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 3, 5], title := "Shading Properties (CT_Shd)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4], title := "Tables", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 1], title := "bidiVisual (Visually Right to Left Table)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 2], title := "bottom (Table Cell Bottom Margin Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 3], title := "bottom (Table Cell Bottom Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 4], title := "bottom (Table Bottom Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 5], title := "bottom (Table Cell Bottom Margin Default)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 6], title := "cantSplit (Table Row Cannot Break Across Pages)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 7], title := "cnfStyle (Table Row Conditional Formatting)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 8], title := "cnfStyle (Table Cell Conditional Formatting)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 9], title := "divId (Associated HTML div ID)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 10], title := "end (Table Cell Trailing Margin Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 11], title := "end (Table Cell Trailing Margin Default)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 12], title := "end (Table Cell Trailing Edge Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 13], title := "end (Table Trailing Edge Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 14], title := "gridAfter (Grid Columns After Last Cell)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 15], title := "gridBefore (Grid Columns Before First Cell)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 16], title := "gridCol (Grid Column Definition)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 17], title := "gridSpan (Grid Columns Spanned by Current Table Cell)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 18], title := "header (Header Cell Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 19], title := "headers (Header Cells Associated With Table Cell)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 20], title := "hidden (Hidden Table Row Marker)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 21], title := "hideMark (Ignore End Of Cell Marker In Row Height Calculation)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 22], title := "insideH (Table Inside Horizontal Edges Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 23], title := "insideH (Table Cell Inside Horizontal Edges Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 24], title := "insideV (Table Inside Vertical Edges Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 25], title := "insideV (Table Cell Inside Vertical Edges Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 26], title := "jc (Table Alignment Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 27], title := "jc (Table Row Alignment)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 28], title := "jc (Table Alignment)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 29], title := "noWrap (Don't Wrap Cell Content)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 30], title := "shd (Table Shading Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 31], title := "shd (Table Shading)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 32], title := "shd (Table Cell Shading)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 33], title := "start (Table Cell Leading Edge Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 34], title := "start (Table Cell Leading Margin Default)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 35], title := "start (Table Cell Leading Margin Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 36], title := "start (Table Leading Edge Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 37], title := "tbl (Table)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 38], title := "tblBorders (Table Borders)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 39], title := "tblBorders (Table Borders Exceptions)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 40], title := "tblCaption (Table Caption)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 41], title := "tblCellMar (Table Cell Margin Exceptions)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 42], title := "tblCellMar (Table Cell Margin Defaults)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 43], title := "tblCellSpacing (Table Row Cell Spacing)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 44], title := "tblCellSpacing (Table Cell Spacing Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 45], title := "tblCellSpacing (Table Cell Spacing Default)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 46], title := "tblDescription (Table Description)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 47], title := "tblGrid (Previous Table Grid)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 48], title := "tblGrid (Table Grid)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 49], title := "tblHeader (Repeat Table Row on Every New Page)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 50], title := "tblInd (Table Indent from Leading Margin)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 51], title := "tblInd (Table Indent from Leading Margin Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 52], title := "tblLayout (Table Layout)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 53], title := "tblLayout (Table Layout Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 54], title := "tblLook (Table Style Conditional Formatting Settings Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 55], title := "tblLook (Table Style Conditional Formatting Settings)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 56], title := "tblOverlap (Floating Table Allows Other Tables to Overlap)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 57], title := "tblpPr (Floating Table Positioning)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 58], title := "tblPr (Previous Table Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 59], title := "tblPr (Table Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 60], title := "tblPrEx (Table-Level Property Exceptions)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 61], title := "tblPrEx (Previous Table-Level Property Exceptions)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 62], title := "tblStyle (Referenced Table Style)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 63], title := "tblW (Preferred Table Width)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 64], title := "tblW (Preferred Table Width Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 65], title := "tc (Table Cell)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 66], title := "tcBorders (Table Cell Borders)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 67], title := "tcFitText (Fit Text Within Cell)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 68], title := "tcMar (Single Table Cell Margins)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 69], title := "tcPr (Table Cell Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 70], title := "tcPr (Previous Table Cell Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 71], title := "tcW (Preferred Table Cell Width)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 72], title := "textDirection (Table Cell Text Flow Direction)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 73], title := "tl2br (Table Cell Top Left to Bottom Right Diagonal Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 74], title := "top (Table Cell Top Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 75], title := "top (Table Cell Top Margin Default)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 76], title := "top (Table Top Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 77], title := "top (Table Cell Top Margin Exception)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 78], title := "tr (Table Row)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 79], title := "tr2bl (Table Cell Top Right to Bottom Left Diagonal Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 80], title := "trHeight (Table Row Height)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 81], title := "trPr (Table Row Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 82], title := "trPr (Previous Table Row Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 83], title := "vAlign (Table Cell Vertical Alignment)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 84], title := "vMerge (Vertically Merged Cell)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 85], title := "wAfter (Preferred Width After Table Row)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 86], title := "wBefore (Preferred Width Before Table Row)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 4, 87], title := "Table Measurement (CT_TblWidth)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 5], title := "Custom Markup", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 5, 1], title := "Custom XML and Smart Tags", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 5, 2], title := "Structured Document Tags", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6], title := "Sections", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 1], title := "bidi (Right to Left Section Layout)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 2], title := "bottom (Bottom Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 3], title := "col (Single Column Definition)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 4], title := "cols (Column Definitions)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 5], title := "docGrid (Document Grid)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 6], title := "formProt (Only Allow Editing of Form Fields)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 7], title := "left (Left Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 8], title := "lnNumType (Line Numbering Settings)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 9], title := "paperSrc (Paper Source Information)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 10], title := "pgBorders (Page Borders)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 11], title := "pgMar (Page Margins)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 12], title := "pgNumType (Page Numbering Settings)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 13], title := "pgSz (Page Size)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 14], title := "printerSettings (Reference to Printer Settings Data)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 15], title := "right (Right Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 16], title := "rtlGutter (Gutter on Right Side of Page)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 17], title := "sectPr (Document Final Section Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 18], title := "sectPr (Section Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 19], title := "sectPr (Previous Section Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 20], title := "textDirection (Text Flow Direction)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 21], title := "top (Top Border)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 22], title := "type (Section Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 6, 23], title := "vAlign (Vertical Text Alignment on Page)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 7], title := "Styles", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 7, 1], title := "Style Inheritance", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 7, 2], title := "Style Hierarchy", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 7, 3], title := "Toggle Properties", status := .incomplete,
    note := "docboss-model resolves the paragraph style chain and the character style chain separately and combines their toggle values by XOR, direct formatting winning (crates/docboss-model/src/style.rs Styles::resolve_run, test resolution.rs toggle_properties_cancel_across_style_kinds); a table style's contribution is not part of the XOR yet." },
  { standard := .ecma376Part1, ref := .clause [17, 7, 4], title := "General Style Properties", status := .notImplemented,
    note := "No reader parses style definitions yet. docboss-model resolves basedOn chains root first with a cycle and length cap (Styles::chain, test resolution.rs based_on_chain_resolves_root_first cites 17.7.4.3), but no implementation comment cites the clause." },
  { standard := .ecma376Part1, ref := .clause [17, 7, 5], title := "Document Defaults", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 7, 6], title := "Table Styles", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 7, 7], title := "Numbering Styles", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 7, 8], title := "Paragraph Styles", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 7, 9], title := "Run (Character) Styles", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 8], title := "Fonts", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 8, 1], title := "Font Embedding", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 8, 2], title := "Font Substitution", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 8, 3], title := "Elements", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9], title := "Numbering", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 1], title := "abstractNum (Abstract Numbering Definition)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 2], title := "abstractNumId (Abstract Numbering Definition Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 3], title := "ilvl (Numbering Level Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 4], title := "isLgl (Display All Levels Using Arabic Numerals)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 5], title := "lvl (Numbering Level Override Definition)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 6], title := "lvl (Numbering Level Definition)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 7], title := "lvlJc (Justification)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 8], title := "lvlOverride (Numbering Level Definition Override)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 9], title := "lvlPicBulletId (Picture Numbering Symbol Definition Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 10], title := "lvlRestart (Restart Numbering Level Symbol)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 11], title := "lvlText (Numbering Level Text)", status := .notImplemented,
    note := "No reader parses numbering definitions yet. docboss-model expands %1 to %9 in a level's text through NumberingCounter::next (test resolution.rs multilevel_labels_count_and_restart cites the clause), but no implementation comment cites it." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 12], title := "multiLevelType (Abstract Numbering Definition Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 13], title := "name (Abstract Numbering Definition Name)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 14], title := "nsid (Abstract Numbering Definition Identifier)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 15], title := "num (Numbering Definition Instance)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 16], title := "numbering (Numbering Definitions)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 17], title := "numFmt (Numbering Format)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 18], title := "numId (Numbering Definition Instance Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 19], title := "numIdMacAtCleanup (Last Reviewed Abstract Numbering Definition)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 20], title := "numPicBullet (Picture Numbering Symbol Definition)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 21], title := "numStyleLink (Numbering Style Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 22], title := "pPr (Numbering Level Associated Paragraph Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 23], title := "pStyle (Paragraph Style's Associated Numbering Level)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 24], title := "rPr (Numbering Symbol Run Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 25], title := "start (Starting Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 26], title := "startOverride (Numbering Level Starting Value Override)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 27], title := "styleLink (Numbering Style Definition)", status := .notImplemented,
    note := "Not read yet." }
]

def rows1 : List Feature := [
  { standard := .ecma376Part1, ref := .clause [17, 9, 28], title := "suff (Content Between Numbering Symbol and Paragraph Text)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 9, 29], title := "tmpl (Numbering Template Code)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 10], title := "Headers and Footers", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 10, 1], title := "evenAndOddHeaders (Different Even/Odd Page Headers and Footers)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 10, 2], title := "footerReference (Footer Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 10, 3], title := "ftr (Footer)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 10, 4], title := "hdr (Header)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 10, 5], title := "headerReference (Header Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 10, 6], title := "titlePg (Different First Page Headers and Footers)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11], title := "Footnotes and Endnotes", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 1], title := "continuationSeparator (Continuation Separator Mark)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 2], title := "endnote (Endnote Content)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 3], title := "endnote (Special Endnote List)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 4], title := "endnotePr (Document-Wide Endnote Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 5], title := "endnotePr (Section-Wide Endnote Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 6], title := "endnoteRef (Endnote Reference Mark)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 7], title := "endnoteReference (Endnote Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 8], title := "endnotes (Document Endnotes)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 9], title := "footnote (Special Footnote List)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 10], title := "footnote (Footnote Content)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 11], title := "footnotePr (Section-Wide Footnote Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 12], title := "footnotePr (Document-Wide Footnote Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 13], title := "footnoteRef (Footnote Reference Mark)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 14], title := "footnoteReference (Footnote Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 15], title := "footnotes (Document Footnotes)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 16], title := "noEndnote (Suppress Endnotes In Document)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 17], title := "numFmt (Endnote Numbering Format)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 18], title := "numFmt (Footnote Numbering Format)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 19], title := "numRestart (Footnote and Endnote Numbering Restart Location)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 20], title := "numStart (Footnote and Endnote Numbering Starting Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 21], title := "pos (Footnote Placement)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 22], title := "pos (Endnote Placement)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 11, 23], title := "separator (Footnote/Endnote Separator Mark)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12], title := "Glossary Document", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 1], title := "behavior (Entry Insertion Behavior)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 2], title := "behaviors (Entry Insertion Behaviors)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 3], title := "category (Entry Categorization)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 4], title := "description (Description for Entry)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 5], title := "docPart (Glossary Document Entry)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 6], title := "docPartBody (Contents of Glossary Document Entry)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 7], title := "docPartPr (Glossary Document Entry Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 8], title := "docParts (List of Glossary Document Entries)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 9], title := "gallery (Gallery Associated With Entry)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 10], title := "glossaryDocument (Glossary Document Root Element)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 11], title := "guid (Entry ID)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 12], title := "name (Category Associated With Entry)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 13], title := "name (Entry Name)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 14], title := "style (Associated Paragraph Style Name)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 15], title := "type (Entry Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 12, 16], title := "types (Entry Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 13], title := "Annotations", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 13, 1], title := "Inline Annotations", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 13, 3], title := "Property Annotations", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 13, 4], title := "Comments", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 13, 5], title := "Revisions", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 13, 6], title := "Bookmarks", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 13, 7], title := "Range Permissions", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 13, 8], title := "Spelling and Grammar", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14], title := "Mail Merge", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 1], title := "active (Record Is Included in Mail Merge)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 2], title := "activeRecord (Record Currently Displayed In Merged Document)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 3], title := "addressFieldName (Column Containing E-mail Address)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 4], title := "checkErrors (Mail Merge Error Reporting Setting)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 5], title := "colDelim (Column Delimiter for Data Source)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 6], title := "column (Index of Column Being Mapped)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 7], title := "column (Index of Column Containing Unique Values for Record)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 8], title := "connectString (Data Source Connection String)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 9], title := "dataSource (Data Source File Path)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 10], title := "dataType (Data Source Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 11], title := "destination (Merged Document Destination)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 12], title := "doNotSuppressBlankLines (Remove Blank Lines from Merged Documents)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 13], title := "dynamicAddress (Use Country-Based Address Field Ordering)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 14], title := "fHdr (First Row of Data Source Contains Column Names)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 15], title := "fieldMapData (External Data Source to Merge Field Mapping)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 16], title := "headerSource (Header Definition File Path)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 17], title := "lid (Merge Field Name Language ID)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 18], title := "linkToQuery (Query Contains Link to External Query File)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 19], title := "mailAsAttachment (Merged Document To E-Mail Attachment)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 20], title := "mailMerge (Mail Merge Settings)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 21], title := "mailSubject (Merged E-mail or Fax Subject Line)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 22], title := "mainDocumentType (Source Document Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 23], title := "mappedName (Predefined Merge Field Name)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 24], title := "name (Data Source Name for Column)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 25], title := "odso (Office Data Source Object Settings)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 26], title := "query (Query For Data Source Records To Merge)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 27], title := "recipientData (Data About Single Data Source Record)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 28], title := "recipientData (Reference to Inclusion/Exclusion Data for Data Source)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 29], title := "recipients (Inclusion/Exclusion Data for Data Source)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 30], title := "src (ODSO Data Source File Path)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 31], title := "table (Data Source Table Name)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 32], title := "type (ODSO Data Source Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 33], title := "type (Merge Field Mapping)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 34], title := "udl (UDL Connection String)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 35], title := "uniqueTag (Unique Value for Record)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 14, 36], title := "viewMergedData (View Merged Data Within Document)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 15], title := "Settings", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 15, 1], title := "Document Settings", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 15, 2], title := "Web Page Settings", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 15, 3], title := "Language Compatibility Settings", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16], title := "Fields and Hyperlinks", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 1], title := "Syntax", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 2], title := "XML representation", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 3], title := "Formulas and expressions", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 4], title := "Field formatting", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 5], title := "Field definitions", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 6], title := "calcOnExit (Recalculate Fields When Current Field Is Modified)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 7], title := "checkBox (Checkbox Form Field Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 8], title := "checked (Checkbox Form Field State)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 9], title := "ddList (Drop-Down List Form Field Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 10], title := "default (Default Text Box Form Field String)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 11], title := "default (Default Drop-Down List Item Index)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 12], title := "default (Default Checkbox Form Field State)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 13], title := "delInstrText (Deleted Field Code)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 14], title := "enabled (Form Field Enabled)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 15], title := "entryMacro (Script Function to Execute on Form Field Entry)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 16], title := "exitMacro (Script Function to Execute on Form Field Exit)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 17], title := "ffData (Form Field Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 18], title := "fldChar (Complex Field Character)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 19], title := "fldSimple (Simple Field)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 20], title := "format (Text Box Form Field Formatting)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 21], title := "helpText (Associated Help Text)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 22], title := "hyperlink (Hyperlink)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 23], title := "instrText (Field Code)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 24], title := "label (Form Field Label)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 25], title := "listEntry (Drop-Down List Entry)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 26], title := "maxLength (Text Box Form Field Maximum Length)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 27], title := "name (Form Field Name)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 28], title := "result (Drop-Down List Selection)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 29], title := "size (Checkbox Form Field Size)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 30], title := "sizeAuto (Automatically Size Form Field)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 31], title := "statusText (Associated Status Text)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 32], title := "tabIndex (Form Field Navigation Order Index)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 33], title := "textInput (Text Box Form Field Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 16, 34], title := "type (Text Box Form Field Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 17], title := "Miscellaneous Topics", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 17, 1], title := "Subdocuments", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 17, 2], title := "Alternative Format Import", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 17, 3], title := "Roundtripping Alternate Content", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 17, 4], title := "Boolean Property (CT_OnOff)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18], title := "Simple Types", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 1], title := "ST_AnnotationVMerge (Table Cell Vertical Merge Revision Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 2], title := "ST_Border (Border Styles)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 3], title := "ST_BrClear (Line Break Text Wrapping Restart Location)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 4], title := "ST_BrType (Break Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 5], title := "ST_CaptionPos (Automatic Caption Positioning Values)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 6], title := "ST_ChapterSep (Chapter Separator Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 7], title := "ST_CharacterSpacing (Character-Level Whitespace Compression Settings)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 8], title := "ST_CombineBrackets (Two Lines in One Enclosing Character Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 9], title := "ST_DateTime (Standard Date and Time Storage Format)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 10], title := "ST_DecimalNumber (Decimal Number Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 11], title := "ST_DecimalNumberOrPercent (Percentage Measurement)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 12], title := "ST_Direction (Bidirectional Direction Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 13], title := "ST_DisplacedByCustomXml (Location of Custom XML Markup Displacing an Annotation)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 14], title := "ST_DocGrid (Document Grid Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 15], title := "ST_DocPartBehavior (Insertion Behavior Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 16], title := "ST_DocPartGallery (Entry Gallery Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 17], title := "ST_DocPartType (Entry Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 18], title := "ST_DocProtect (Document Protection Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 19], title := "ST_DocType (Document Classification Values)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 20], title := "ST_DropCap (Text Frame Drop Cap Location)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 21], title := "ST_EdGrp (Range Permision Editing Group)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 22], title := "ST_EdnPos (Endnote Positioning Location)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 23], title := "ST_EighthPointMeasure (Measurement in Eighths of a Point)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 24], title := "ST_Em (Emphasis Mark Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 25], title := "ST_FFHelpTextVal (Help Text Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 26], title := "ST_FFName (Form Field Name Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 27], title := "ST_FFStatusTextVal (Status Text Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 28], title := "ST_FFTextType (Text Box Form Field Type Values)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 29], title := "ST_FldCharType (Complex Field Character Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 30], title := "ST_FontFamily (Font Family Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 31], title := "ST_FrameLayout (Frameset Layout Order)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 32], title := "ST_FrameScrollbar (Frame Scrollbar Visibility)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 33], title := "ST_FtnEdn (Footnote or Endnote Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 34], title := "ST_FtnPos (Footnote Positioning Location)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 35], title := "ST_HAnchor (Horizontal Anchor Location)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 36], title := "ST_HdrFtr (Header or Footer Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 37], title := "ST_HeightRule (Height Rule)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 38], title := "ST_HexColor (Color Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 39], title := "ST_HexColorAuto (‘Automatic’ Color Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 40], title := "ST_HighlightColor (Text Highlight Colors)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 41], title := "ST_Hint (Font Type Hint)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 42], title := "ST_HpsMeasure (Measurement in Half-Points)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 43], title := "ST_InfoTextType (Help or Status Text Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 44], title := "ST_Jc (Horizontal Alignment Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 45], title := "ST_JcTable (Table Alignment Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 46], title := "ST_LevelSuffix (Content Between Numbering Symbol and Paragraph Text)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 47], title := "ST_LineNumberRestart (Line Numbering Restart Position)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 48], title := "ST_LineSpacingRule (Line Spacing Rule)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 49], title := "ST_Lock (Locking Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 50], title := "ST_LongHexNumber (Eight Digit Hexadecimal Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 51], title := "ST_MacroName (Script Subroutine Name Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 52], title := "ST_MailMergeDataType (Mail Merge Data Source Type Values)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 53], title := "ST_MailMergeDest (Merged Document Destination Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 54], title := "ST_MailMergeDocType (Source Document Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 55], title := "ST_MailMergeOdsoFMDFieldType (Merge Field Mapping Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 56], title := "ST_MailMergeSourceType (Mail Merge ODSO Data Source Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 57], title := "ST_Merge (Merged Cell Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 58], title := "ST_MultiLevelType (Numbering Definition Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 59], title := "ST_NumberFormat (Numbering Format)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 60], title := "ST_ObjectDrawAspect (Embedded Object Representations)", status := .notImplemented,
    note := "Not read yet." }
]

def rows2 : List Feature := [
  { standard := .ecma376Part1, ref := .clause [17, 18, 61], title := "ST_ObjectUpdateMode (Embedded Object Update Modes)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 62], title := "ST_PageBorderDisplay (Page Border Display Options)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 63], title := "ST_PageBorderOffset (Page Border Positioning Base)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 64], title := "ST_PageBorderZOrder (Page Border Z-Order)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 65], title := "ST_PageOrientation (Page Orientation)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 66], title := "ST_Pitch (Font Pitch Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 67], title := "ST_PixelsMeasure (Measurement in Pixels)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 68], title := "ST_PointMeasure (Measurement in Points)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 69], title := "ST_Proof (Proofing State Values)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 70], title := "ST_ProofErr (Proofing Error Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 71], title := "ST_PTabAlignment (Absolute Position Tab Alignment)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 72], title := "ST_PTabLeader (Absolute Position Tab Leader Character)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 73], title := "ST_PTabRelativeTo (Absolute Position Tab Positioning Base)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 74], title := "ST_RestartNumber (Footnote/Endnote Numbering Restart Locations)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 75], title := "ST_RubyAlign (Phonetic Guide Text Alignment)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 76], title := "ST_SdtDateMappingType (Date Storage Format Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 77], title := "ST_SectionMark (Section Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 78], title := "ST_Shd (Shading Patterns)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 79], title := "ST_ShortHexNumber (Four Digit Hexadecimal Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 80], title := "ST_SignedHpsMeasure (Signed Measurement in Half-Points)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 81], title := "ST_SignedTwipsMeasure (Signed Measurement in Twentieths of a Point)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 82], title := "ST_StyleSort (Style Sort Settings)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 83], title := "ST_StyleType (Style Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 84], title := "ST_TabJc (Custom Tab Stop Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 85], title := "ST_TabTlc (Custom Tab Stop Leader Character)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 86], title := "ST_TargetScreenSz (Target Screen Sizes for Generated Web Pages)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 87], title := "ST_TblLayoutType (Table Layout Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 88], title := "ST_TblOverlap (Table Overlap Setting)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 89], title := "ST_TblStyleOverrideType (Conditional Table Style Formatting Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 90], title := "ST_TblWidth (Table Width Units)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 91], title := "ST_TextAlignment (Vertical Text Alignment Types)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 92], title := "ST_TextboxTightWrap (Lines To Tight Wrap Within Text Box)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 93], title := "ST_TextDirection (Text Flow Direction)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 94], title := "ST_TextEffect (Animated Text Effects)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 95], title := "ST_TextScale (Text Expansion/Compression Percentage)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 96], title := "ST_Theme (Theme Font)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 97], title := "ST_ThemeColor (Theme Color)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 98], title := "ST_UcharHexNumber (Two Digit Hexadecimal Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 99], title := "ST_Underline (Underline Patterns)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 100], title := "ST_VAnchor (Vertical Anchor Location)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 101], title := "ST_VerticalJc (Vertical Alignment Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 102], title := "ST_View (Document View Values)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 103], title := "ST_WmlColorSchemeIndex (Theme Color Reference)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 104], title := "ST_Wrap (Text Wrapping around Text Frame Type)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 105], title := "ST_Zoom (Magnification Preset Values)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 106], title := "ST_TextScalePercent (Text Expansion/Compression Percentage)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [17, 18, 107], title := "ST_MeasurementOrPercent (Measurement or Percentage Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4], title := "DrawingML - WordprocessingML Drawing", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2], title := "Elements", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 1], title := "align (Relative Horizontal Alignment)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 2], title := "align (Relative Vertical Alignment)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 3], title := "anchor (Anchor for Floating DrawingML Object)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 4], title := "cNvGraphicFramePr (Common DrawingML Non-Visual Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 5], title := "docPr (Drawing Object Non-Visual Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 6], title := "effectExtent (Object Extents Including Effects)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 7], title := "extent (Drawing Object Size)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 8], title := "inline (Inline DrawingML Object)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 9], title := "lineTo (Wrapping Polygon Line End Position)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 10], title := "positionH (Horizontal Positioning)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 11], title := "positionV (Vertical Positioning)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 12], title := "posOffset (Absolute Position Offset)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 13], title := "simplePos (Simple Positioning Coordinates)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 14], title := "start (Wrapping Polygon Start)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 15], title := "wrapNone (No Text Wrapping)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 16], title := "wrapPolygon (Wrapping Polygon)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 17], title := "wrapSquare (Square Wrapping)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 18], title := "wrapThrough (Through Wrapping)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 19], title := "wrapTight (Tight Wrapping)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 20], title := "wrapTopAndBottom (Top and Bottom Wrapping)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 21], title := "bg (Background Formatting)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 22], title := "bodyPr (Body Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 23], title := "cNvCnPr (Non-Visual Connector Shape Drawing Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 24], title := "cNvContentPartPr (Non-Visual Content Part Drawing Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 25], title := "cNvFrPr (Non-Visual Graphic Frame Drawing Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 26], title := "cNvGrpSpPr (Non-Visual Group Shape Drawing Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 27], title := "cNvPr (Non-Visual Drawing Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 28], title := "cNvSpPr (Non-Visual Drawing Properties for a Shape)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 29], title := "contentPart (Content Part)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 30], title := "extLst (Extension List)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 31], title := "graphicFrame (Graphical object container)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 32], title := "grpSp (Group Shape)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 33], title := "grpSpPr (Group Shape Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 34], title := "linkedTxbx (Textual contents of shape)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 35], title := "spPr (Shape Properties)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 36], title := "style (Shape Style)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 37], title := "txbx (Textual contents of shape)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 38], title := "txbxContent (Rich Text Box Content Container)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 39], title := "wgp (WordprocessingML Shape Group)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 40], title := "whole (Whole E2O Formatting)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 41], title := "wpc (WordprocessingML Drawing Canvas)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 42], title := "wsp (WordprocessingML Shape)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 2, 43], title := "xfrm (2D Transform for Graphic Frames)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 3], title := "Simple Types", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 3, 1], title := "ST_AlignH (Relative Horizontal Alignment Positions)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 3, 2], title := "ST_AlignV (Vertical Alignment Definition)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 3, 3], title := "ST_PositionOffset (Absolute Position Offset Value)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 3, 4], title := "ST_RelFromH (Horizontal Relative Positioning)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 3, 5], title := "ST_RelFromV (Vertical Relative Positioning)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 3, 6], title := "ST_WrapDistance (Distance from Text)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [20, 4, 3, 7], title := "ST_WrapText (Text Wrapping Location)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [22, 2], title := "Extended Properties", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part1, ref := .clause [22, 2, 2], title := "Elements", status := .notImplemented,
    note := "Not read yet." }
]

/-- Every row of the ECMA-376 Part 1 ledger. -/
def rows : List Feature :=
  rows0 ++ rows1 ++ rows2

end Ledger.Catalogue.Ecma376Part1
