import Ledger.Feature

/-!
Ledger rows for ECMA-376 Part 2. One row per clause the scope requires, plus any deeper row a note needs.
-/

namespace Ledger.Catalogue.Ecma376Part2

open Ledger

def rows0 : List Feature := [
  { standard := .ecma376Part2, ref := .clause [6, 2], title := "Parts", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 2, 2], title := "Part names", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 2, 3], title := "Media types", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 2, 4], title := "Growth hint", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 2, 5], title := "XML usage", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 3], title := "Part addressing", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 3, 2], title := "Pack scheme", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 3, 3], title := "Resolving a pack IRI to a resource", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 3, 4], title := "Composing a pack IRI", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 3, 5], title := "Equivalence", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 4], title := "Resolving relative references", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 4, 2], title := "Base IRIs", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 4, 3], title := "Examples", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 5], title := "Relationships", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 5, 2], title := "Relationships part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 5, 3], title := "Relationship markup", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [6, 5, 4], title := "Examples", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 2], title := "Physical mapping guidelines", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 1], title := "Using features of physical formats", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 2], title := "Mapped components", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 3], title := "Mapping media types to parts", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 4], title := "Interleaving", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 2, 5], title := "Mapping part names to physical package item names", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 3], title := "Mapping to a ZIP file", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 2], title := "Mapping part data", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 3], title := "ZIP item names", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 4], title := "Mapping logical item names to ZIP item names", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 5], title := "Mapping ZIP item names to logical item names", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 6], title := "ZIP package limitations", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 7], title := "Mapping the Media Types stream", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [7, 3, 8], title := "Mapping the growth hint", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [8, 2], title := "Core Properties part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [8, 3], title := "Core properties markup", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [8, 3, 2], title := "Support for versioning and extensibility", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [8, 3, 3], title := "coreProperties element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [8, 3, 4], title := "Core property elements", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 3], title := "Choosing content to sign", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 4], title := "Digital signature parts", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 4, 2], title := "Digital Signature Origin part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 4, 3], title := "Digital Signature XML Signature part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 4, 4], title := "Digital Signature Certificate part", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5], title := "Digital signature markup", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 2], title := "Support for versioning and extensibility", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 3], title := "Signature element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 4], title := "SignedInfo element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 5], title := "CanonicalizationMethod element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 6], title := "SignatureMethod element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 7], title := "Reference element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 8], title := "Transform element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 9], title := "RelationshipReference element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 10], title := "RelationshipsGroupReference element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 11], title := "DigestMethod element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 12], title := "Object element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 13], title := "Manifest element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 14], title := "SignatureProperty element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 15], title := "SignatureTime element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 16], title := "Format element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 17], title := "Value element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 5, 18], title := "XPath element", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 6], title := "Relationships transform algorithm", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 7], title := "Digital signature example", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 8], title := "Generating signatures", status := .notImplemented,
    note := "Not read yet." },
  { standard := .ecma376Part2, ref := .clause [10, 9], title := "Validating signatures", status := .notImplemented,
    note := "Not read yet." }
]

/-- Every row of the ECMA-376 Part 2 ledger. -/
def rows : List Feature :=
  rows0

end Ledger.Catalogue.Ecma376Part2
