import Ledger.Feature

/-!
Ledger rows for [MS-DOC]. One row per clause the scope requires, plus any deeper row a note needs.
-/

namespace Ledger.Catalogue.MsDoc

open Ledger

def rows0 : List Feature := [
  { standard := .msDoc, ref := .clause [2, 1], title := "File Structure", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 1], title := "WordDocument Stream", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 3], title := "Data Stream", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 4], title := "ObjectPool Storage", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 5], title := "Custom XML Data Storage", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 6], title := "Summary Information Stream", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 7], title := "Document Summary Information Stream", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 8], title := "Encryption Stream", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 9], title := "Macros Storage", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 10], title := "XML Signatures Storage", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 11], title := "Signatures Stream", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 12], title := "Information Rights Management Data Space Storage", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 1, 13], title := "Protected Content Stream", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 2], title := "Fundamental Concepts", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 2, 1], title := "Character Position (CP)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 2, 2], title := "PLC", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 2, 3], title := "Valid Selection", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 2, 4], title := "STTB", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 2, 5], title := "Property Storage", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 2, 6], title := "Encryption and Obfuscation (Password to Open)", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 3], title := "Document Parts", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 3, 1], title := "Main Document", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 3, 2], title := "Footnotes", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 3, 3], title := "Headers", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 3, 4], title := "Comments", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 3, 5], title := "Endnotes", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 3, 6], title := "Textboxes", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 3, 7], title := "Header Textboxes", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 4], title := "Document Content", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 4, 1], title := "Retrieving Text", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 4, 2], title := "Determining Paragraph Boundaries", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 4, 3], title := "Overview of Tables", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 4, 4], title := "Determining Cell Boundaries", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 4, 5], title := "Determining Row Boundaries", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 4, 6], title := "Applying Properties", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 4, 7], title := "Application Data For VtHyperlink", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5], title := "The File Information Block", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 1], title := "Fib", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 2], title := "FibBase", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 3], title := "FibRgW97", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 4], title := "FibRgLw97", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 5], title := "FibRgFcLcb", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 6], title := "FibRgFcLcb97", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 7], title := "FibRgFcLcb2000", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 8], title := "FibRgFcLcb2002", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 9], title := "FibRgFcLcb2003", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 10], title := "FibRgFcLcb2007", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 11], title := "FibRgCswNew", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 12], title := "FibRgCswNewData2000", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 13], title := "FibRgCswNewData2007", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 14], title := "Determining the nFib", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 5, 15], title := "How to read the FIB", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 6], title := "Single Property Modifiers", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 6, 1], title := "Character Properties", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 6, 2], title := "Paragraph Properties", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 6, 3], title := "Table Properties", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 6, 4], title := "Section Properties", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 6, 5], title := "Picture Properties", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7], title := "Document Properties", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 1], title := "Dop", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 2], title := "DopBase", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 3], title := "Dop95", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 4], title := "Dop97", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 5], title := "Dop2000", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 6], title := "Dop2002", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 7], title := "Dop2003", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 8], title := "Dop2007", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 9], title := "Dop2010", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 10], title := "Dop2013", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 11], title := "Copts60", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 12], title := "Copts80", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 13], title := "Copts", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 14], title := "Asumyi", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 15], title := "Dogrid", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 16], title := "DopTypography", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 7, 17], title := "DopMth", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8], title := "PLCs", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 1], title := "Plcbkf", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 2], title := "Plcbkfd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 3], title := "Plcbkl", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 4], title := "Plcbkld", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 5], title := "PlcBteChpx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 6], title := "PlcBtePapx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 7], title := "PlcfandRef", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 8], title := "PlcfandTxt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 9], title := "PlcfAsumy", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 10], title := "Plcfbkf", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 11], title := "Plcfbkfd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 12], title := "Plcfbkl", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 13], title := "Plcfbkld", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 14], title := "Plcfcookie", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 15], title := "PlcfcookieOld", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 16], title := "PlcfendRef", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 17], title := "PlcfendTxt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 18], title := "Plcffactoid", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 19], title := "PlcffndRef", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 20], title := "PlcffndTxt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 21], title := "Plcfgram", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 22], title := "Plcfhdd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 23], title := "PlcfHdrtxbxTxt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 24], title := "Plcflad", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 25], title := "Plcfld", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 26], title := "PlcfSed", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 27], title := "PlcfSpa", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 28], title := "Plcfspl", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 29], title := "PlcfTch", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 30], title := "PlcfTxbxBkd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 31], title := "PlcfTxbxHdrBkd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 32], title := "PlcftxbxTxt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 33], title := "Plcfuim", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 34], title := "PlcfWKB", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 8, 35], title := "PlcPcd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9], title := "Basic Types", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 1], title := "Acd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 2], title := "Afd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 3], title := "ASUMY", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 4], title := "ATNBE", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 5], title := "AtrdExtra", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 6], title := "ATRDPost10", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 7], title := "ATRDPre10", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 8], title := "BKC", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 9], title := "BKF", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 10], title := "BKFD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 11], title := "BKL", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 12], title := "BKLD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 13], title := "BlockSel", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 14], title := "Bool16", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 15], title := "Bool8", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 16], title := "Brc", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 17], title := "Brc80", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 18], title := "Brc80MayBeNil", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 19], title := "BrcCvOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 20], title := "BrcMayBeNil", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 21], title := "BrcOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 22], title := "BrcType", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 23], title := "BxPap", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 24], title := "CAPI", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 25], title := "CDB", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 26], title := "CellHideMarkOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 27], title := "CellRangeFitText", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 28], title := "CellRangeNoWrap", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 29], title := "CellRangeTextFlow", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 30], title := "CellRangeVertAlign", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 31], title := "CFitTextOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 32], title := "Chpx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 33], title := "ChpxFkp", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 34], title := "Cid", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 35], title := "CidAllocated", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 36], title := "CidFci", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 37], title := "CidMacro", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 38], title := "Clx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 39], title := "CMajorityOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 40], title := "Cmt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 41], title := "CNFOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 42], title := "CNS", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 43], title := "COLORREF", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 44], title := "COSL", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 45], title := "CSSA", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 46], title := "CSSAOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 47], title := "CSymbolOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 48], title := "CTB", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 49], title := "CTBWRAPPER", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 50], title := "Customization", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 51], title := "DCS", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 52], title := "DefTableShd80Operand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 53], title := "DefTableShdOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 54], title := "DispFldRmOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 55], title := "Dofr", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 56], title := "DofrFsn", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 57], title := "DofrFsnFnm", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 58], title := "DofrFsnName", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 59], title := "DofrFsnp", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 60], title := "DofrFsnSpbd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 61], title := "Dofrh", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 62], title := "DofrRglstsf", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 63], title := "Dofrt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 64], title := "DPCID", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 65], title := "DTTM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 66], title := "FACTOIDINFO", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 67], title := "FactoidSpls", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 68], title := "FarEastLayoutOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 69], title := "Fatl", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 70], title := "FBKF", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 71], title := "FBKFD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 72], title := "FBKLD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 73], title := "FcCompressed", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 74], title := "FCCT", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 75], title := "Fci", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 76], title := "FCKS", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 77], title := "FCKSOLD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 78], title := "FFData", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 79], title := "FFDataBits", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 80], title := "FFID", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 81], title := "FFM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 82], title := "FFN", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 83], title := "FieldMapBase", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 84], title := "FieldMapDataItem", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 85], title := "FieldMapInfo", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 86], title := "FieldMapTerminator", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 87], title := "FilterDataItem", status := .notImplemented,
    note := "Not read yet." }
]

def rows1 : List Feature := [
  { standard := .msDoc, ref := .clause [2, 9, 88], title := "Fld", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 89], title := "fldch", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 90], title := "flt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 91], title := "FNFB", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 92], title := "FNIF", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 93], title := "FNPI", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 94], title := "FOBJH", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 95], title := "FrameTextFlowOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 96], title := "FSDAP", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 97], title := "Fsnk", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 98], title := "Fssd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 99], title := "FssUnits", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 100], title := "FTO", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 101], title := "Fts", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 102], title := "FtsWWidth_Indent", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 103], title := "FtsWWidth_Table", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 104], title := "FtsWWidth_TablePart", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 105], title := "FTXBXNonReusable", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 106], title := "FTXBXS", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 107], title := "FTXBXSReusable", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 108], title := "GOSL", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 109], title := "GrammarSpls", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 110], title := "grffldEnd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 111], title := "grfhic", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 112], title := "GRFSTD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 113], title := "GrLPUpxSw", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 114], title := "GrpPrlAndIstd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 115], title := "HFD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 116], title := "HFDBits", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 117], title := "Hplxsdr", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 118], title := "HresiOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 119], title := "Ico", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 120], title := "IDPCI", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 121], title := "Ipat", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 122], title := "IScrollType", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 123], title := "ItcFirstLim", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 124], title := "Kcm", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 125], title := "Kme", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 126], title := "Kt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 127], title := "Kul", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 128], title := "LadSpls", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 129], title := "LBCOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 130], title := "LEGOXTR_V11", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 131], title := "LFO", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 132], title := "LFOData", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 133], title := "LFOLVL", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 134], title := "LID", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 135], title := "LPStd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 136], title := "LPStshi", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 137], title := "LPStshiGrpPrl", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 138], title := "LPUpxChpx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 139], title := "LPUpxChpxRM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 140], title := "LPUpxPapx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 141], title := "LPUpxPapxRM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 142], title := "LPUpxRm", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 143], title := "LPUpxTapx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 144], title := "LPXCharBuffer9", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 145], title := "LSD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 146], title := "LSPD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 147], title := "LSTF", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 148], title := "Lstsf", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 149], title := "LVL", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 150], title := "LVLF", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 151], title := "MacroName", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 152], title := "MacroNames", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 153], title := "MathPrOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 154], title := "Mcd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 155], title := "MDP", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 156], title := "MFPF", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 157], title := "NilBrc", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 158], title := "NilPICFAndBinData", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 159], title := "NumRM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 160], title := "NumRMOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 161], title := "OcxInfo", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 162], title := "ODSOPropertyBase", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 163], title := "ODSOPropertyLarge", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 164], title := "ODSOPropertyStandard", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 165], title := "ODT", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 166], title := "ODTPersist1", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 167], title := "ODTPersist2", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 168], title := "OfficeArtClientAnchor", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 169], title := "OfficeArtClientData", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 170], title := "OfficeArtClientTextbox", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 171], title := "OfficeArtContent", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 172], title := "OfficeArtWordDrawing", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 173], title := "PANOSE", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 174], title := "PapxFkp", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 175], title := "PapxInFkp", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 176], title := "PbiGrfOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 177], title := "Pcd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 178], title := "Pcdt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 179], title := "PChgTabsAdd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 180], title := "PChgTabsDel", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 181], title := "PChgTabsDelClose", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 182], title := "PChgTabsOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 183], title := "PChgTabsPapxOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 184], title := "PgbApplyTo", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 185], title := "PgbOffsetFrom", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 186], title := "PgbPageDepth", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 187], title := "PGPArray", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 188], title := "PGPInfo", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 189], title := "PGPOptions", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 190], title := "PICF", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 191], title := "PICF_Shape", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 192], title := "PICFAndOfficeArtData", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 193], title := "PICMID", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 194], title := "PlcfGlsy", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 195], title := "PlfAcd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 196], title := "PlfCosl", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 197], title := "PlfGosl", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 198], title := "PlfguidUim", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 199], title := "PlfKme", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 200], title := "PlfLfo", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 201], title := "PlfLst", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 202], title := "PlfMcd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 203], title := "PLRSID", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 204], title := "Pmfs", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 205], title := "Pms", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 206], title := "PnFkpChpx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 207], title := "PnFkpPapx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 208], title := "PositionCodeOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 209], title := "Prc", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 210], title := "PrcData", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 211], title := "PrDrvr", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 212], title := "PrEnvLand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 213], title := "PrEnvPort", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 214], title := "Prm", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 215], title := "Prm0", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 216], title := "Prm1", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 217], title := "PropRMark", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 218], title := "PropRMarkOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 219], title := "ProtectionType", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 220], title := "PRTI", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 221], title := "PTIstdInfoOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 222], title := "Rca", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 223], title := "RecipientBase", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 224], title := "RecipientDataItem", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 225], title := "RecipientInfo", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 226], title := "RecipientTerminator", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 227], title := "Rfs", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 228], title := "RgCdb", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 229], title := "RgxOcxInfo", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 230], title := "RmdThreading", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 231], title := "Rnc", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 232], title := "RouteSlip", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 233], title := "RouteSlipInfo", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 234], title := "RouteSlipProtectionEnum", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 235], title := "SBkcOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 236], title := "SBOrientationOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 237], title := "SClmOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 238], title := "SDmBinOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 239], title := "SDTI", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 240], title := "SDTT", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 241], title := "SDxaColSpacingOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 242], title := "SDxaColWidthOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 243], title := "Sed", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 244], title := "Selsf", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 245], title := "Sepx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 246], title := "SFpcOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 247], title := "Shd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 248], title := "Shd80", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 249], title := "SHDOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 250], title := "SLncOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 251], title := "SmartTagData", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 252], title := "SortColumnAndDirection", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 253], title := "Spa", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 254], title := "SpellingSpls", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 255], title := "SPgbPropOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 256], title := "SPLS", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 257], title := "SPPOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 258], title := "STD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 259], title := "Stdf", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 260], title := "StdfBase", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 261], title := "StdfPost2000", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 262], title := "StdfPost2000OrNone", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 263], title := "StkCharGRLPUPX", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 264], title := "StkCharLPUpxGrLPUpxRM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 265], title := "StkCharUpxGrLPUpxRM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 266], title := "StkListGRLPUPX", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 267], title := "StkParaGRLPUPX", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 268], title := "StkParaLPUpxGrLPUpxRM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 269], title := "StkParaUpxGrLPUpxRM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 270], title := "StkTableGRLPUPX", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 271], title := "STSH", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 272], title := "STSHI", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 273], title := "STSHIB", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 274], title := "Stshif", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 275], title := "StshiLsd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 276], title := "SttbfAssoc", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 277], title := "SttbfAtnBkmk", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 278], title := "SttbfAutoCaption", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 279], title := "SttbfBkmk", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 280], title := "SttbfBkmkBPRepairs", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 281], title := "SttbfBkmkFactoid", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 282], title := "SttbfBkmkFcc", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 283], title := "SttbfBkmkProt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 284], title := "SttbfBkmkSdt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 285], title := "SttbfCaption", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 286], title := "SttbfFfn", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 287], title := "SttbfGlsy", status := .notImplemented,
    note := "Not read yet." }
]

def rows2 : List Feature := [
  { standard := .msDoc, ref := .clause [2, 9, 288], title := "SttbFnm", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 289], title := "SttbfRfs", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 290], title := "SttbfRMark", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 291], title := "SttbGlsyStyle", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 292], title := "SttbListNames", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 293], title := "SttbProtUser", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 294], title := "SttbRgtplc", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 295], title := "SttbSavedBy", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 296], title := "SttbTtmbd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 297], title := "SttbW6", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 298], title := "StwUser", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 299], title := "Sty", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 300], title := "TabJC", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 301], title := "TabLC", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 302], title := "TableBordersOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 303], title := "TableBordersOperand80", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 304], title := "TableBrc80Operand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 305], title := "TableBrcOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 306], title := "TableCellWidthOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 307], title := "TableSel", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 308], title := "TableShadeOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 309], title := "TBC", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 310], title := "TBD", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 311], title := "TBDelta", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 312], title := "Tbkd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 313], title := "TC80", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 314], title := "TCellBrcTypeOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 315], title := "Tcg", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 316], title := "Tcg255", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 317], title := "TCGRF", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 318], title := "TcgSttbf", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 319], title := "TcgSttbfCore", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 320], title := "Tch", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 321], title := "TDefTableOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 322], title := "TDxaColOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 323], title := "TextFlow", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 324], title := "TInsertOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 325], title := "TIQ", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 326], title := "TLP", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 327], title := "ToggleOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 328], title := "Tplc", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 329], title := "TplcBuildIn", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 330], title := "TplcUser", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 331], title := "Ttmbd", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 332], title := "UFEL", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 333], title := "UID", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 334], title := "UidSel", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 335], title := "UIM", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 336], title := "UpxChpx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 337], title := "UPXPadding", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 338], title := "UpxPapx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 339], title := "UpxRm", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 340], title := "UpxTapx", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 341], title := "VerticalAlign", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 342], title := "VerticalMergeFlag", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 343], title := "VertMergeOperand", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 344], title := "Vjc", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 345], title := "WHeightAbs", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 346], title := "WKB", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 347], title := "Wpms", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 348], title := "Wpmsdt", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 349], title := "XAS", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 350], title := "XAS_nonNeg", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 351], title := "XAS_plusOne", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 352], title := "XSDR", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 353], title := "Xst", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 354], title := "Xstz", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 355], title := "YAS", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 356], title := "YAS_nonNeg", status := .notImplemented,
    note := "Not read yet." },
  { standard := .msDoc, ref := .clause [2, 9, 357], title := "YAS_plusOne", status := .notImplemented,
    note := "Not read yet." }
]

/-- Every row of the [MS-DOC] ledger. -/
def rows : List Feature :=
  rows0 ++ rows1 ++ rows2

end Ledger.Catalogue.MsDoc
