import Ledger.Feature

/-!
Citations of the tracked specifications in the docboss source tree, written by
`lake exe ledger-index`. Regenerate rather than edit.
-/

namespace Ledger

def Generated.citations0 : List Citation := [
  ⟨.msCfb, some (.clause [2, 6, 1]), "crates/docboss-cfb/src/directory.rs", 3, false⟩,
  ⟨.msCfb, some (.clause [2, 6, 1]), "crates/docboss-cfb/src/directory.rs", 12, false⟩,
  ⟨.msCfb, none, "crates/docboss-cfb/src/lib.rs", 1, false⟩,
  ⟨.msOleps, none, "crates/docboss-cfb/src/lib.rs", 2, false⟩,
  ⟨.msCfb, some (.clause [2, 2]), "crates/docboss-cfb/src/lib.rs", 29, false⟩,
  ⟨.msCfb, some (.clause [2, 2]), "crates/docboss-cfb/src/lib.rs", 72, false⟩,
  ⟨.msCfb, some (.clause [2, 1]), "crates/docboss-cfb/src/lib.rs", 73, false⟩,
  ⟨.msCfb, some (.clause [2, 2]), "crates/docboss-cfb/src/lib.rs", 73, false⟩,
  ⟨.msCfb, some (.clause [2, 3]), "crates/docboss-cfb/src/lib.rs", 73, false⟩,
  ⟨.msCfb, some (.clause [2, 4]), "crates/docboss-cfb/src/lib.rs", 73, false⟩,
  ⟨.msCfb, some (.clause [2, 5]), "crates/docboss-cfb/src/lib.rs", 73, false⟩,
  ⟨.msCfb, some (.clause [2, 6, 2]), "crates/docboss-cfb/src/lib.rs", 73, false⟩,
  ⟨.msCfb, some (.clause [2, 6, 3]), "crates/docboss-cfb/src/lib.rs", 73, false⟩,
  ⟨.msCfb, some (.clause [2, 6]), "crates/docboss-cfb/src/lib.rs", 73, false⟩,
  ⟨.msCfb, some (.clause [2, 5]), "crates/docboss-cfb/src/lib.rs", 192, false⟩,
  ⟨.msCfb, some (.clause [2, 4]), "crates/docboss-cfb/src/lib.rs", 332, false⟩,
  ⟨.msCfb, some (.clause [2, 6, 4]), "crates/docboss-cfb/src/lib.rs", 381, false⟩,
  ⟨.msCfb, some (.clause [2, 6, 4]), "crates/docboss-cfb/src/lib.rs", 410, false⟩,
  ⟨.msOleps, none, "crates/docboss-cfb/src/property.rs", 1, false⟩,
  ⟨.msOleps, some (.clause [2, 15]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 18, 2]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 19]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 1]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 20]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 21]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 23]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 25, 1]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 2]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 5]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 7]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 8]), "crates/docboss-cfb/src/property.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 15]), "crates/docboss-cfb/src/property.rs", 20, false⟩,
  ⟨.msOleps, some (.clause [2, 21]), "crates/docboss-cfb/src/property.rs", 73, false⟩,
  ⟨.msOleps, some (.clause [2, 20]), "crates/docboss-cfb/src/property.rs", 99, false⟩,
  ⟨.msOleps, some (.clause [2, 15]), "crates/docboss-cfb/src/property.rs", 146, false⟩,
  ⟨.msOleps, some (.clause [2, 15]), "crates/docboss-cfb/src/time.rs", 3, false⟩,
  ⟨.msOleps, some (.clause [2, 8]), "crates/docboss-cfb/src/time.rs", 40, true⟩,
  ⟨.msCfb, some (.clause [2, 2]), "crates/docboss-cfb/tests/cfb.rs", 5, true⟩,
  ⟨.msCfb, some (.clause [2, 1]), "crates/docboss-cfb/tests/cfb.rs", 7, true⟩,
  ⟨.msCfb, some (.clause [2, 2]), "crates/docboss-cfb/tests/cfb.rs", 7, true⟩,
  ⟨.msCfb, some (.clause [2, 3]), "crates/docboss-cfb/tests/cfb.rs", 7, true⟩,
  ⟨.msCfb, some (.clause [2, 4]), "crates/docboss-cfb/tests/cfb.rs", 7, true⟩,
  ⟨.msCfb, some (.clause [2, 5]), "crates/docboss-cfb/tests/cfb.rs", 7, true⟩,
  ⟨.msCfb, some (.clause [2, 6, 1]), "crates/docboss-cfb/tests/cfb.rs", 7, true⟩,
  ⟨.msCfb, some (.clause [2, 6, 2]), "crates/docboss-cfb/tests/cfb.rs", 7, true⟩,
  ⟨.msCfb, some (.clause [2, 6, 3]), "crates/docboss-cfb/tests/cfb.rs", 7, true⟩,
  ⟨.msCfb, some (.clause [2, 6]), "crates/docboss-cfb/tests/cfb.rs", 7, true⟩,
  ⟨.msCfb, some (.clause [2, 6, 4]), "crates/docboss-cfb/tests/cfb.rs", 31, true⟩,
  ⟨.msOleps, some (.clause [2, 21]), "crates/docboss-cfb/tests/cfb.rs", 42, true⟩,
  ⟨.msOleps, some (.clause [2, 15]), "crates/docboss-cfb/tests/cfb.rs", 43, true⟩,
  ⟨.msOleps, some (.clause [2, 18, 2]), "crates/docboss-cfb/tests/cfb.rs", 43, true⟩,
  ⟨.msOleps, some (.clause [2, 19]), "crates/docboss-cfb/tests/cfb.rs", 43, true⟩,
  ⟨.msOleps, some (.clause [2, 1]), "crates/docboss-cfb/tests/cfb.rs", 43, true⟩,
  ⟨.msOleps, some (.clause [2, 20]), "crates/docboss-cfb/tests/cfb.rs", 43, true⟩,
  ⟨.msOleps, some (.clause [2, 23]), "crates/docboss-cfb/tests/cfb.rs", 43, true⟩,
  ⟨.msOleps, some (.clause [2, 25, 1]), "crates/docboss-cfb/tests/cfb.rs", 43, true⟩,
  ⟨.msOleps, some (.clause [2, 2]), "crates/docboss-cfb/tests/cfb.rs", 43, true⟩,
  ⟨.msOleps, some (.clause [2, 5]), "crates/docboss-cfb/tests/cfb.rs", 43, true⟩,
  ⟨.msCfb, some (.clause [2, 3]), "crates/docboss-cfb/tests/cfb.rs", 81, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 2]), "crates/docboss-doc/src/bytes.rs", 37, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 6]), "crates/docboss-doc/src/crypt.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 3]), "crates/docboss-doc/src/document.rs", 20, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 1]), "crates/docboss-doc/src/document.rs", 22, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 1]), "crates/docboss-doc/src/document.rs", 22, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 2]), "crates/docboss-doc/src/document.rs", 22, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 3]), "crates/docboss-doc/src/document.rs", 22, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 4]), "crates/docboss-doc/src/document.rs", 22, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 5]), "crates/docboss-doc/src/document.rs", 22, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 6]), "crates/docboss-doc/src/document.rs", 22, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 7]), "crates/docboss-doc/src/document.rs", 22, false⟩,
  ⟨.msDoc, some (.clause [2, 1, 1]), "crates/docboss-doc/src/document.rs", 65, false⟩,
  ⟨.msDoc, some (.clause [2, 1, 3]), "crates/docboss-doc/src/document.rs", 65, false⟩,
  ⟨.msDoc, some (.clause [2, 1, 6]), "crates/docboss-doc/src/document.rs", 65, false⟩,
  ⟨.msDoc, some (.clause [2, 1, 7]), "crates/docboss-doc/src/document.rs", 65, false⟩,
  ⟨.msDoc, some (.clause [2, 1]), "crates/docboss-doc/src/document.rs", 65, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 6, 2]), "crates/docboss-doc/src/document.rs", 106, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 6, 3]), "crates/docboss-doc/src/document.rs", 106, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 19]), "crates/docboss-doc/src/document.rs", 245, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 2]), "crates/docboss-doc/src/document.rs", 248, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 5]), "crates/docboss-doc/src/document.rs", 248, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 16]), "crates/docboss-doc/src/document.rs", 248, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 17]), "crates/docboss-doc/src/document.rs", 248, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 19]), "crates/docboss-doc/src/document.rs", 248, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 20]), "crates/docboss-doc/src/document.rs", 248, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 7]), "crates/docboss-doc/src/document.rs", 276, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 4]), "crates/docboss-doc/src/document.rs", 278, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 1]), "crates/docboss-doc/src/document.rs", 278, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 3]), "crates/docboss-doc/src/document.rs", 278, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 7]), "crates/docboss-doc/src/document.rs", 278, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 8]), "crates/docboss-doc/src/document.rs", 278, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 277]), "crates/docboss-doc/src/document.rs", 278, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 7]), "crates/docboss-doc/src/document.rs", 278, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 10]), "crates/docboss-doc/src/document.rs", 346, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 10]), "crates/docboss-doc/src/document.rs", 347, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 12]), "crates/docboss-doc/src/document.rs", 347, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 11]), "crates/docboss-doc/src/document.rs", 347, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 279]), "crates/docboss-doc/src/document.rs", 347, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 9]), "crates/docboss-doc/src/document.rs", 347, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 27]), "crates/docboss-doc/src/document.rs", 370, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 171]), "crates/docboss-doc/src/document.rs", 371, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 27]), "crates/docboss-doc/src/document.rs", 374, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 171]), "crates/docboss-doc/src/document.rs", 374, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 172]), "crates/docboss-doc/src/document.rs", 374, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 253]), "crates/docboss-doc/src/document.rs", 374, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 23]), "crates/docboss-doc/src/document.rs", 406, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 32]), "crates/docboss-doc/src/document.rs", 406, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 26]), "crates/docboss-doc/src/document.rs", 485, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 22]), "crates/docboss-doc/src/document.rs", 486, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 22]), "crates/docboss-doc/src/document.rs", 487, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 26]), "crates/docboss-doc/src/document.rs", 487, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 243]), "crates/docboss-doc/src/document.rs", 487, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 245]), "crates/docboss-doc/src/document.rs", 487, false⟩,
  ⟨.msDoc, some (.clause [2, 5]), "crates/docboss-doc/src/fib.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 15]), "crates/docboss-doc/src/fib.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 1]), "crates/docboss-doc/src/fib.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 2]), "crates/docboss-doc/src/fib.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 4]), "crates/docboss-doc/src/fib.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 5]), "crates/docboss-doc/src/fib.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 6]), "crates/docboss-doc/src/fib.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 6]), "crates/docboss-doc/src/fib.rs", 9, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 4]), "crates/docboss-doc/src/fib.rs", 39, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 15]), "crates/docboss-doc/src/fib.rs", 71, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 14]), "crates/docboss-doc/src/fib.rs", 123, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 33]), "crates/docboss-doc/src/fkp.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 5]), "crates/docboss-doc/src/fkp.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 6]), "crates/docboss-doc/src/fkp.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 5]), "crates/docboss-doc/src/fkp.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 6]), "crates/docboss-doc/src/fkp.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 174]), "crates/docboss-doc/src/fkp.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 206]), "crates/docboss-doc/src/fkp.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 207]), "crates/docboss-doc/src/fkp.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 33]), "crates/docboss-doc/src/fkp.rs", 3, false⟩,
  ⟨.msDoc, none, "crates/docboss-doc/src/lib.rs", 1, false⟩,
  ⟨.msCfb, none, "crates/docboss-doc/src/lib.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 201]), "crates/docboss-doc/src/lists.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 131]), "crates/docboss-doc/src/lists.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 147]), "crates/docboss-doc/src/lists.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 149]), "crates/docboss-doc/src/lists.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 150]), "crates/docboss-doc/src/lists.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 200]), "crates/docboss-doc/src/lists.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 201]), "crates/docboss-doc/src/lists.rs", 3, false⟩,
  ⟨.msOshared, some (.clause [2, 2, 1, 3]), "crates/docboss-doc/src/lists.rs", 17, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 149]), "crates/docboss-doc/src/lists.rs", 48, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 190]), "crates/docboss-doc/src/picture.rs", 1, false⟩,
  ⟨.msOdraw, some (.clause [2, 2, 23]), "crates/docboss-doc/src/picture.rs", 2, false⟩,
  ⟨.msOdraw, some (.clause [2, 2, 1]), "crates/docboss-doc/src/picture.rs", 12, false⟩,
  ⟨.msOdraw, some (.clause [2, 2, 23]), "crates/docboss-doc/src/picture.rs", 59, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 192]), "crates/docboss-doc/src/picture.rs", 170, false⟩,
  ⟨.msOdraw, some (.clause [2, 3, 23, 1]), "crates/docboss-doc/src/picture.rs", 199, false⟩,
  ⟨.msOdraw, some (.clause [2, 2, 40]), "crates/docboss-doc/src/picture.rs", 212, false⟩,
  ⟨.msDoc, some (.clause [2, 6]), "crates/docboss-doc/src/props.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 119]), "crates/docboss-doc/src/props.rs", 12, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 43]), "crates/docboss-doc/src/props.rs", 41, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 65]), "crates/docboss-doc/src/props.rs", 49, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 17]), "crates/docboss-doc/src/props.rs", 118, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 16]), "crates/docboss-doc/src/props.rs", 132, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 247]), "crates/docboss-doc/src/props.rs", 148, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 248]), "crates/docboss-doc/src/props.rs", 160, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 1]), "crates/docboss-doc/src/props.rs", 212, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 2]), "crates/docboss-doc/src/props.rs", 391, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 146]), "crates/docboss-doc/src/props.rs", 427, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 4]), "crates/docboss-doc/src/props.rs", 485, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 4]), "crates/docboss-doc/src/props.rs", 495, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 65]), "crates/docboss-doc/src/props.rs", 577, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 43]), "crates/docboss-doc/src/props.rs", 586, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 146]), "crates/docboss-doc/src/props.rs", 593, true⟩,
  ⟨.msDoc, some (.clause [2, 6, 1]), "crates/docboss-doc/src/props.rs", 610, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 5]), "crates/docboss-doc/src/sprm.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 5, 1]), "crates/docboss-doc/src/sprm.rs", 15, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 5, 1]), "crates/docboss-doc/src/sprm.rs", 46, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 5, 1]), "crates/docboss-doc/src/sprm.rs", 87, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 2]), "crates/docboss-doc/src/story.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 6]), "crates/docboss-doc/src/story.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 3]), "crates/docboss-doc/src/story.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 2]), "crates/docboss-doc/src/story.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 3]), "crates/docboss-doc/src/story.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 4]), "crates/docboss-doc/src/story.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 5]), "crates/docboss-doc/src/story.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 6]), "crates/docboss-doc/src/story.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 88]), "crates/docboss-doc/src/story.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 89]), "crates/docboss-doc/src/story.rs", 4, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 253]), "crates/docboss-doc/src/story.rs", 31, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 90]), "crates/docboss-doc/src/story.rs", 215, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 6]), "crates/docboss-doc/src/story.rs", 511, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 32]), "crates/docboss-doc/src/story.rs", 511, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 4]), "crates/docboss-doc/src/sttb.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 82]), "crates/docboss-doc/src/sttb.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 4]), "crates/docboss-doc/src/sttb.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 286]), "crates/docboss-doc/src/sttb.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 353]), "crates/docboss-doc/src/sttb.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 82]), "crates/docboss-doc/src/sttb.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 82]), "crates/docboss-doc/src/sttb.rs", 85, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 353]), "crates/docboss-doc/src/sttb.rs", 115, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 271]), "crates/docboss-doc/src/styles.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 258]), "crates/docboss-doc/src/styles.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 259]), "crates/docboss-doc/src/styles.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 260]), "crates/docboss-doc/src/styles.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 271]), "crates/docboss-doc/src/styles.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 272]), "crates/docboss-doc/src/styles.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 336]), "crates/docboss-doc/src/styles.rs", 2, false⟩
]

def Generated.citations1 : List Citation := [
  ⟨.msDoc, some (.clause [2, 9, 338]), "crates/docboss-doc/src/styles.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 258]), "crates/docboss-doc/src/styles.rs", 45, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 271]), "crates/docboss-doc/src/styles.rs", 45, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 3]), "crates/docboss-doc/src/table.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 3]), "crates/docboss-doc/src/table.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 3]), "crates/docboss-doc/src/table.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 313]), "crates/docboss-doc/src/table.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 317]), "crates/docboss-doc/src/table.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 321]), "crates/docboss-doc/src/table.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 313]), "crates/docboss-doc/src/table.rs", 14, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 38]), "crates/docboss-doc/src/text.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 1]), "crates/docboss-doc/src/text.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 1]), "crates/docboss-doc/src/text.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 35]), "crates/docboss-doc/src/text.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 177]), "crates/docboss-doc/src/text.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 178]), "crates/docboss-doc/src/text.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 209]), "crates/docboss-doc/src/text.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 38]), "crates/docboss-doc/src/text.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 215]), "crates/docboss-doc/src/text.rs", 45, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 38]), "crates/docboss-doc/src/text.rs", 81, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 214]), "crates/docboss-doc/src/text.rs", 153, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 73]), "crates/docboss-doc/src/text.rs", 195, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 73]), "crates/docboss-doc/src/text.rs", 205, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 1]), "crates/docboss-doc/tests/read.rs", 50, true⟩,
  ⟨.msDoc, some (.clause [2, 1, 1]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 1]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 2]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 1]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 1]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 2]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 5, 14]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 5, 15]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 5, 1]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 5, 2]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 5, 4]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 5, 5]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 5, 6]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 35]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 177]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 178]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 214]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 38]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 73]), "crates/docboss-doc/tests/read.rs", 52, true⟩,
  ⟨.msDoc, some (.clause [2, 5, 1]), "crates/docboss-doc/tests/read.rs", 60, true⟩,
  ⟨.msOleps, some (.clause [2, 21]), "crates/docboss-doc/tests/read.rs", 60, true⟩,
  ⟨.msDoc, some (.clause [2, 1, 6]), "crates/docboss-doc/tests/read.rs", 61, true⟩,
  ⟨.msOleps, some (.clause [2, 15]), "crates/docboss-doc/tests/read.rs", 61, true⟩,
  ⟨.msOleps, some (.clause [2, 20]), "crates/docboss-doc/tests/read.rs", 61, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 6, 2]), "crates/docboss-doc/tests/read.rs", 75, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 5]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 6]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 6, 1]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 6, 2]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 5]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 6]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 174]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 206]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 207]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 258]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 259]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 260]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 271]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 272]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 336]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 338]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 33]), "crates/docboss-doc/tests/read.rs", 77, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 6, 3]), "crates/docboss-doc/tests/read.rs", 128, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 131]), "crates/docboss-doc/tests/read.rs", 130, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 147]), "crates/docboss-doc/tests/read.rs", 130, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 149]), "crates/docboss-doc/tests/read.rs", 130, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 150]), "crates/docboss-doc/tests/read.rs", 130, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 200]), "crates/docboss-doc/tests/read.rs", 130, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 201]), "crates/docboss-doc/tests/read.rs", 130, true⟩,
  ⟨.msOshared, some (.clause [2, 2, 1, 3]), "crates/docboss-doc/tests/read.rs", 130, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 3]), "crates/docboss-doc/tests/read.rs", 142, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 3]), "crates/docboss-doc/tests/read.rs", 145, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 4]), "crates/docboss-doc/tests/read.rs", 145, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 5]), "crates/docboss-doc/tests/read.rs", 145, true⟩,
  ⟨.msDoc, some (.clause [2, 6, 3]), "crates/docboss-doc/tests/read.rs", 145, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 313]), "crates/docboss-doc/tests/read.rs", 145, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 317]), "crates/docboss-doc/tests/read.rs", 145, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 321]), "crates/docboss-doc/tests/read.rs", 145, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 2]), "crates/docboss-doc/tests/read.rs", 173, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 4]), "crates/docboss-doc/tests/read.rs", 173, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 5]), "crates/docboss-doc/tests/read.rs", 173, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 2]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 4]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 5]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 10]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 12]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 16]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 17]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 19]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 20]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 7]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 8]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 11]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 277]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 279]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 353]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 7]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 88]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 89]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 90]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 9]), "crates/docboss-doc/tests/read.rs", 176, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 192]), "crates/docboss-doc/tests/read.rs", 221, true⟩,
  ⟨.msOdraw, some (.clause [2, 2, 24]), "crates/docboss-doc/tests/read.rs", 221, true⟩,
  ⟨.msDoc, some (.clause [2, 1, 3]), "crates/docboss-doc/tests/read.rs", 223, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 190]), "crates/docboss-doc/tests/read.rs", 223, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 192]), "crates/docboss-doc/tests/read.rs", 223, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 26]), "crates/docboss-doc/tests/read.rs", 243, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 3]), "crates/docboss-doc/tests/read.rs", 244, true⟩,
  ⟨.msDoc, some (.clause [2, 6, 4]), "crates/docboss-doc/tests/read.rs", 244, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 22]), "crates/docboss-doc/tests/read.rs", 244, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 26]), "crates/docboss-doc/tests/read.rs", 244, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 243]), "crates/docboss-doc/tests/read.rs", 244, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 245]), "crates/docboss-doc/tests/read.rs", 244, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 6, 2]), "crates/docboss-doc/tests/read.rs", 288, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 27]), "crates/docboss-doc/tests/read.rs", 315, true⟩,
  ⟨.msOdraw, some (.clause [2, 2, 32]), "crates/docboss-doc/tests/read.rs", 315, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 32]), "crates/docboss-doc/tests/read.rs", 316, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 6]), "crates/docboss-doc/tests/read.rs", 317, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 27]), "crates/docboss-doc/tests/read.rs", 317, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 32]), "crates/docboss-doc/tests/read.rs", 317, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 171]), "crates/docboss-doc/tests/read.rs", 317, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 172]), "crates/docboss-doc/tests/read.rs", 317, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 253]), "crates/docboss-doc/tests/read.rs", 317, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 4]), "crates/docboss-doc/tests/read.rs", 354, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 286]), "crates/docboss-doc/tests/read.rs", 354, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 82]), "crates/docboss-doc/tests/read.rs", 354, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 10]), "crates/docboss-docx/src/lib.rs", 67, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2, 2]), "crates/docboss-docx/src/lib.rs", 143, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2, 3]), "crates/docboss-docx/src/lib.rs", 143, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 6]), "crates/docboss-docx/src/lib.rs", 154, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 9]), "crates/docboss-docx/src/lib.rs", 154, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 3]), "crates/docboss-docx/src/lib.rs", 154, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 4]), "crates/docboss-docx/src/lib.rs", 154, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 4]), "crates/docboss-docx/src/lib.rs", 163, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 7]), "crates/docboss-docx/src/lib.rs", 163, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 10]), "crates/docboss-docx/src/lib.rs", 163, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 15]), "crates/docboss-docx/src/lib.rs", 163, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 1]), "crates/docboss-docx/src/lib.rs", 163, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 23]), "crates/docboss-docx/src/lib.rs", 163, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 2]), "crates/docboss-docx/src/lib.rs", 163, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 8]), "crates/docboss-docx/src/lib.rs", 163, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 2]), "crates/docboss-docx/src/lib.rs", 183, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 4]), "crates/docboss-docx/src/lib.rs", 183, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 11]), "crates/docboss-docx/src/lib.rs", 258, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 12]), "crates/docboss-docx/src/lib.rs", 258, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 3]), "crates/docboss-docx/src/lib.rs", 258, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 5]), "crates/docboss-docx/src/lib.rs", 258, false⟩,
  ⟨.ecma376Part1, some (.clause [15, 2, 14]), "crates/docboss-docx/src/lib.rs", 297, false⟩,
  ⟨.ecma376Part2, none, "crates/docboss-docx/src/package.rs", 1, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 5, 3, 4]), "crates/docboss-docx/src/package.rs", 10, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 4, 2]), "crates/docboss-docx/src/package.rs", 61, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 4]), "crates/docboss-docx/src/package.rs", 61, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 4]), "crates/docboss-docx/src/package.rs", 62, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 5, 2]), "crates/docboss-docx/src/package.rs", 122, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 2, 3, 2]), "crates/docboss-docx/src/package.rs", 174, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 7]), "crates/docboss-docx/src/package.rs", 174, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 2, 3]), "crates/docboss-docx/src/package.rs", 218, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 2, 3, 5]), "crates/docboss-docx/src/package.rs", 218, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 5, 2]), "crates/docboss-docx/src/package.rs", 242, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 5, 3]), "crates/docboss-docx/src/package.rs", 242, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 2, 2, 3]), "crates/docboss-docx/src/package.rs", 284, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 5]), "crates/docboss-docx/src/package.rs", 284, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 2, 5]), "crates/docboss-docx/src/package.rs", 285, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 2]), "crates/docboss-docx/src/package.rs", 285, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 3]), "crates/docboss-docx/src/package.rs", 285, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 4, 2]), "crates/docboss-docx/src/package.rs", 297, true⟩,
  ⟨.ecma376Part2, some (.clause [6, 4, 3]), "crates/docboss-docx/src/package.rs", 297, true⟩,
  ⟨.ecma376Part2, some (.clause [6, 5, 2]), "crates/docboss-docx/src/package.rs", 324, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7]), "crates/docboss-docx/src/parts.rs", 16, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 4]), "crates/docboss-docx/src/parts.rs", 18, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 5]), "crates/docboss-docx/src/parts.rs", 18, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 6]), "crates/docboss-docx/src/parts.rs", 18, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 7]), "crates/docboss-docx/src/parts.rs", 18, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 8]), "crates/docboss-docx/src/parts.rs", 18, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 9]), "crates/docboss-docx/src/parts.rs", 18, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 18, 59]), "crates/docboss-docx/src/parts.rs", 71, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 6]), "crates/docboss-docx/src/parts.rs", 104, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 10]), "crates/docboss-docx/src/parts.rs", 107, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 11]), "crates/docboss-docx/src/parts.rs", 107, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 17]), "crates/docboss-docx/src/parts.rs", 107, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 22]), "crates/docboss-docx/src/parts.rs", 107, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 24]), "crates/docboss-docx/src/parts.rs", 107, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 25]), "crates/docboss-docx/src/parts.rs", 107, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 4]), "crates/docboss-docx/src/parts.rs", 107, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 7]), "crates/docboss-docx/src/parts.rs", 107, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-docx/src/parts.rs", 139, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 15]), "crates/docboss-docx/src/parts.rs", 142, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 16]), "crates/docboss-docx/src/parts.rs", 142, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 1]), "crates/docboss-docx/src/parts.rs", 142, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 26]), "crates/docboss-docx/src/parts.rs", 142, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 2]), "crates/docboss-docx/src/parts.rs", 142, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 5]), "crates/docboss-docx/src/parts.rs", 142, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 8]), "crates/docboss-docx/src/parts.rs", 142, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 21]), "crates/docboss-docx/src/parts.rs", 194, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 15]), "crates/docboss-docx/src/parts.rs", 220, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 1]), "crates/docboss-docx/src/parts.rs", 221, false⟩
]

def Generated.citations2 : List Citation := [
  ⟨.ecma376Part1, some (.clause [20, 1, 4, 1, 18]), "crates/docboss-docx/src/parts.rs", 238, false⟩,
  ⟨.ecma376Part2, some (.clause [8, 3]), "crates/docboss-docx/src/parts.rs", 274, false⟩,
  ⟨.ecma376Part1, some (.clause [22, 2]), "crates/docboss-docx/src/parts.rs", 275, false⟩,
  ⟨.ecma376Part1, some (.clause [15, 2, 12]), "crates/docboss-docx/src/parts.rs", 276, false⟩,
  ⟨.ecma376Part1, some (.clause [22, 2, 2]), "crates/docboss-docx/src/parts.rs", 276, false⟩,
  ⟨.ecma376Part2, some (.clause [8, 2]), "crates/docboss-docx/src/parts.rs", 276, false⟩,
  ⟨.ecma376Part2, some (.clause [8, 3, 3]), "crates/docboss-docx/src/parts.rs", 276, false⟩,
  ⟨.ecma376Part2, some (.clause [8, 3, 4]), "crates/docboss-docx/src/parts.rs", 276, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 8, 1]), "crates/docboss-docx/src/parts.rs", 323, false⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 5]), "crates/docboss-docx/src/parts.rs", 345, false⟩,
  ⟨.ecma376Part1, some (.clause [15, 2, 13]), "crates/docboss-docx/src/parts.rs", 345, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 8, 3]), "crates/docboss-docx/src/parts.rs", 345, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 8, 3]), "crates/docboss-docx/src/parts.rs", 346, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 8, 1]), "crates/docboss-docx/src/parts.rs", 409, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-docx/src/props.rs", 1, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 1, 4, 1, 18]), "crates/docboss-docx/src/props.rs", 17, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 26]), "crates/docboss-docx/src/props.rs", 41, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 19]), "crates/docboss-docx/src/props.rs", 127, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 18]), "crates/docboss-docx/src/props.rs", 128, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 3]), "crates/docboss-docx/src/props.rs", 128, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 38]), "crates/docboss-docx/src/props.rs", 140, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 4]), "crates/docboss-docx/src/props.rs", 175, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 12]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 13]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 22]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 23]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 24]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 25]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 33]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 36]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 3]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 4]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 74]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 76]), "crates/docboss-docx/src/props.rs", 196, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 5]), "crates/docboss-docx/src/props.rs", 214, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 28]), "crates/docboss-docx/src/props.rs", 252, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 11]), "crates/docboss-docx/src/props.rs", 323, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 34]), "crates/docboss-docx/src/props.rs", 323, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 5]), "crates/docboss-docx/src/props.rs", 323, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 75]), "crates/docboss-docx/src/props.rs", 323, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 59]), "crates/docboss-docx/src/props.rs", 342, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 28]), "crates/docboss-docx/src/props.rs", 344, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 31]), "crates/docboss-docx/src/props.rs", 344, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 38]), "crates/docboss-docx/src/props.rs", 344, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 42]), "crates/docboss-docx/src/props.rs", 344, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 50]), "crates/docboss-docx/src/props.rs", 344, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 52]), "crates/docboss-docx/src/props.rs", 344, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 62]), "crates/docboss-docx/src/props.rs", 344, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 63]), "crates/docboss-docx/src/props.rs", 344, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 81]), "crates/docboss-docx/src/props.rs", 361, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 49]), "crates/docboss-docx/src/props.rs", 362, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 6]), "crates/docboss-docx/src/props.rs", 362, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 80]), "crates/docboss-docx/src/props.rs", 362, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 69]), "crates/docboss-docx/src/props.rs", 377, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 17]), "crates/docboss-docx/src/props.rs", 379, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 32]), "crates/docboss-docx/src/props.rs", 379, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 66]), "crates/docboss-docx/src/props.rs", 379, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 68]), "crates/docboss-docx/src/props.rs", 379, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 71]), "crates/docboss-docx/src/props.rs", 379, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 83]), "crates/docboss-docx/src/props.rs", 379, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 84]), "crates/docboss-docx/src/props.rs", 379, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 18]), "crates/docboss-docx/src/props.rs", 410, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 2]), "crates/docboss-docx/src/props.rs", 413, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 5]), "crates/docboss-docx/src/props.rs", 413, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 6]), "crates/docboss-docx/src/props.rs", 413, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 11]), "crates/docboss-docx/src/props.rs", 413, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 12]), "crates/docboss-docx/src/props.rs", 413, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 13]), "crates/docboss-docx/src/props.rs", 413, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 22]), "crates/docboss-docx/src/props.rs", 413, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 3]), "crates/docboss-docx/src/props.rs", 413, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 4]), "crates/docboss-docx/src/props.rs", 413, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16]), "crates/docboss-docx/src/story.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2]), "crates/docboss-docx/src/story.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3]), "crates/docboss-docx/src/story.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-docx/src/story.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 18]), "crates/docboss-docx/src/story.rs", 37, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 5, 25]), "crates/docboss-docx/src/story.rs", 94, false⟩,
  ⟨.ecma376Part3, some (.clause [7, 5]), "crates/docboss-docx/src/story.rs", 287, false⟩,
  ⟨.ecma376Part3, some (.clause [7, 6]), "crates/docboss-docx/src/story.rs", 287, false⟩,
  ⟨.ecma376Part3, some (.clause [7, 7]), "crates/docboss-docx/src/story.rs", 287, false⟩,
  ⟨.ecma376Part3, some (.clause [9, 3]), "crates/docboss-docx/src/story.rs", 287, false⟩,
  ⟨.ecma376Part3, some (.clause [7, 5]), "crates/docboss-docx/src/story.rs", 288, false⟩,
  ⟨.ecma376Part3, some (.clause [9, 3]), "crates/docboss-docx/src/story.rs", 288, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2, 2]), "crates/docboss-docx/src/story.rs", 341, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 17]), "crates/docboss-docx/src/story.rs", 341, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 17, 2, 1]), "crates/docboss-docx/src/story.rs", 393, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 22]), "crates/docboss-docx/src/story.rs", 399, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 4]), "crates/docboss-docx/src/story.rs", 442, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 5]), "crates/docboss-docx/src/story.rs", 442, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 6]), "crates/docboss-docx/src/story.rs", 442, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 19]), "crates/docboss-docx/src/story.rs", 442, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 22]), "crates/docboss-docx/src/story.rs", 442, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 5, 1]), "crates/docboss-docx/src/story.rs", 442, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 5, 2]), "crates/docboss-docx/src/story.rs", 442, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 25]), "crates/docboss-docx/src/story.rs", 518, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 3]), "crates/docboss-docx/src/story.rs", 538, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 13]), "crates/docboss-docx/src/story.rs", 541, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 14]), "crates/docboss-docx/src/story.rs", 541, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 6]), "crates/docboss-docx/src/story.rs", 541, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 7]), "crates/docboss-docx/src/story.rs", 541, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 4]), "crates/docboss-docx/src/story.rs", 541, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 13]), "crates/docboss-docx/src/story.rs", 541, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 18]), "crates/docboss-docx/src/story.rs", 541, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 23]), "crates/docboss-docx/src/story.rs", 541, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 3, 9]), "crates/docboss-docx/src/story.rs", 660, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 10]), "crates/docboss-docx/src/story.rs", 663, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 11]), "crates/docboss-docx/src/story.rs", 663, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 12]), "crates/docboss-docx/src/story.rs", 663, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 38]), "crates/docboss-docx/src/story.rs", 663, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 3]), "crates/docboss-docx/src/story.rs", 663, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 5]), "crates/docboss-docx/src/story.rs", 663, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 7]), "crates/docboss-docx/src/story.rs", 663, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 8]), "crates/docboss-docx/src/story.rs", 663, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 37]), "crates/docboss-docx/src/story.rs", 664, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 42]), "crates/docboss-docx/src/story.rs", 664, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 3, 19]), "crates/docboss-docx/src/story.rs", 731, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 37]), "crates/docboss-docx/src/story.rs", 784, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 16]), "crates/docboss-docx/src/story.rs", 785, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 48]), "crates/docboss-docx/src/story.rs", 785, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 78]), "crates/docboss-docx/src/story.rs", 815, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 65]), "crates/docboss-docx/src/story.rs", 825, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 5, 25]), "crates/docboss-docx/src/story.rs", 881, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 17, 4]), "crates/docboss-docx/src/xml.rs", 52, false⟩,
  ⟨.ecma376Part1, some (.clause [22, 9, 2, 15]), "crates/docboss-docx/src/xml.rs", 74, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 18, 40]), "crates/docboss-docx/src/xml.rs", 116, false⟩,
  ⟨.ecma376Part1, some (.clause [22, 9, 2, 15]), "crates/docboss-docx/src/xml.rs", 145, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 17, 4]), "crates/docboss-docx/src/xml.rs", 157, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-docx/tests/fixtures.rs", 26, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 22]), "crates/docboss-docx/tests/structure.rs", 19, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 25]), "crates/docboss-docx/tests/structure.rs", 19, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 2, 2]), "crates/docboss-docx/tests/structure.rs", 21, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 2, 3]), "crates/docboss-docx/tests/structure.rs", 21, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-docx/tests/structure.rs", 21, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2]), "crates/docboss-docx/tests/structure.rs", 21, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 3]), "crates/docboss-docx/tests/structure.rs", 21, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 4]), "crates/docboss-docx/tests/structure.rs", 38, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 5]), "crates/docboss-docx/tests/structure.rs", 38, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 1]), "crates/docboss-docx/tests/structure.rs", 39, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 2]), "crates/docboss-docx/tests/structure.rs", 39, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 8]), "crates/docboss-docx/tests/structure.rs", 39, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 12]), "crates/docboss-docx/tests/structure.rs", 40, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-docx/tests/structure.rs", 59, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 11]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 15]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 16]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 17]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 1]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 25]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 26]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 2]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 6]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 8]), "crates/docboss-docx/tests/structure.rs", 60, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 18]), "crates/docboss-docx/tests/structure.rs", 61, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 3]), "crates/docboss-docx/tests/structure.rs", 61, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 11]), "crates/docboss-docx/tests/structure.rs", 62, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-docx/tests/structure.rs", 91, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 16]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 17]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 37]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 48]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 49]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 59]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 63]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 65]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 69]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 78]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 81]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 84]), "crates/docboss-docx/tests/structure.rs", 92, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 17]), "crates/docboss-docx/tests/structure.rs", 115, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 9]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 4]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 5]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 6]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 11]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 12]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 13]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 18]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 22]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 4]), "crates/docboss-docx/tests/structure.rs", 117, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 18]), "crates/docboss-docx/tests/structure.rs", 145, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 5, 25]), "crates/docboss-docx/tests/structure.rs", 145, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 23]), "crates/docboss-docx/tests/structure.rs", 147, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 19]), "crates/docboss-docx/tests/structure.rs", 177, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 22]), "crates/docboss-docx/tests/structure.rs", 177, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 5]), "crates/docboss-docx/tests/structure.rs", 204, true⟩,
  ⟨.ecma376Part3, some (.clause [9, 3]), "crates/docboss-docx/tests/structure.rs", 218, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 5, 2]), "crates/docboss-docx/tests/structure.rs", 220, true⟩,
  ⟨.ecma376Part3, some (.clause [7, 5]), "crates/docboss-docx/tests/structure.rs", 220, true⟩,
  ⟨.ecma376Part3, some (.clause [7, 6]), "crates/docboss-docx/tests/structure.rs", 220, true⟩,
  ⟨.ecma376Part3, some (.clause [7, 7]), "crates/docboss-docx/tests/structure.rs", 220, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 3]), "crates/docboss-docx/tests/structure.rs", 230, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 8]), "crates/docboss-docx/tests/structure.rs", 230, true⟩,
  ⟨.ecma376Part1, some (.clause [15, 2, 14]), "crates/docboss-docx/tests/structure.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 10]), "crates/docboss-docx/tests/structure.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 11]), "crates/docboss-docx/tests/structure.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 12]), "crates/docboss-docx/tests/structure.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 37]), "crates/docboss-docx/tests/structure.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 38]), "crates/docboss-docx/tests/structure.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 42]), "crates/docboss-docx/tests/structure.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 5]), "crates/docboss-docx/tests/structure.rs", 232, true⟩
]

def Generated.citations3 : List Citation := [
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 7]), "crates/docboss-docx/tests/structure.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-docx/tests/structure.rs", 276, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 4]), "crates/docboss-docx/tests/structure.rs", 276, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 2]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 4]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 7]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 10]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 13]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 14]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 15]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 23]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 2]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 7]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 8]), "crates/docboss-docx/tests/structure.rs", 278, true⟩,
  ⟨.ecma376Part2, some (.clause [8, 3]), "crates/docboss-docx/tests/structure.rs", 308, true⟩,
  ⟨.ecma376Part1, some (.clause [15, 2, 12]), "crates/docboss-docx/tests/structure.rs", 309, true⟩,
  ⟨.ecma376Part1, some (.clause [22, 2, 2]), "crates/docboss-docx/tests/structure.rs", 309, true⟩,
  ⟨.ecma376Part1, some (.clause [22, 2]), "crates/docboss-docx/tests/structure.rs", 309, true⟩,
  ⟨.ecma376Part2, some (.clause [8, 2]), "crates/docboss-docx/tests/structure.rs", 309, true⟩,
  ⟨.ecma376Part2, some (.clause [8, 3, 3]), "crates/docboss-docx/tests/structure.rs", 309, true⟩,
  ⟨.ecma376Part2, some (.clause [8, 3, 4]), "crates/docboss-docx/tests/structure.rs", 309, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 17, 2, 1]), "crates/docboss-docx/tests/structure.rs", 397, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 28]), "crates/docboss-docx/tests/structure.rs", 408, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 31]), "crates/docboss-docx/tests/structure.rs", 408, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 38]), "crates/docboss-docx/tests/structure.rs", 408, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 42]), "crates/docboss-docx/tests/structure.rs", 408, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 50]), "crates/docboss-docx/tests/structure.rs", 408, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 52]), "crates/docboss-docx/tests/structure.rs", 408, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 62]), "crates/docboss-docx/tests/structure.rs", 408, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 6]), "crates/docboss-docx/tests/structure.rs", 409, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 80]), "crates/docboss-docx/tests/structure.rs", 409, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 34]), "crates/docboss-docx/tests/structure.rs", 410, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 3]), "crates/docboss-docx/tests/structure.rs", 410, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 76]), "crates/docboss-docx/tests/structure.rs", 410, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 32]), "crates/docboss-docx/tests/structure.rs", 411, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 66]), "crates/docboss-docx/tests/structure.rs", 411, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 68]), "crates/docboss-docx/tests/structure.rs", 411, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 71]), "crates/docboss-docx/tests/structure.rs", 411, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 83]), "crates/docboss-docx/tests/structure.rs", 411, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 4]), "crates/docboss-docx/tests/structure.rs", 412, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 5]), "crates/docboss-docx/tests/structure.rs", 413, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 3]), "crates/docboss-docx/tests/structure.rs", 448, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 3]), "crates/docboss-docx/tests/structure.rs", 451, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 6]), "crates/docboss-docx/tests/structure.rs", 451, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 1]), "crates/docboss-docx/tests/structure.rs", 451, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 2]), "crates/docboss-docx/tests/structure.rs", 451, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 10, 3]), "crates/docboss-docx/tests/structure.rs", 451, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 15, 1]), "crates/docboss-docx/tests/structure.rs", 451, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 3]), "crates/docboss-docx/tests/structure.rs", 451, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 6]), "crates/docboss-docx/tests/structure.rs", 485, true⟩,
  ⟨.ecma376Part2, some (.clause [6, 2, 2, 3]), "crates/docboss-docx/tests/structure.rs", 502, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 5]), "crates/docboss-docx/tests/structure.rs", 502, true⟩,
  ⟨.ecma376Part1, some (.clause [11, 3, 10]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part2, some (.clause [6, 2, 2]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part2, some (.clause [6, 2, 3]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part2, some (.clause [6, 5, 3]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 2, 3]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 2, 5]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 2]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 3]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 5]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 7]), "crates/docboss-docx/tests/structure.rs", 507, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6]), "crates/docboss-layout/src/flow.rs", 568, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 10]), "crates/docboss-layout/src/flow.rs", 742, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-layout/src/flow.rs", 742, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/src/paragraph.rs", 117, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 15, 1]), "crates/docboss-layout/src/paragraph.rs", 119, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16]), "crates/docboss-layout/src/paragraph.rs", 192, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/src/paragraph.rs", 284, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2]), "crates/docboss-layout/src/shape.rs", 39, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-layout/src/table.rs", 85, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-layout/src/table.rs", 263, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 3]), "crates/docboss-layout/tests/layout.rs", 147, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-layout/tests/layout.rs", 176, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 10]), "crates/docboss-layout/tests/layout.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16]), "crates/docboss-layout/tests/layout.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-layout/tests/layout.rs", 271, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-layout/tests/layout.rs", 314, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/tests/layout.rs", 371, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/tests/layout.rs", 394, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6]), "crates/docboss-layout/tests/layout.rs", 430, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/tests/layout.rs", 445, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-layout/tests/layout.rs", 466, true⟩,
  ⟨.msDoc, none, "crates/docboss-model/src/document.rs", 13, false⟩,
  ⟨.msDoc, none, "crates/docboss-model/src/lib.rs", 4, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 1]), "crates/docboss-model/src/style.rs", 95, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 2]), "crates/docboss-model/src/style.rs", 122, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 3]), "crates/docboss-model/src/style.rs", 148, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 18, 59]), "crates/docboss-model/tests/ledger_vectors.rs", 2, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 3]), "crates/docboss-model/tests/resolution.rs", 13, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 4, 3]), "crates/docboss-model/tests/resolution.rs", 48, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 11]), "crates/docboss-model/tests/resolution.rs", 102, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 23]), "crates/docboss-output/src/walk.rs", 89, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 5, 25]), "crates/docboss-output/src/walk.rs", 209, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 41]), "crates/docboss-output/src/walk.rs", 272, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-output/src/walk.rs", 385, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 17]), "crates/docboss-output/src/walk.rs", 466, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-output/tests/text.rs", 11, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 41]), "crates/docboss-output/tests/text.rs", 41, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16]), "crates/docboss-output/tests/text.rs", 81, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3]), "crates/docboss-write/src/body.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 22]), "crates/docboss-write/src/body.rs", 120, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 18]), "crates/docboss-write/src/body.rs", 156, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 5]), "crates/docboss-write/src/body.rs", 174, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 8]), "crates/docboss-write/src/body.rs", 277, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 38]), "crates/docboss-write/src/body.rs", 398, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 23]), "crates/docboss-write/src/docx.rs", 45, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2, 2]), "crates/docboss-write/src/docx.rs", 291, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 17]), "crates/docboss-write/src/docx.rs", 291, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 4]), "crates/docboss-write/src/package.rs", 1, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 7]), "crates/docboss-write/src/package.rs", 1, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 5]), "crates/docboss-write/src/package.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 4]), "crates/docboss-write/src/parts.rs", 10, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-write/src/parts.rs", 86, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 15, 1]), "crates/docboss-write/src/parts.rs", 130, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 8, 3]), "crates/docboss-write/src/parts.rs", 155, false⟩,
  ⟨.ecma376Part2, some (.clause [8]), "crates/docboss-write/src/parts.rs", 176, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-write/src/props.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 18, 40]), "crates/docboss-write/src/props.rs", 71, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2]), "crates/docboss-write/tests/libreoffice.rs", 5, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-write/tests/markdown.rs", 42, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-write/tests/markdown.rs", 108, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 4]), "crates/docboss-write/tests/package.rs", 14, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 3, 7]), "crates/docboss-write/tests/package.rs", 14, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 2, 3]), "crates/docboss-write/tests/package.rs", 15, true⟩,
  ⟨.ecma376Part2, some (.clause [6, 5]), "crates/docboss-write/tests/package.rs", 32, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 23]), "crates/docboss-write/tests/package.rs", 53, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 5, 14]), "crates/docboss-write/tests/package.rs", 53, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 17]), "crates/docboss-write/tests/package.rs", 73, true⟩,
  ⟨.ecma376Part3, none, "crates/docboss-xml/src/ns.rs", 26, false⟩,
  ⟨.appnote, none, "crates/docboss-zip/src/cp437.rs", 1, false⟩,
  ⟨.appnote, none, "crates/docboss-zip/src/cp437.rs", 29, true⟩,
  ⟨.appnote, some (.clause [4, 4, 7]), "crates/docboss-zip/src/crc.rs", 1, false⟩,
  ⟨.appnote, some (.clause [4, 4, 7]), "crates/docboss-zip/src/crc.rs", 69, true⟩,
  ⟨.appnote, some (.clause [4, 1, 5]), "crates/docboss-zip/src/lib.rs", 10, false⟩,
  ⟨.appnote, some (.clause [4, 3, 8]), "crates/docboss-zip/src/lib.rs", 10, false⟩,
  ⟨.appnote, some (.clause [4, 4, 7]), "crates/docboss-zip/src/lib.rs", 10, false⟩,
  ⟨.appnote, some (.clause [4, 4, 5]), "crates/docboss-zip/src/lib.rs", 74, false⟩,
  ⟨.appnote, some (.clause [5, 5]), "crates/docboss-zip/src/lib.rs", 75, false⟩,
  ⟨.appnote, some (.clause [4, 4, 4]), "crates/docboss-zip/src/lib.rs", 101, false⟩,
  ⟨.appnote, some (.clause [4, 4, 17]), "crates/docboss-zip/src/lib.rs", 138, false⟩,
  ⟨.appnote, some (.clause [4, 4, 4]), "crates/docboss-zip/src/lib.rs", 138, false⟩,
  ⟨.appnote, some (.clause [4, 3, 12]), "crates/docboss-zip/src/lib.rs", 466, false⟩,
  ⟨.appnote, some (.clause [4, 3, 16]), "crates/docboss-zip/src/lib.rs", 467, false⟩,
  ⟨.appnote, some (.clause [4, 3, 12]), "crates/docboss-zip/src/lib.rs", 468, false⟩,
  ⟨.appnote, some (.clause [4, 3, 14]), "crates/docboss-zip/src/lib.rs", 468, false⟩,
  ⟨.appnote, some (.clause [4, 3, 15]), "crates/docboss-zip/src/lib.rs", 468, false⟩,
  ⟨.appnote, some (.clause [4, 3, 16]), "crates/docboss-zip/src/lib.rs", 468, false⟩,
  ⟨.appnote, some (.clause [4, 3, 6]), "crates/docboss-zip/src/lib.rs", 468, false⟩,
  ⟨.appnote, some (.clause [4, 3, 7]), "crates/docboss-zip/src/lib.rs", 528, false⟩,
  ⟨.appnote, some (.clause [4, 3, 9]), "crates/docboss-zip/src/lib.rs", 530, false⟩,
  ⟨.appnote, some (.clause [4, 4, 4]), "crates/docboss-zip/src/lib.rs", 530, false⟩,
  ⟨.appnote, some (.clause [4, 5, 3]), "crates/docboss-zip/src/write.rs", 242, false⟩,
  ⟨.appnote, some (.clause [4, 3, 16]), "crates/docboss-zip/src/write.rs", 287, true⟩,
  ⟨.appnote, some (.clause [4, 3, 14]), "crates/docboss-zip/src/write.rs", 299, true⟩,
  ⟨.appnote, some (.clause [4, 3, 7]), "crates/docboss-zip/src/write.rs", 299, true⟩,
  ⟨.appnote, some (.clause [4, 3, 9]), "crates/docboss-zip/src/write.rs", 299, true⟩,
  ⟨.appnote, some (.clause [4, 3, 12]), "crates/docboss-zip/tests/archive.rs", 24, true⟩,
  ⟨.appnote, some (.clause [4, 3, 16]), "crates/docboss-zip/tests/archive.rs", 24, true⟩,
  ⟨.appnote, some (.clause [4, 3, 6]), "crates/docboss-zip/tests/archive.rs", 26, true⟩,
  ⟨.appnote, some (.clause [4, 3, 8]), "crates/docboss-zip/tests/archive.rs", 26, true⟩,
  ⟨.appnote, some (.clause [4, 4, 5]), "crates/docboss-zip/tests/archive.rs", 26, true⟩,
  ⟨.appnote, some (.clause [5, 5]), "crates/docboss-zip/tests/archive.rs", 26, true⟩,
  ⟨.appnote, some (.clause [4, 3, 9]), "crates/docboss-zip/tests/archive.rs", 32, true⟩,
  ⟨.appnote, some (.clause [4, 4, 4]), "crates/docboss-zip/tests/archive.rs", 33, true⟩,
  ⟨.appnote, some (.clause [4, 3, 14]), "crates/docboss-zip/tests/archive.rs", 42, true⟩,
  ⟨.appnote, some (.clause [4, 3, 15]), "crates/docboss-zip/tests/archive.rs", 42, true⟩,
  ⟨.appnote, some (.clause [4, 5, 3]), "crates/docboss-zip/tests/archive.rs", 42, true⟩,
  ⟨.appnote, some (.clause [4, 3, 7]), "crates/docboss-zip/tests/archive.rs", 72, true⟩,
  ⟨.appnote, some (.clause [4, 1, 5]), "crates/docboss-zip/tests/archive.rs", 100, true⟩,
  ⟨.appnote, some (.clause [4, 4, 7]), "crates/docboss-zip/tests/archive.rs", 100, true⟩,
  ⟨.appnote, none, "crates/docboss-zip/tests/archive.rs", 136, true⟩,
  ⟨.appnote, some (.clause [4, 4, 17]), "crates/docboss-zip/tests/archive.rs", 138, true⟩,
  ⟨.appnote, some (.clause [4, 4, 4]), "crates/docboss-zip/tests/archive.rs", 138, true⟩,
  ⟨.appnote, some (.clause [4, 4, 7]), "crates/docboss-zip/tests/ledger_vectors.rs", 10, true⟩
]

def Generated.citations : List Citation :=
  Generated.citations0 ++ Generated.citations1 ++ Generated.citations2 ++ Generated.citations3

end Ledger
