import Ledger.Feature

/-!
Citations of the tracked specifications in the docboss source tree, written by
`lake exe ledger-index`. Regenerate rather than edit.
-/

namespace Ledger

def Generated.citations0 : List Citation := [
  ⟨.msCfb, some (.clause [2, 6, 1]), "crates/docboss-cfb/src/directory.rs", 3, false⟩,
  ⟨.msCfb, some (.clause [2, 6, 1]), "crates/docboss-cfb/src/directory.rs", 12, false⟩,
  ⟨.msCfb, none, "crates/docboss-cfb/src/lib.rs", 1, false⟩,
  ⟨.msOleps, none, "crates/docboss-cfb/src/lib.rs", 2, false⟩,
  ⟨.msCfb, some (.clause [2, 2]), "crates/docboss-cfb/src/lib.rs", 29, false⟩,
  ⟨.msCfb, some (.clause [2, 2]), "crates/docboss-cfb/src/lib.rs", 72, false⟩,
  ⟨.msCfb, some (.clause [2, 5]), "crates/docboss-cfb/src/lib.rs", 191, false⟩,
  ⟨.msCfb, some (.clause [2, 4]), "crates/docboss-cfb/src/lib.rs", 331, false⟩,
  ⟨.msCfb, some (.clause [2, 6, 4]), "crates/docboss-cfb/src/lib.rs", 380, false⟩,
  ⟨.msCfb, some (.clause [2, 6, 4]), "crates/docboss-cfb/src/lib.rs", 409, false⟩,
  ⟨.msOleps, none, "crates/docboss-cfb/src/property.rs", 1, false⟩,
  ⟨.msOleps, some (.clause [2, 15]), "crates/docboss-cfb/src/property.rs", 19, false⟩,
  ⟨.msOleps, some (.clause [2, 21]), "crates/docboss-cfb/src/property.rs", 72, false⟩,
  ⟨.msOleps, some (.clause [2, 20]), "crates/docboss-cfb/src/property.rs", 98, false⟩,
  ⟨.msOleps, some (.clause [2, 15]), "crates/docboss-cfb/src/property.rs", 145, false⟩,
  ⟨.msOleps, some (.clause [2, 15]), "crates/docboss-cfb/src/time.rs", 3, false⟩,
  ⟨.msCfb, some (.clause [2, 2]), "crates/docboss-cfb/tests/cfb.rs", 5, true⟩,
  ⟨.msCfb, some (.clause [2, 6, 4]), "crates/docboss-cfb/tests/cfb.rs", 30, true⟩,
  ⟨.msOleps, some (.clause [2, 21]), "crates/docboss-cfb/tests/cfb.rs", 41, true⟩,
  ⟨.msCfb, some (.clause [2, 3]), "crates/docboss-cfb/tests/cfb.rs", 79, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 2]), "crates/docboss-doc/src/bytes.rs", 37, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 6]), "crates/docboss-doc/src/crypt.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 3]), "crates/docboss-doc/src/document.rs", 20, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 6, 2]), "crates/docboss-doc/src/document.rs", 104, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 6, 3]), "crates/docboss-doc/src/document.rs", 104, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 19]), "crates/docboss-doc/src/document.rs", 243, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 7]), "crates/docboss-doc/src/document.rs", 273, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 10]), "crates/docboss-doc/src/document.rs", 342, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 27]), "crates/docboss-doc/src/document.rs", 365, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 171]), "crates/docboss-doc/src/document.rs", 366, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 26]), "crates/docboss-doc/src/document.rs", 478, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 22]), "crates/docboss-doc/src/document.rs", 479, false⟩,
  ⟨.msDoc, some (.clause [2, 5]), "crates/docboss-doc/src/fib.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 6]), "crates/docboss-doc/src/fib.rs", 6, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 4]), "crates/docboss-doc/src/fib.rs", 36, false⟩,
  ⟨.msDoc, some (.clause [2, 5, 15]), "crates/docboss-doc/src/fib.rs", 68, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 33]), "crates/docboss-doc/src/fkp.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 5]), "crates/docboss-doc/src/fkp.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 6]), "crates/docboss-doc/src/fkp.rs", 2, false⟩,
  ⟨.msDoc, none, "crates/docboss-doc/src/lib.rs", 1, false⟩,
  ⟨.msCfb, none, "crates/docboss-doc/src/lib.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 201]), "crates/docboss-doc/src/lists.rs", 1, false⟩,
  ⟨.msOshared, some (.clause [2, 2, 1, 3]), "crates/docboss-doc/src/lists.rs", 16, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 149]), "crates/docboss-doc/src/lists.rs", 47, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 190]), "crates/docboss-doc/src/picture.rs", 1, false⟩,
  ⟨.msOdraw, some (.clause [2, 2, 23]), "crates/docboss-doc/src/picture.rs", 2, false⟩,
  ⟨.msOdraw, some (.clause [2, 2, 1]), "crates/docboss-doc/src/picture.rs", 12, false⟩,
  ⟨.msOdraw, some (.clause [2, 2, 23]), "crates/docboss-doc/src/picture.rs", 59, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 192]), "crates/docboss-doc/src/picture.rs", 170, false⟩,
  ⟨.msOdraw, some (.clause [2, 3, 23, 1]), "crates/docboss-doc/src/picture.rs", 199, false⟩,
  ⟨.msOdraw, some (.clause [2, 2, 40]), "crates/docboss-doc/src/picture.rs", 212, false⟩,
  ⟨.msDoc, some (.clause [2, 6]), "crates/docboss-doc/src/props.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 119]), "crates/docboss-doc/src/props.rs", 12, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 43]), "crates/docboss-doc/src/props.rs", 41, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 65]), "crates/docboss-doc/src/props.rs", 49, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 17]), "crates/docboss-doc/src/props.rs", 118, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 16]), "crates/docboss-doc/src/props.rs", 132, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 247]), "crates/docboss-doc/src/props.rs", 148, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 248]), "crates/docboss-doc/src/props.rs", 160, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 1]), "crates/docboss-doc/src/props.rs", 212, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 2]), "crates/docboss-doc/src/props.rs", 391, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 4]), "crates/docboss-doc/src/props.rs", 484, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 4]), "crates/docboss-doc/src/props.rs", 494, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 65]), "crates/docboss-doc/src/props.rs", 576, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 43]), "crates/docboss-doc/src/props.rs", 585, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 146]), "crates/docboss-doc/src/props.rs", 592, true⟩,
  ⟨.msDoc, some (.clause [2, 6, 1]), "crates/docboss-doc/src/props.rs", 609, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 5]), "crates/docboss-doc/src/sprm.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 5, 1]), "crates/docboss-doc/src/sprm.rs", 15, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 5, 1]), "crates/docboss-doc/src/sprm.rs", 46, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 5, 1]), "crates/docboss-doc/src/sprm.rs", 87, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 2]), "crates/docboss-doc/src/story.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 6]), "crates/docboss-doc/src/story.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 3]), "crates/docboss-doc/src/story.rs", 3, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 253]), "crates/docboss-doc/src/story.rs", 30, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 90]), "crates/docboss-doc/src/story.rs", 214, false⟩,
  ⟨.msDoc, some (.clause [2, 3, 6]), "crates/docboss-doc/src/story.rs", 510, false⟩,
  ⟨.msDoc, some (.clause [2, 8, 32]), "crates/docboss-doc/src/story.rs", 510, false⟩,
  ⟨.msDoc, some (.clause [2, 2, 4]), "crates/docboss-doc/src/sttb.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 82]), "crates/docboss-doc/src/sttb.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 82]), "crates/docboss-doc/src/sttb.rs", 84, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 353]), "crates/docboss-doc/src/sttb.rs", 114, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 271]), "crates/docboss-doc/src/styles.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 258]), "crates/docboss-doc/src/styles.rs", 44, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 271]), "crates/docboss-doc/src/styles.rs", 44, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 3]), "crates/docboss-doc/src/table.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 6, 3]), "crates/docboss-doc/src/table.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 313]), "crates/docboss-doc/src/table.rs", 13, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 38]), "crates/docboss-doc/src/text.rs", 1, false⟩,
  ⟨.msDoc, some (.clause [2, 4, 1]), "crates/docboss-doc/src/text.rs", 2, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 215]), "crates/docboss-doc/src/text.rs", 44, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 38]), "crates/docboss-doc/src/text.rs", 80, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 214]), "crates/docboss-doc/src/text.rs", 152, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 73]), "crates/docboss-doc/src/text.rs", 194, false⟩,
  ⟨.msDoc, some (.clause [2, 9, 73]), "crates/docboss-doc/src/text.rs", 204, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 1]), "crates/docboss-doc/tests/read.rs", 50, true⟩,
  ⟨.msDoc, some (.clause [2, 5, 1]), "crates/docboss-doc/tests/read.rs", 59, true⟩,
  ⟨.msOleps, some (.clause [2, 21]), "crates/docboss-doc/tests/read.rs", 59, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 6, 2]), "crates/docboss-doc/tests/read.rs", 73, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 6, 3]), "crates/docboss-doc/tests/read.rs", 125, true⟩,
  ⟨.msDoc, some (.clause [2, 4, 3]), "crates/docboss-doc/tests/read.rs", 138, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 2]), "crates/docboss-doc/tests/read.rs", 168, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 4]), "crates/docboss-doc/tests/read.rs", 168, true⟩,
  ⟨.msDoc, some (.clause [2, 3, 5]), "crates/docboss-doc/tests/read.rs", 168, true⟩,
  ⟨.msDoc, some (.clause [2, 9, 192]), "crates/docboss-doc/tests/read.rs", 215, true⟩,
  ⟨.msOdraw, some (.clause [2, 2, 24]), "crates/docboss-doc/tests/read.rs", 215, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 26]), "crates/docboss-doc/tests/read.rs", 236, true⟩,
  ⟨.msDoc, some (.clause [2, 2, 6, 2]), "crates/docboss-doc/tests/read.rs", 280, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 27]), "crates/docboss-doc/tests/read.rs", 307, true⟩,
  ⟨.msOdraw, some (.clause [2, 2, 32]), "crates/docboss-doc/tests/read.rs", 307, true⟩,
  ⟨.msDoc, some (.clause [2, 8, 32]), "crates/docboss-doc/tests/read.rs", 308, true⟩,
  ⟨.ecma376Part2, none, "crates/docboss-docx/src/package.rs", 1, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 5, 3, 4]), "crates/docboss-docx/src/package.rs", 10, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 4]), "crates/docboss-docx/src/package.rs", 61, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 5, 2]), "crates/docboss-docx/src/package.rs", 121, false⟩,
  ⟨.ecma376Part2, some (.clause [7, 2, 3, 2]), "crates/docboss-docx/src/package.rs", 173, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 4, 3]), "crates/docboss-docx/src/package.rs", 293, true⟩,
  ⟨.ecma376Part2, some (.clause [6, 5, 2]), "crates/docboss-docx/src/package.rs", 320, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7]), "crates/docboss-docx/src/parts.rs", 16, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-docx/src/parts.rs", 132, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 21]), "crates/docboss-docx/src/parts.rs", 185, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 15]), "crates/docboss-docx/src/parts.rs", 211, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 1, 4, 1, 18]), "crates/docboss-docx/src/parts.rs", 228, false⟩,
  ⟨.ecma376Part2, some (.clause [8, 3]), "crates/docboss-docx/src/parts.rs", 264, false⟩,
  ⟨.ecma376Part1, some (.clause [22, 2]), "crates/docboss-docx/src/parts.rs", 265, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 8, 1]), "crates/docboss-docx/src/parts.rs", 312, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 8, 3]), "crates/docboss-docx/src/parts.rs", 334, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 8, 1]), "crates/docboss-docx/src/parts.rs", 397, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-docx/src/props.rs", 1, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 1, 4, 1, 18]), "crates/docboss-docx/src/props.rs", 17, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 26]), "crates/docboss-docx/src/props.rs", 41, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 19]), "crates/docboss-docx/src/props.rs", 127, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 38]), "crates/docboss-docx/src/props.rs", 139, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 5]), "crates/docboss-docx/src/props.rs", 211, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 28]), "crates/docboss-docx/src/props.rs", 249, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 59]), "crates/docboss-docx/src/props.rs", 337, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 81]), "crates/docboss-docx/src/props.rs", 354, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 69]), "crates/docboss-docx/src/props.rs", 369, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 18]), "crates/docboss-docx/src/props.rs", 400, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16]), "crates/docboss-docx/src/story.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2]), "crates/docboss-docx/src/story.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3]), "crates/docboss-docx/src/story.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-docx/src/story.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 18]), "crates/docboss-docx/src/story.rs", 37, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 5, 25]), "crates/docboss-docx/src/story.rs", 94, false⟩,
  ⟨.ecma376Part3, some (.clause [7, 5]), "crates/docboss-docx/src/story.rs", 287, false⟩,
  ⟨.ecma376Part3, some (.clause [9, 3]), "crates/docboss-docx/src/story.rs", 287, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2, 2]), "crates/docboss-docx/src/story.rs", 340, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 17]), "crates/docboss-docx/src/story.rs", 340, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 17, 2, 1]), "crates/docboss-docx/src/story.rs", 392, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 22]), "crates/docboss-docx/src/story.rs", 398, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 25]), "crates/docboss-docx/src/story.rs", 513, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 3, 9]), "crates/docboss-docx/src/story.rs", 651, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 3, 19]), "crates/docboss-docx/src/story.rs", 719, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 37]), "crates/docboss-docx/src/story.rs", 772, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 78]), "crates/docboss-docx/src/story.rs", 802, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 5, 25]), "crates/docboss-docx/src/story.rs", 867, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 17, 4]), "crates/docboss-docx/src/xml.rs", 52, false⟩,
  ⟨.ecma376Part1, some (.clause [22, 9, 2, 15]), "crates/docboss-docx/src/xml.rs", 74, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 18, 40]), "crates/docboss-docx/src/xml.rs", 116, false⟩,
  ⟨.ecma376Part1, some (.clause [22, 9, 2, 15]), "crates/docboss-docx/src/xml.rs", 145, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 17, 4]), "crates/docboss-docx/src/xml.rs", 157, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-docx/tests/fixtures.rs", 26, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1, 22]), "crates/docboss-docx/tests/structure.rs", 18, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 25]), "crates/docboss-docx/tests/structure.rs", 18, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 4]), "crates/docboss-docx/tests/structure.rs", 36, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 5]), "crates/docboss-docx/tests/structure.rs", 36, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-docx/tests/structure.rs", 55, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-docx/tests/structure.rs", 84, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 17]), "crates/docboss-docx/tests/structure.rs", 107, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 18]), "crates/docboss-docx/tests/structure.rs", 136, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 5, 25]), "crates/docboss-docx/tests/structure.rs", 136, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 19]), "crates/docboss-docx/tests/structure.rs", 167, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 22]), "crates/docboss-docx/tests/structure.rs", 167, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 5]), "crates/docboss-docx/tests/structure.rs", 194, true⟩,
  ⟨.ecma376Part3, some (.clause [9, 3]), "crates/docboss-docx/tests/structure.rs", 208, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 3]), "crates/docboss-docx/tests/structure.rs", 219, true⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 8]), "crates/docboss-docx/tests/structure.rs", 219, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-docx/tests/structure.rs", 264, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 4]), "crates/docboss-docx/tests/structure.rs", 264, true⟩,
  ⟨.ecma376Part2, some (.clause [8, 3]), "crates/docboss-docx/tests/structure.rs", 295, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 17, 2, 1]), "crates/docboss-docx/tests/structure.rs", 383, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6]), "crates/docboss-layout/src/flow.rs", 568, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 10]), "crates/docboss-layout/src/flow.rs", 742, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-layout/src/flow.rs", 742, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/src/paragraph.rs", 117, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 15, 1]), "crates/docboss-layout/src/paragraph.rs", 119, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16]), "crates/docboss-layout/src/paragraph.rs", 192, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/src/paragraph.rs", 284, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2]), "crates/docboss-layout/src/shape.rs", 39, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-layout/src/table.rs", 85, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-layout/src/table.rs", 263, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 3]), "crates/docboss-layout/tests/layout.rs", 147, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-layout/tests/layout.rs", 176, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 10]), "crates/docboss-layout/tests/layout.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16]), "crates/docboss-layout/tests/layout.rs", 232, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-layout/tests/layout.rs", 271, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-layout/tests/layout.rs", 314, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/tests/layout.rs", 371, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/tests/layout.rs", 394, true⟩
]

def Generated.citations1 : List Citation := [
  ⟨.ecma376Part1, some (.clause [17, 6]), "crates/docboss-layout/tests/layout.rs", 430, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-layout/tests/layout.rs", 445, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 4]), "crates/docboss-layout/tests/layout.rs", 466, true⟩,
  ⟨.msDoc, none, "crates/docboss-model/src/document.rs", 13, false⟩,
  ⟨.msDoc, none, "crates/docboss-model/src/lib.rs", 4, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 3]), "crates/docboss-model/src/style.rs", 147, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 18, 59]), "crates/docboss-model/tests/ledger_vectors.rs", 2, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 3]), "crates/docboss-model/tests/resolution.rs", 13, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 4, 3]), "crates/docboss-model/tests/resolution.rs", 48, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 11]), "crates/docboss-model/tests/resolution.rs", 102, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9, 23]), "crates/docboss-output/src/walk.rs", 89, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 5, 25]), "crates/docboss-output/src/walk.rs", 209, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 41]), "crates/docboss-output/src/walk.rs", 272, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-output/src/walk.rs", 385, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 17]), "crates/docboss-output/src/walk.rs", 466, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-output/tests/text.rs", 11, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 2, 41]), "crates/docboss-output/tests/text.rs", 41, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 16]), "crates/docboss-output/tests/text.rs", 81, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 3]), "crates/docboss-write/src/body.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 22]), "crates/docboss-write/src/body.rs", 120, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 16, 18]), "crates/docboss-write/src/body.rs", 156, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 5]), "crates/docboss-write/src/body.rs", 174, false⟩,
  ⟨.ecma376Part1, some (.clause [20, 4, 2, 8]), "crates/docboss-write/src/body.rs", 277, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 4, 38]), "crates/docboss-write/src/body.rs", 398, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 23]), "crates/docboss-write/src/docx.rs", 45, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2, 2]), "crates/docboss-write/src/docx.rs", 291, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 17]), "crates/docboss-write/src/docx.rs", 291, false⟩,
  ⟨.ecma376Part2, some (.clause [6, 5]), "crates/docboss-write/src/package.rs", 1, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 7, 4]), "crates/docboss-write/src/parts.rs", 10, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-write/src/parts.rs", 86, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 15, 1]), "crates/docboss-write/src/parts.rs", 130, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 8, 3]), "crates/docboss-write/src/parts.rs", 155, false⟩,
  ⟨.ecma376Part2, some (.clause [8]), "crates/docboss-write/src/parts.rs", 176, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 3, 1]), "crates/docboss-write/src/props.rs", 2, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 18, 40]), "crates/docboss-write/src/props.rs", 71, false⟩,
  ⟨.ecma376Part1, some (.clause [17, 2]), "crates/docboss-write/tests/libreoffice.rs", 5, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 9]), "crates/docboss-write/tests/markdown.rs", 42, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11]), "crates/docboss-write/tests/markdown.rs", 108, true⟩,
  ⟨.ecma376Part2, some (.clause [7, 2, 3]), "crates/docboss-write/tests/package.rs", 14, true⟩,
  ⟨.ecma376Part2, some (.clause [6, 5]), "crates/docboss-write/tests/package.rs", 31, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 11, 23]), "crates/docboss-write/tests/package.rs", 52, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 13, 5, 14]), "crates/docboss-write/tests/package.rs", 52, true⟩,
  ⟨.ecma376Part1, some (.clause [17, 6, 17]), "crates/docboss-write/tests/package.rs", 72, true⟩,
  ⟨.ecma376Part3, none, "crates/docboss-xml/src/ns.rs", 26, false⟩,
  ⟨.appnote, none, "crates/docboss-zip/src/cp437.rs", 1, false⟩,
  ⟨.appnote, none, "crates/docboss-zip/src/cp437.rs", 29, true⟩,
  ⟨.appnote, some (.clause [4, 4, 7]), "crates/docboss-zip/src/crc.rs", 1, false⟩,
  ⟨.appnote, some (.clause [4, 4, 7]), "crates/docboss-zip/src/crc.rs", 69, true⟩,
  ⟨.appnote, some (.clause [4, 4, 5]), "crates/docboss-zip/src/lib.rs", 73, false⟩,
  ⟨.appnote, some (.clause [4, 3, 12]), "crates/docboss-zip/src/lib.rs", 460, false⟩,
  ⟨.appnote, some (.clause [4, 3, 16]), "crates/docboss-zip/src/lib.rs", 461, false⟩,
  ⟨.appnote, some (.clause [4, 3, 7]), "crates/docboss-zip/src/lib.rs", 521, false⟩,
  ⟨.appnote, some (.clause [4, 5, 3]), "crates/docboss-zip/src/write.rs", 242, false⟩,
  ⟨.appnote, some (.clause [4, 3, 16]), "crates/docboss-zip/src/write.rs", 287, true⟩,
  ⟨.appnote, some (.clause [4, 3, 14]), "crates/docboss-zip/src/write.rs", 299, true⟩,
  ⟨.appnote, some (.clause [4, 3, 7]), "crates/docboss-zip/src/write.rs", 299, true⟩,
  ⟨.appnote, some (.clause [4, 3, 9]), "crates/docboss-zip/src/write.rs", 299, true⟩,
  ⟨.appnote, some (.clause [4, 3, 12]), "crates/docboss-zip/tests/archive.rs", 24, true⟩,
  ⟨.appnote, some (.clause [4, 3, 16]), "crates/docboss-zip/tests/archive.rs", 24, true⟩,
  ⟨.appnote, some (.clause [4, 3, 9]), "crates/docboss-zip/tests/archive.rs", 31, true⟩,
  ⟨.appnote, some (.clause [4, 3, 14]), "crates/docboss-zip/tests/archive.rs", 40, true⟩,
  ⟨.appnote, some (.clause [4, 3, 15]), "crates/docboss-zip/tests/archive.rs", 40, true⟩,
  ⟨.appnote, some (.clause [4, 5, 3]), "crates/docboss-zip/tests/archive.rs", 40, true⟩,
  ⟨.appnote, some (.clause [4, 3, 7]), "crates/docboss-zip/tests/archive.rs", 70, true⟩,
  ⟨.appnote, none, "crates/docboss-zip/tests/archive.rs", 132, true⟩,
  ⟨.appnote, some (.clause [4, 4, 7]), "crates/docboss-zip/tests/ledger_vectors.rs", 10, true⟩
]

def Generated.citations : List Citation :=
  Generated.citations0 ++ Generated.citations1

end Ledger
