import Ledger.Ref

/-!
The clause outline of PKWARE APPNOTE.TXT: .ZIP File Format Specification,
derived from the specification text by `tools/outline.py`. Regenerate rather than edit.
-/

namespace Ledger.Outline.Appnote

/-- Chapter titles by number. -/
def chapters : List (Nat × String) := [
  (1, "Introduction"),
  (2, "Revisions"),
  (3, "Notations"),
  (4, "ZIP Files"),
  (5, "Explanation of compression methods"),
  (6, "Traditional PKWARE Encryption"),
  (7, "Strong Encryption Specification"),
  (8, "Splitting and Spanning ZIP files"),
  (9, "Change Process"),
  (10, "Incorporating PKWARE Proprietary Technology into Your Product"),
  (11, "Acknowledgements"),
  (12, "References")
]

/-- Annex titles by letter. -/
def annexes : List (Char × String) := [

]

def headings0 : List Heading := [
  ⟨.clause [1, 1], "Purpose"⟩,
  ⟨.clause [1, 1, 1], "This specification is intended to define a cross-platform, interoperable file…"⟩,
  ⟨.clause [1, 2], "Scope"⟩,
  ⟨.clause [1, 2, 1], "ZIP is one of the most widely used compressed file formats"⟩,
  ⟨.clause [1, 3], "Trademarks"⟩,
  ⟨.clause [1, 3, 1], "PKWARE, PKZIP, Smartcrypt, SecureZIP, and PKSFX are registered trademarks of…"⟩,
  ⟨.clause [1, 4], "Permitted Use"⟩,
  ⟨.clause [1, 4, 1], "This document, \"APPNOTE.TXT - .ZIP File Format Specification\" is the exclusive…"⟩,
  ⟨.clause [1, 4, 2], "Use of the content of this document within other publications is permitted only…"⟩,
  ⟨.clause [1, 4, 3], "Certain technological components provided in this document are the patented…"⟩,
  ⟨.clause [1, 5], "Contacting PKWARE"⟩,
  ⟨.clause [1, 5, 1], "If you have questions on this format, its use, or licensing, or if you wish to…"⟩,
  ⟨.clause [1, 5, 2], "Information about this format and a reference copy of this document is publicly…"⟩,
  ⟨.clause [1, 6], "Disclaimer"⟩,
  ⟨.clause [1, 6, 1], "Although PKWARE will attempt to supply current and accurate information…"⟩,
  ⟨.clause [2, 1], "Document Status"⟩,
  ⟨.clause [2, 1, 1], "If the STATUS of this file is marked as DRAFT, the content defines proposed…"⟩,
  ⟨.clause [2, 1, 2], "Versions of this document having a STATUS of FINAL are considered to be in the…"⟩,
  ⟨.clause [2, 2], "Change Log"⟩,
  ⟨.clause [3, 1], "Use of the term MUST or SHALL indicates a required element"⟩,
  ⟨.clause [3, 2], "MUST NOT or SHALL NOT indicates an element is prohibited from use"⟩,
  ⟨.clause [3, 3], "SHOULD indicates a RECOMMENDED element"⟩,
  ⟨.clause [3, 4], "SHOULD NOT indicates an element NOT RECOMMENDED for use"⟩,
  ⟨.clause [3, 5], "MAY indicates an OPTIONAL element"⟩,
  ⟨.clause [4, 1], "What is a ZIP file"⟩,
  ⟨.clause [4, 1, 1], "ZIP files MAY be identified by the standard .ZIP file extension although use of…"⟩,
  ⟨.clause [4, 1, 2], "ZIP files SHOULD contain at least one file and MAY contain multiple files"⟩,
  ⟨.clause [4, 1, 3], "Data compression MAY be used to reduce the size of files placed into a ZIP…"⟩,
  ⟨.clause [4, 1, 4], "Data encryption MAY be used to protect files within a ZIP file"⟩,
  ⟨.clause [4, 1, 5], "Data integrity MUST be provided for each file using CRC32"⟩,
  ⟨.clause [4, 1, 6], "Additional data integrity MAY be included through the use of digital signatures"⟩,
  ⟨.clause [4, 1, 7], "Files MAY be placed within a ZIP file uncompressed or stored"⟩,
  ⟨.clause [4, 1, 8], "Each data file placed into a ZIP file MAY be compressed, stored, encrypted or…"⟩,
  ⟨.clause [4, 1, 9], "ZIP files MAY be streamed, split into segments (on fixed or on removable media)…"⟩,
  ⟨.clause [4, 1, 10], "Extensibility is provided for platform or application specific needs through…"⟩,
  ⟨.clause [4, 1, 11], "Common uses for ZIP MAY also include the use of manifest files"⟩,
  ⟨.clause [4, 1, 12], "ZIP files MAY be placed within other ZIP files"⟩,
  ⟨.clause [4, 2], "ZIP Metadata"⟩,
  ⟨.clause [4, 2, 1], "ZIP files are identified by metadata consisting of defined record types…"⟩,
  ⟨.clause [4, 3], "General Format of a .ZIP file"⟩,
  ⟨.clause [4, 3, 1], "A ZIP file MUST contain an \"end of central directory record\""⟩,
  ⟨.clause [4, 3, 2], "Each file placed into a ZIP file MUST be preceded by a \"local file header\"…"⟩,
  ⟨.clause [4, 3, 3], "Files MAY be stored in arbitrary order within a ZIP file"⟩,
  ⟨.clause [4, 3, 4], "Compression MUST NOT be applied to a \"local file header\", an \"encryption…"⟩,
  ⟨.clause [4, 3, 5], "File data MAY be followed by a \"data descriptor\" for the file"⟩,
  ⟨.clause [4, 3, 6], "Overall .ZIP file format"⟩,
  ⟨.clause [4, 3, 7], "Local file header"⟩,
  ⟨.clause [4, 3, 8], "File data"⟩,
  ⟨.clause [4, 3, 9], "Data descriptor"⟩,
  ⟨.clause [4, 3, 9, 1], "This descriptor MUST exist if bit 3 of the general purpose bit flag is set (see…"⟩,
  ⟨.clause [4, 3, 9, 2], "When compressing files, compressed and uncompressed sizes SHOULD be stored in…"⟩,
  ⟨.clause [4, 3, 9, 3], "Although not originally assigned a signature, the value 0x08074b50 has commonly…"⟩,
  ⟨.clause [4, 3, 9, 4], "When writing ZIP files, implementors SHOULD include the signature value marking…"⟩,
  ⟨.clause [4, 3, 9, 5], "An extensible data descriptor will be released in a future version of this…"⟩,
  ⟨.clause [4, 3, 9, 6], "When the Central Directory Encryption method is used, the data descriptor…"⟩,
  ⟨.clause [4, 3, 10], "Archive decryption header"⟩,
  ⟨.clause [4, 3, 10, 1], "The Archive Decryption Header is introduced in version 6.2 of the ZIP format…"⟩,
  ⟨.clause [4, 3, 10, 2], "The encrypted data segment SHALL consist of the Archive extra data record (if…"⟩,
  ⟨.clause [4, 3, 11], "Archive extra data record"⟩,
  ⟨.clause [4, 3, 11, 1], "The Archive Extra Data Record is introduced in version 6.2 of the ZIP format…"⟩,
  ⟨.clause [4, 3, 11, 2], "The size of this data record SHALL be included in the Size of the Central…"⟩,
  ⟨.clause [4, 3, 12], "Central directory structure"⟩,
  ⟨.clause [4, 3, 13], "Digital signature"⟩,
  ⟨.clause [4, 3, 14], "Zip64 end of central directory record"⟩,
  ⟨.clause [4, 3, 14, 1], "The value stored into the \"size of zip64 end of central directory record\"…"⟩,
  ⟨.clause [4, 3, 14, 2], "The above record structure defines Version 1 of the zip64 end of central…"⟩,
  ⟨.clause [4, 3, 14, 3], "Special purpose data MAY reside in the zip64 extensible data sector field…"⟩,
  ⟨.clause [4, 3, 14, 4], "Multiple special purpose data blocks MAY be present"⟩,
  ⟨.clause [4, 3, 15], "Zip64 end of central directory locator"⟩,
  ⟨.clause [4, 3, 16], "End of central directory record"⟩,
  ⟨.clause [4, 4], "Explanation of fields"⟩,
  ⟨.clause [4, 4, 1], "General notes on fields"⟩,
  ⟨.clause [4, 4, 1, 1], "All fields unless otherwise noted are unsigned and stored in Intel low-byte"⟩,
  ⟨.clause [4, 4, 1, 2], "String fields are not null terminated, since the length is given explicitly"⟩,
  ⟨.clause [4, 4, 1, 3], "The entries in the central directory MAY NOT necessarily be in the same order…"⟩,
  ⟨.clause [4, 4, 1, 4], "If one of the fields in the end of central directory record is too small to…"⟩,
  ⟨.clause [4, 4, 1, 5], "The end of central directory record and the Zip64 end of central directory…"⟩,
  ⟨.clause [4, 4, 2], "version made by (2 bytes)"⟩,
  ⟨.clause [4, 4, 2, 1], "The upper byte indicates the compatibility of the file attribute information"⟩,
  ⟨.clause [4, 4, 2, 2], "The current mappings are"⟩,
  ⟨.clause [4, 4, 2, 3], "The lower byte indicates the ZIP specification version (the version of this…"⟩,
  ⟨.clause [4, 4, 3], "version needed to extract (2 bytes)"⟩,
  ⟨.clause [4, 4, 3, 1], "The minimum supported ZIP specification version needed to extract the file…"⟩,
  ⟨.clause [4, 4, 3, 2], "Current minimum feature versions are as defined below"⟩,
  ⟨.clause [4, 4, 3, 3], "Notes on version needed to extract"⟩,
  ⟨.clause [4, 4, 4], "general purpose bit flag"⟩,
  ⟨.clause [4, 4, 5], "compression method"⟩,
  ⟨.clause [4, 4, 5, 1], "Methods 1-6 are legacy algorithms and are no longer recommended for use when…"⟩,
  ⟨.clause [4, 4, 6], "date and time fields"⟩,
  ⟨.clause [4, 4, 7], "CRC-32"⟩,
  ⟨.clause [4, 4, 8], "compressed size"⟩,
  ⟨.clause [4, 4, 9], "uncompressed size"⟩,
  ⟨.clause [4, 4, 10], "file name length"⟩,
  ⟨.clause [4, 4, 11], "extra field length"⟩,
  ⟨.clause [4, 4, 12], "file comment length"⟩,
  ⟨.clause [4, 4, 13], "disk number start"⟩,
  ⟨.clause [4, 4, 14], "internal file attributes"⟩,
  ⟨.clause [4, 4, 14, 1], "The lowest bit of this field indicates, if set, that the file is apparently an…"⟩,
  ⟨.clause [4, 4, 14, 2], "The 0x0002 bit of this field indicates, if set, that a 4 byte variable record…"⟩,
  ⟨.clause [4, 4, 15], "external file attributes"⟩,
  ⟨.clause [4, 4, 16], "relative offset of local header"⟩,
  ⟨.clause [4, 4, 17], "file name"⟩,
  ⟨.clause [4, 4, 17, 1], "The name of the file, with optional relative path"⟩,
  ⟨.clause [4, 4, 17, 2], "If using the Central Directory Encryption Feature and general purpose bit flag…"⟩,
  ⟨.clause [4, 4, 18], "file comment"⟩,
  ⟨.clause [4, 4, 19], "number of this disk"⟩,
  ⟨.clause [4, 4, 20], "number of the disk with the start of the central directory"⟩,
  ⟨.clause [4, 4, 21], "total number of entries in the central dir on this disk"⟩,
  ⟨.clause [4, 4, 22], "total number of entries in the central dir"⟩,
  ⟨.clause [4, 4, 23], "size of the central directory"⟩,
  ⟨.clause [4, 4, 24], "offset of start of central directory with respect to the starting disk number"⟩,
  ⟨.clause [4, 4, 25], "ZIP file comment length"⟩,
  ⟨.clause [4, 4, 26], "ZIP file comment"⟩,
  ⟨.clause [4, 4, 27], "zip64 extensible data sector (variable size)"⟩,
  ⟨.clause [4, 4, 28], "extra field"⟩,
  ⟨.clause [4, 5], "Extensible data fields"⟩,
  ⟨.clause [4, 5, 1], "In order to allow different programs and different types of information to be…"⟩,
  ⟨.clause [4, 5, 2], "The current Header ID mappings defined by PKWARE are"⟩,
  ⟨.clause [4, 5, 3], "Zip64 Extended Information Extra Field (0x0001)"⟩,
  ⟨.clause [4, 5, 4], "OS/2 Extra Field (0x0009)"⟩,
  ⟨.clause [4, 5, 5], "NTFS Extra Field (0x000a)"⟩,
  ⟨.clause [4, 5, 6], "OpenVMS Extra Field (0x000c)"⟩,
  ⟨.clause [4, 5, 6, 1], "There will be one or more attributes present, which will each be preceded by…"⟩,
  ⟨.clause [4, 5, 6, 2], "No word alignment or padding is performed"⟩,
  ⟨.clause [4, 5, 6, 3], "A well-behaved PKZIP/OpenVMS program SHOULD NOT produce more than one sub-block…"⟩,
  ⟨.clause [4, 5, 7], "UNIX Extra Field (0x000d)"⟩,
  ⟨.clause [4, 5, 8], "PATCH Descriptor Extra Field (0x000f)"⟩,
  ⟨.clause [4, 5, 8, 1], "The following is the layout of the Patch Descriptor \"extra\" block"⟩,
  ⟨.clause [4, 5, 8, 2], "Actions and reactions"⟩,
  ⟨.clause [4, 5, 8, 2, 1], "Actions"⟩,
  ⟨.clause [4, 5, 8, 2, 2], "Reactions"⟩,
  ⟨.clause [4, 5, 8, 3], "Patch support is provided by PKPatchMaker(tm) technology and is covered under…"⟩,
  ⟨.clause [4, 5, 9], "PKCS#7 Store for X.509 Certificates (0x0014)"⟩,
  ⟨.clause [4, 5, 10], "X.509 Certificate ID and Signature for individual file (0x0015)"⟩,
  ⟨.clause [4, 5, 11], "X.509 Certificate ID and Signature for central directory (0x0016)"⟩,
  ⟨.clause [4, 5, 12], "Strong Encryption Header (0x0017)"⟩,
  ⟨.clause [4, 5, 13], "Record Management Controls (0x0018)"⟩,
  ⟨.clause [4, 5, 14], "PKCS#7 Encryption Recipient Certificate List (0x0019)"⟩,
  ⟨.clause [4, 5, 15], "MVS Extra Field (0x0065)"⟩,
  ⟨.clause [4, 5, 16], "OS/400 Extra Field (0x0065)"⟩,
  ⟨.clause [4, 5, 17], "Policy Decryption Key Record Extra Field (0x0021)"⟩,
  ⟨.clause [4, 5, 18], "Key Provider Record Extra Field (0x0022)"⟩,
  ⟨.clause [4, 5, 19], "Policy Key Data Record Record Extra Field (0x0023)"⟩,
  ⟨.clause [4, 6], "Third Party Mappings"⟩,
  ⟨.clause [4, 6, 1], "Third party mappings commonly used are"⟩,
  ⟨.clause [4, 6, 2], "Third-party Extra Fields MUST include a Header ID using the format defined in…"⟩,
  ⟨.clause [4, 6, 3], "In case two different programs appropriate the same Header ID value, it is…"⟩,
  ⟨.clause [4, 6, 4], "ZipIt Macintosh Extra Field (long) (0x2605)"⟩,
  ⟨.clause [4, 6, 5], "ZipIt Macintosh Extra Field (short, for files) (0x2705)"⟩,
  ⟨.clause [4, 6, 6], "ZipIt Macintosh Extra Field (short, for directories) (0x2805)"⟩,
  ⟨.clause [4, 6, 7], "FWKCS MD5 Extra Field (0x4b46)"⟩,
  ⟨.clause [4, 6, 8], "Info-ZIP Unicode Comment Extra Field (0x6375)"⟩,
  ⟨.clause [4, 6, 9], "Info-ZIP Unicode Path Extra Field (0x7075)"⟩,
  ⟨.clause [4, 6, 10], "Microsoft Open Packaging Growth Hint (0xa220)"⟩,
  ⟨.clause [4, 6, 11], "Data Stream Alignment (Apache Commons-Compress) (0xa11e)"⟩,
  ⟨.clause [4, 7], "Manifest Files"⟩,
  ⟨.clause [4, 7, 1], "Applications using ZIP files MAY have a need for additional information that…"⟩,
  ⟨.clause [4, 7, 2], "A manifest file is a file created for the application process that requires…"⟩,
  ⟨.clause [4, 7, 3], "Manifest files MAY be compressed or encrypted as needed for application…"⟩,
  ⟨.clause [5, 1], "UnShrinking - Method 1"⟩,
  ⟨.clause [5, 1, 1], "Shrinking is a Dynamic Ziv-Lempel-Welch compression algorithm with partial…"⟩,
  ⟨.clause [5, 1, 2], "The code size is controlled by the compressor, and is not automatically…"⟩,
  ⟨.clause [5, 1, 3], "When the table becomes full, total clearing is not performed"⟩,
  ⟨.clause [5, 2], "Expanding - Methods 2-5"⟩,
  ⟨.clause [5, 2, 1], "The Reducing algorithm is actually a combination of two distinct algorithms"⟩,
  ⟨.clause [5, 2, 2], "The probabilistic compression stores an array of 'follower sets' S(j), for j=0…"⟩,
  ⟨.clause [5, 2, 3], "The sets are encoded as { N(j), S(j)[0],...,S(j)[N(j)-1] }, where N(j) is the…"⟩,
  ⟨.clause [5, 2, 4], "Immediately after the follower sets, is the compressed data stream"⟩,
  ⟨.clause [5, 2, 5], "The decompressed stream from above can then be expanded to re-create the…"⟩,
  ⟨.clause [5, 3], "Imploding - Method 6"⟩,
  ⟨.clause [5, 3, 1], "The Imploding algorithm is actually a combination of two distinct algorithms"⟩,
  ⟨.clause [5, 3, 2], "The Imploding algorithm can use a 4K or 8K sliding dictionary size"⟩,
  ⟨.clause [5, 3, 3], "The Shannon-Fano trees are stored at the start of the compressed file"⟩,
  ⟨.clause [5, 3, 4], "The Literal Shannon-Fano tree, if present is used to represent the entire ASCII…"⟩,
  ⟨.clause [5, 3, 5], "The Length Shannon-Fano tree is used to compress the Length part of the…"⟩,
  ⟨.clause [5, 3, 6], "The Distance Shannon-Fano tree is used to compress the Distance part of the…"⟩,
  ⟨.clause [5, 3, 7], "The Shannon-Fano trees themselves are stored in a compressed format"⟩,
  ⟨.clause [5, 3, 8], "The Shannon-Fano codes can be constructed from the bit lengths using the…"⟩,
  ⟨.clause [5, 3, 9], "The compressed data stream begins immediately after the compressed Shannon-Fano…"⟩,
  ⟨.clause [5, 4], "Tokenizing - Method 7"⟩,
  ⟨.clause [5, 4, 1], "This method is not used by PKZIP"⟩,
  ⟨.clause [5, 5], "Deflating - Method 8"⟩,
  ⟨.clause [5, 5, 1], "The Deflate algorithm is similar to the Implode algorithm using a sliding…"⟩,
  ⟨.clause [5, 5, 2], "The compressed data is stored in blocks with a header describing the block and…"⟩,
  ⟨.clause [5, 5, 3], "Expanding Huffman Codes"⟩,
  ⟨.clause [5, 5, 4], "The compressed data stream begins immediately after the compressed header data"⟩,
  ⟨.clause [5, 6], "Enhanced Deflating - Method 9"⟩,
  ⟨.clause [5, 6, 1], "The Enhanced Deflating algorithm is similar to Deflate but uses a sliding…"⟩,
  ⟨.clause [5, 7], "BZIP2 - Method 12"⟩,
  ⟨.clause [5, 7, 1], "BZIP2 is an open-source data compression algorithm developed by Julian Seward"⟩,
  ⟨.clause [5, 8], "LZMA - Method 14"⟩,
  ⟨.clause [5, 8, 1], "LZMA is a block-oriented, general purpose data compression algorithm developed…"⟩,
  ⟨.clause [5, 8, 2], "The Compression method field within the ZIP Local and Central Header records…"⟩,
  ⟨.clause [5, 8, 3], "The Version needed to extract field within the ZIP Local and Central Header…"⟩,
  ⟨.clause [5, 8, 4], "File data compressed using the LZMA algorithm MUST be placed immediately…"⟩,
  ⟨.clause [5, 8, 5], "The encryption header and data descriptor records MAY be conditionally present"⟩,
  ⟨.clause [5, 8, 6], "The LZMA Compressed Data will be stored as provided by the LZMA compression…"⟩,
  ⟨.clause [5, 8, 7], "The LZMA Properties Header will store specific data required to decompress the…"⟩,
  ⟨.clause [5, 8, 8], "Storage fields for the property information within the LZMA Properties Header…"⟩,
  ⟨.clause [5, 8, 8, 1], "LZMA Version Information - this field identifies which version of the LZMA SDK…"⟩,
  ⟨.clause [5, 8, 8, 2], "LZMA Properties Size - this field defines the size of the remaining property…"⟩,
  ⟨.clause [5, 8, 8, 3], "LZMA Property Data - this variable sized field records the required values for…"⟩,
  ⟨.clause [5, 8, 8, 4], "The layout of the \"LZMA Properties Data\" field is a function of the LZMA…"⟩,
  ⟨.clause [5, 8, 9], "Data compressed with method 14, LZMA, MAY include an end-of-stream (EOS) marker…"⟩,
  ⟨.clause [5, 9], "WavPack - Method 97"⟩,
  ⟨.clause [5, 9, 1], "Information describing the use of compression method 97 is provided by WinZIP…"⟩,
  ⟨.clause [5, 9, 2], "WavPack data for a file begins immediately after the end of the local header…"⟩,
  ⟨.clause [5, 9, 3], "An implementation note for storing digital sample data when using WavPack…"⟩,
  ⟨.clause [5, 10], "PPMd - Method 98"⟩,
  ⟨.clause [5, 10, 1], "PPMd is a data compression algorithm developed by Dmitry Shkarin which includes…"⟩,
  ⟨.clause [5, 10, 2], "Support for PPMd within the ZIP format currently is provided only for version…"⟩,
  ⟨.clause [5, 10, 3], "Parameters needed to control the algorithm are stored in the two bytes…"⟩,
  ⟨.clause [5, 10, 4], "An example for packing these fields into the 2 byte storage field is…"⟩,
  ⟨.clause [5, 11], "AE-x Encryption marker - Method 99"⟩,
  ⟨.clause [5, 12], "JPEG variant - Method 96"⟩,
  ⟨.clause [5, 13], "PKWARE Data Compression Library Imploding - Method 10"⟩,
  ⟨.clause [5, 14], "Reserved - Method 11"⟩,
  ⟨.clause [5, 15], "Reserved - Method 13"⟩,
  ⟨.clause [5, 16], "Reserved - Method 15"⟩,
  ⟨.clause [5, 17], "IBM z/OS CMPSC Compression - Method 16"⟩,
  ⟨.clause [5, 18], "Reserved - Method 17"⟩,
  ⟨.clause [5, 19], "IBM TERSE - Method 18"⟩,
  ⟨.clause [5, 20], "IBM LZ77 z Architecture - Method 19"⟩,
  ⟨.clause [6, 0, 1], "The following information discusses the decryption steps required to support…"⟩,
  ⟨.clause [6, 1], "Traditional PKWARE Decryption"⟩,
  ⟨.clause [6, 1, 1], "PKWARE is grateful to Mr"⟩,
  ⟨.clause [6, 1, 2], "PKZIP encrypts the compressed data stream"⟩,
  ⟨.clause [6, 1, 3], "Each encrypted file has an extra 12 bytes stored at the start of the data area…"⟩,
  ⟨.clause [6, 1, 4], "The following are the basic steps required to decrypt a file"⟩,
  ⟨.clause [6, 1, 5], "Initializing the encryption keys"⟩,
  ⟨.clause [6, 1, 6], "Decrypting the encryption header"⟩,
  ⟨.clause [6, 1, 7], "Decrypting the compressed data stream"⟩,
  ⟨.clause [7, 0, 1], "Portions of the Strong Encryption technology defined in this specification are…"⟩,
  ⟨.clause [7, 1], "Strong Encryption Overview"⟩,
  ⟨.clause [7, 1, 1], "Version 5.x of this specification introduced support for strong encryption…"⟩,
  ⟨.clause [7, 1, 2], "Password based encryption is the most common form of encryption people are…"⟩,
  ⟨.clause [7, 1, 3], "Most standard encryption algorithms are supported with this specification"⟩,
  ⟨.clause [7, 1, 4], "The algorithms introduced in Version 5.0 of this specification include"⟩,
  ⟨.clause [7, 1, 5], "Version 6.1 introduces encryption data changes to support interoperability with…"⟩,
  ⟨.clause [7, 1, 6], "Version 6.2 introduces support for encrypting metadata by compressing and…"⟩,
  ⟨.clause [7, 1, 7], "Version 6.3 introduces support for encrypting data using the Blowfish and…"⟩,
  ⟨.clause [7, 1, 8], "Central Directory Encryption provides greater protection against information…"⟩,
  ⟨.clause [7, 1, 9], "Extra Field records that MAY contain information about a file that SHOULD not…"⟩,
  ⟨.clause [7, 1, 10], "Older ZIP compatible programs not familiar with the Central Directory…"⟩,
  ⟨.clause [7, 1, 11], "This strong encryption feature specification is intended to provide for…"⟩,
  ⟨.clause [7, 1, 12], "Encryption provides data confidentiality and privacy"⟩,
  ⟨.clause [7, 2], "Single Password Symmetric Encryption Method"⟩,
  ⟨.clause [7, 2, 1], "The Single Password Symmetric Encryption Method using strong encryption…"⟩,
  ⟨.clause [7, 2, 2], "General Purpose Bits - Bits 0 and 6 of the General Purpose bit flag in both…"⟩,
  ⟨.clause [7, 2, 3], "Extra Field 0x0017 in central header only"⟩,
  ⟨.clause [7, 2, 3, 1], "Format - the data format identifier for this record"⟩,
  ⟨.clause [7, 2, 3, 2], "AlgId - integer identifier of the encryption algorithm from the following range"⟩,
  ⟨.clause [7, 2, 3, 3], "Bitlen - Explicit bit length of key"⟩,
  ⟨.clause [7, 2, 3, 4], "Flags - Processing flags needed for decryption"⟩,
  ⟨.clause [7, 2, 4], "Decryption header record preceding compressed file data"⟩,
  ⟨.clause [7, 2, 4, 1], "IVData - The size of the IV SHOULD match the algorithm block size"⟩,
  ⟨.clause [7, 2, 4, 2], "Format - the data format identifier for this record"⟩,
  ⟨.clause [7, 2, 4, 3], "AlgId - integer identifier of the encryption algorithm from the following range"⟩,
  ⟨.clause [7, 2, 4, 4], "Bitlen - Explicit bit length of key"⟩,
  ⟨.clause [7, 2, 4, 5], "Flags - Processing flags needed for decryption"⟩,
  ⟨.clause [7, 2, 4, 6], "ErdData - Encrypted random data is used to store random data that is used to…"⟩,
  ⟨.clause [7, 2, 4, 7], "Reserved1 - Reserved for certificate processing, if value is zero, then…"⟩,
  ⟨.clause [7, 2, 4, 8], "Reserved2 - If present, the size of the Reserved2 data structure is located by…"⟩,
  ⟨.clause [7, 2, 4, 9], "VSize - This size value will always include the 4 bytes of the VCRC32 data and…"⟩,
  ⟨.clause [7, 2, 4, 10], "VData - Random data for password validation"⟩,
  ⟨.clause [7, 2, 5], "Useful Tips"⟩,
  ⟨.clause [7, 2, 5, 1], "Strong Encryption is always applied to a file after compression"⟩,
  ⟨.clause [7, 2, 5, 2], "A pseudo-code representation of the encryption process is as follows"⟩,
  ⟨.clause [7, 2, 5, 3], "The function names and parameter requirements will depend on the choice of the…"⟩,
  ⟨.clause [7, 3], "Single Password - Central Directory Encryption"⟩,
  ⟨.clause [7, 3, 1], "Central Directory Encryption is achieved within the .ZIP format by encrypting…"⟩,
  ⟨.clause [7, 3, 2], "Local Header"⟩,
  ⟨.clause [7, 3, 3], "Encrypting the Central Directory"⟩,
  ⟨.clause [7, 3, 4], "New fields for Version 2"⟩,
  ⟨.clause [7, 3, 5], "When the Central Directory data is signed, the same hash algorithm used to hash…"⟩,
  ⟨.clause [7, 3, 6], "When the Central Directory is compressed and/or encrypted, the End of Central…"⟩,
  ⟨.clause [7, 3, 7], "Decrypting and decompressing the Central Directory is accomplished in the same…"⟩,
  ⟨.clause [7, 4], "Certificate Processing Method"⟩,
  ⟨.clause [7, 4, 1], "Certificate Flag Values"⟩,
  ⟨.clause [7, 4, 2], "CertData - Extra Field 0x0017 record certificate data structure"⟩,
  ⟨.clause [7, 4, 3], "Reserved1 - Certificate Decryption Header Reserved1 Data"⟩,
  ⟨.clause [7, 4, 4], "Reserved2 - Certificate Decryption Header Reserved2 Data Structures"⟩,
  ⟨.clause [7, 5], "Certificate Processing - Central Directory Encryption"⟩,
  ⟨.clause [7, 5, 1], "Central Directory Encryption using Digital Certificates will operate in a…"⟩,
  ⟨.clause [7, 5, 2], "The Archive Extra Data record will be used to store the following information"⟩,
  ⟨.clause [7, 5, 3], "When present, the size of the Archive Extra Data record will be included in the…"⟩,
  ⟨.clause [7, 6], "Certificate Processing Differences"⟩,
  ⟨.clause [7, 6, 1], "The Certificate Processing Method of encryption differs from the Single…"⟩,
  ⟨.clause [7, 6, 2], "This specification currently assumes digital certificates will follow the X.509…"⟩,
  ⟨.clause [7, 7], "OAEP Processing with Certificate-based Encryption"⟩,
  ⟨.clause [7, 7, 1], "OAEP stands for Optimal Asymmetric Encryption Padding"⟩,
  ⟨.clause [7, 7, 2], "Support for private keys stored on Smartcards or Tokens introduced a conflict…"⟩,
  ⟨.clause [7, 7, 3], "Versions of PKZIP available during initial development of the certificate…"⟩,
  ⟨.clause [7, 8], "Additional Encryption/Decryption Data Records"⟩,
  ⟨.clause [7, 8, 1], "Additional information MAY be stored within a ZIP file in support of the strong…"⟩,
  ⟨.clause [8, 1], "Spanned ZIP files"⟩,
  ⟨.clause [8, 1, 1], "Spanning is the process of segmenting a ZIP file across multiple removable media"⟩,
  ⟨.clause [8, 2], "Split ZIP files"⟩,
  ⟨.clause [8, 2, 1], "File splitting is a newer derivation of spanning"⟩,
  ⟨.clause [8, 3], "File Naming Differences"⟩,
  ⟨.clause [8, 3, 1], "A key difference between spanned and split ZIP files is that all pieces of a…"⟩,
  ⟨.clause [8, 3, 2], "Sequence ordering for DOS spanned archives uses the DOS volume label to…"⟩,
  ⟨.clause [8, 3, 3], "Split ZIP files are typically written to the same location and are subject to…"⟩,
  ⟨.clause [8, 3, 4], "The .ZIP extension is used on the last segment to support quickly reading the…"⟩,
  ⟨.clause [8, 4], "Spanned Self-extracting ZIP Files"⟩,
  ⟨.clause [8, 4, 1], "Spanned ZIP files MAY be PKSFX Self-extracting ZIP files"⟩,
  ⟨.clause [8, 5], "Capacities and Markers"⟩,
  ⟨.clause [8, 5, 1], "Capacities for split archives are as follows"⟩,
  ⟨.clause [8, 5, 2], "Segment sizes MAY be different however by convention, all segment sizes SHOULD…"⟩,
  ⟨.clause [8, 5, 3], "Spanned/Split archives created using PKZIP for Windows (V2.50 or greater)…"⟩,
  ⟨.clause [8, 5, 4], "A special spanning marker MAY also appear in spanned/split archives if the…"⟩,
  ⟨.clause [8, 5, 5], "The signature value 0x08074b50 is also used by some ZIP implementations as a…"⟩,
  ⟨.clause [9, 1], "In order for the .ZIP file format to remain a viable technology, this…"⟩,
  ⟨.clause [9, 2], "If your application requires new definitions to the extensible sections in this…"⟩,
  ⟨.clause [9, 3], "Periodic revisions to this specification will be published as DRAFT or as FINAL…"⟩,
  ⟨.clause [10, 1], "The Use or Implementation in a product of APPNOTE technological components…"⟩,
  ⟨.clause [10, 2], "Additional information regarding PKWARE proprietary technology is available at…"⟩
]

/-- Every numbered heading of the specification, in document order. -/
def headings : List Heading := headings0

end Ledger.Outline.Appnote
