import Ledger.Ref

/-!
The clause outline of ECMA-376 Part 2, 5th edition (2021): Open Packaging Conventions,
derived from the specification text by `tools/outline.py`. Regenerate rather than edit.
-/

namespace Ledger.Outline.Ecma376Part2

/-- Chapter titles by number. -/
def chapters : List (Nat × String) := [
  (1, "Scope"),
  (2, "Normative references"),
  (3, "Terms and definitions"),
  (4, "Conformance"),
  (5, "Overview"),
  (6, "Abstract package model"),
  (7, "Physical package model"),
  (8, "Core properties"),
  (9, "Thumbnails"),
  (10, "Digital signatures")
]

/-- Annex titles by letter. -/
def annexes : List (Char × String) := [
  ('A', "Preprocessing for generating relative references"),
  ('B', "Constraints and clarifications on the use of ZIP features"),
  ('C', "Schemas - W3C XML"),
  ('D', "Schemas - RELAX NG"),
  ('E', "Standard namespaces and media types"),
  ('F', "Physical package model design considerations"),
  ('G', "Differences between ECMA-376-2021 and ECMA-376:2006"),
  ('H', "Package example")
]

def headings0 : List Heading := [
  ⟨.clause [3, 1], "Basics"⟩,
  ⟨.clause [3, 2], "Abstract package model"⟩,
  ⟨.clause [3, 3], "Physical package model"⟩,
  ⟨.clause [3, 4], "Digital signature and thumbnail"⟩,
  ⟨.clause [3, 5], "Implementations"⟩,
  ⟨.clause [3, 6], "Core properties"⟩,
  ⟨.clause [6, 1], "General"⟩,
  ⟨.clause [6, 2], "Parts"⟩,
  ⟨.clause [6, 2, 1], "General"⟩,
  ⟨.clause [6, 2, 2], "Part names"⟩,
  ⟨.clause [6, 2, 2, 1], "General"⟩,
  ⟨.clause [6, 2, 2, 2], "Syntax"⟩,
  ⟨.clause [6, 2, 2, 3], "Part name equivalence and integrity in an abstract package"⟩,
  ⟨.clause [6, 2, 3], "Media types"⟩,
  ⟨.clause [6, 2, 4], "Growth hint"⟩,
  ⟨.clause [6, 2, 5], "XML usage"⟩,
  ⟨.clause [6, 3], "Part addressing"⟩,
  ⟨.clause [6, 3, 1], "General"⟩,
  ⟨.clause [6, 3, 2], "Pack scheme"⟩,
  ⟨.clause [6, 3, 3], "Resolving a pack IRI to a resource"⟩,
  ⟨.clause [6, 3, 4], "Composing a pack IRI"⟩,
  ⟨.clause [6, 3, 5], "Equivalence"⟩,
  ⟨.clause [6, 4], "Resolving relative references"⟩,
  ⟨.clause [6, 4, 1], "General"⟩,
  ⟨.clause [6, 4, 2], "Base IRIs"⟩,
  ⟨.clause [6, 4, 3], "Examples"⟩,
  ⟨.clause [6, 4, 3, 1], "General"⟩,
  ⟨.clause [6, 4, 3, 2], "Leading slash: \"/b/bar.xml\""⟩,
  ⟨.clause [6, 4, 3, 3], "No leading slash: \"bar.xml\""⟩,
  ⟨.clause [6, 4, 3, 4], "Dot segment: \"./bar.xml\""⟩,
  ⟨.clause [6, 4, 3, 5], "Dot segment: \"../bar.xml\""⟩,
  ⟨.clause [6, 5], "Relationships"⟩,
  ⟨.clause [6, 5, 1], "General"⟩,
  ⟨.clause [6, 5, 2], "Relationships part"⟩,
  ⟨.clause [6, 5, 2, 1], "Relationships part"⟩,
  ⟨.clause [6, 5, 2, 2], "Package Relationships part"⟩,
  ⟨.clause [6, 5, 2, 3], "Part Relationships part"⟩,
  ⟨.clause [6, 5, 3], "Relationship markup"⟩,
  ⟨.clause [6, 5, 3, 1], "General"⟩,
  ⟨.clause [6, 5, 3, 2], "Support for versioning and extensibility"⟩,
  ⟨.clause [6, 5, 3, 3], "Relationships element"⟩,
  ⟨.clause [6, 5, 3, 4], "Relationship element"⟩,
  ⟨.clause [6, 5, 4], "Examples"⟩,
  ⟨.clause [6, 5, 4, 1], "Relationships part associated with the entire package"⟩,
  ⟨.clause [6, 5, 4, 2], "Relationships part associated with a part"⟩,
  ⟨.clause [6, 5, 4, 3], "Relationships parts related to digital signature markup"⟩,
  ⟨.clause [6, 5, 4, 4], "Relationships targeting external resources"⟩,
  ⟨.clause [6, 5, 4, 5], "Multiple relationships that have the same target"⟩,
  ⟨.clause [7, 1], "General"⟩,
  ⟨.clause [7, 2], "Physical mapping guidelines"⟩,
  ⟨.clause [7, 2, 1], "Using features of physical formats"⟩,
  ⟨.clause [7, 2, 2], "Mapped components"⟩,
  ⟨.clause [7, 2, 3], "Mapping media types to parts"⟩,
  ⟨.clause [7, 2, 3, 1], "General"⟩,
  ⟨.clause [7, 2, 3, 2], "Media Types stream markup"⟩,
  ⟨.clause [7, 2, 3, 2, 1], "General"⟩,
  ⟨.clause [7, 2, 3, 2, 2], "Support for versioning and extensibility"⟩,
  ⟨.clause [7, 2, 3, 2, 3], "Types element"⟩,
  ⟨.clause [7, 2, 3, 2, 4], "Default element"⟩,
  ⟨.clause [7, 2, 3, 2, 5], "Override element"⟩,
  ⟨.clause [7, 2, 3, 3], "Media Types stream markup example"⟩,
  ⟨.clause [7, 2, 3, 4], "Setting a part media type in the Media Types stream"⟩,
  ⟨.clause [7, 2, 3, 5], "Determining a part media type from the Media Types stream"⟩,
  ⟨.clause [7, 2, 4], "Interleaving"⟩,
  ⟨.clause [7, 2, 5], "Mapping part names to physical package item names"⟩,
  ⟨.clause [7, 2, 5, 1], "General"⟩,
  ⟨.clause [7, 2, 5, 2], "Logical item names"⟩,
  ⟨.clause [7, 2, 5, 3], "Mapping part names to logical item names"⟩,
  ⟨.clause [7, 2, 5, 4], "Mapping logical item names and physical package item names"⟩,
  ⟨.clause [7, 2, 5, 5], "Mapping logical item names to part names"⟩,
  ⟨.clause [7, 3], "Mapping to a ZIP file"⟩,
  ⟨.clause [7, 3, 1], "General"⟩,
  ⟨.clause [7, 3, 2], "Mapping part data"⟩,
  ⟨.clause [7, 3, 3], "ZIP item names"⟩,
  ⟨.clause [7, 3, 4], "Mapping logical item names to ZIP item names"⟩,
  ⟨.clause [7, 3, 5], "Mapping ZIP item names to logical item names"⟩,
  ⟨.clause [7, 3, 6], "ZIP package limitations"⟩,
  ⟨.clause [7, 3, 7], "Mapping the Media Types stream"⟩,
  ⟨.clause [7, 3, 8], "Mapping the growth hint"⟩,
  ⟨.clause [8, 1], "General"⟩,
  ⟨.clause [8, 2], "Core Properties part"⟩,
  ⟨.clause [8, 3], "Core properties markup"⟩,
  ⟨.clause [8, 3, 1], "General"⟩,
  ⟨.clause [8, 3, 2], "Support for versioning and extensibility"⟩,
  ⟨.clause [8, 3, 3], "coreProperties element"⟩,
  ⟨.clause [8, 3, 4], "Core property elements"⟩,
  ⟨.clause [8, 3, 4, 1], "General"⟩,
  ⟨.clause [8, 3, 4, 2], "Core property elements as defined by ISO 15836-1"⟩,
  ⟨.clause [8, 3, 4, 3], "Core property elements as defined by ISO 15836-2"⟩,
  ⟨.clause [8, 3, 4, 4], "Core property elements defined in this document"⟩,
  ⟨.clause [8, 3, 4, 4, 1], "category element"⟩,
  ⟨.clause [8, 3, 4, 4, 2], "contentStatus element"⟩,
  ⟨.clause [8, 3, 4, 4, 3], "keywords element"⟩,
  ⟨.clause [8, 3, 4, 4, 4], "value element"⟩,
  ⟨.clause [8, 3, 4, 4, 5], "lastModifiedBy element"⟩,
  ⟨.clause [8, 3, 4, 4, 6], "lastPrinted element"⟩,
  ⟨.clause [8, 3, 4, 4, 7], "revision element"⟩,
  ⟨.clause [8, 3, 4, 4, 8], "version element"⟩,
  ⟨.clause [10, 1], "General"⟩,
  ⟨.clause [10, 2], "Overview of OPC-specific restrictions and extensions to “XML-Signature Syntax and Processing”"⟩,
  ⟨.clause [10, 3], "Choosing content to sign"⟩,
  ⟨.clause [10, 4], "Digital signature parts"⟩,
  ⟨.clause [10, 4, 1], "General"⟩,
  ⟨.clause [10, 4, 2], "Digital Signature Origin part"⟩,
  ⟨.clause [10, 4, 3], "Digital Signature XML Signature part"⟩,
  ⟨.clause [10, 4, 4], "Digital Signature Certificate part"⟩,
  ⟨.clause [10, 5], "Digital signature markup"⟩,
  ⟨.clause [10, 5, 1], "General"⟩,
  ⟨.clause [10, 5, 2], "Support for versioning and extensibility"⟩,
  ⟨.clause [10, 5, 3], "Signature element"⟩,
  ⟨.clause [10, 5, 4], "SignedInfo element"⟩,
  ⟨.clause [10, 5, 5], "CanonicalizationMethod element"⟩,
  ⟨.clause [10, 5, 6], "SignatureMethod element"⟩,
  ⟨.clause [10, 5, 7], "Reference element"⟩,
  ⟨.clause [10, 5, 7, 1], "General"⟩,
  ⟨.clause [10, 5, 7, 2], "Reference element as a child of a SignedInfo element"⟩,
  ⟨.clause [10, 5, 7, 3], "Reference element as a child of a Manifest element"⟩,
  ⟨.clause [10, 5, 8], "Transform element"⟩,
  ⟨.clause [10, 5, 8, 1], "General"⟩,
  ⟨.clause [10, 5, 8, 2], "Transform element representing a Relationships transform"⟩,
  ⟨.clause [10, 5, 9], "RelationshipReference element"⟩,
  ⟨.clause [10, 5, 10], "RelationshipsGroupReference element"⟩,
  ⟨.clause [10, 5, 11], "DigestMethod element"⟩,
  ⟨.clause [10, 5, 12], "Object element"⟩,
  ⟨.clause [10, 5, 12, 1], "General"⟩,
  ⟨.clause [10, 5, 12, 2], "OPC-specific Object element"⟩,
  ⟨.clause [10, 5, 12, 3], "Application-Defined Object element"⟩,
  ⟨.clause [10, 5, 13], "Manifest element"⟩,
  ⟨.clause [10, 5, 14], "SignatureProperty element"⟩,
  ⟨.clause [10, 5, 15], "SignatureTime element"⟩,
  ⟨.clause [10, 5, 16], "Format element"⟩,
  ⟨.clause [10, 5, 17], "Value element"⟩,
  ⟨.clause [10, 5, 18], "XPath element"⟩,
  ⟨.clause [10, 6], "Relationships transform algorithm"⟩,
  ⟨.clause [10, 7], "Digital signature example"⟩,
  ⟨.clause [10, 8], "Generating signatures"⟩,
  ⟨.clause [10, 9], "Validating signatures"⟩,
  ⟨.annex 'B' [1], "General"⟩,
  ⟨.annex 'B' [2], "Archive file header consistency"⟩,
  ⟨.annex 'B' [3], "Data descriptor signature"⟩,
  ⟨.annex 'B' [4], "Requirements on package implementers"⟩,
  ⟨.annex 'C' [1], "General"⟩,
  ⟨.annex 'C' [2], "Media Types stream"⟩,
  ⟨.annex 'C' [3], "Core Properties part"⟩,
  ⟨.annex 'C' [4], "Digital signature XML signature markup"⟩,
  ⟨.annex 'C' [5], "Relationships part"⟩,
  ⟨.annex 'D' [1], "General"⟩,
  ⟨.annex 'D' [2], "Media Types stream"⟩,
  ⟨.annex 'D' [3], "Core Properties part"⟩,
  ⟨.annex 'D' [4], "Digital signature XML signature markup"⟩,
  ⟨.annex 'D' [5], "Relationships part"⟩,
  ⟨.annex 'D' [6], "Additional resources"⟩,
  ⟨.annex 'D' [6, 1], "XML"⟩,
  ⟨.annex 'D' [6, 2], "XML digital signature core"⟩,
  ⟨.annex 'F' [1], "General"⟩,
  ⟨.annex 'F' [2], "Access styles"⟩,
  ⟨.annex 'F' [2, 1], "General"⟩,
  ⟨.annex 'F' [2, 2], "Direct access consumption"⟩,
  ⟨.annex 'F' [2, 3], "Streaming consumption"⟩,
  ⟨.annex 'F' [2, 4], "Streaming creation"⟩,
  ⟨.annex 'F' [2, 5], "Simultaneous creation and consumption"⟩,
  ⟨.annex 'F' [3], "Layout styles"⟩,
  ⟨.annex 'F' [3, 1], "General"⟩,
  ⟨.annex 'F' [3, 2], "Simple ordering"⟩,
  ⟨.annex 'F' [3, 3], "Interleaved ordering"⟩,
  ⟨.annex 'F' [4], "Communication styles"⟩,
  ⟨.annex 'F' [4, 1], "General"⟩,
  ⟨.annex 'F' [4, 2], "Sequential delivery"⟩,
  ⟨.annex 'F' [4, 3], "Random access"⟩,
  ⟨.annex 'G' [1], "General"⟩,
  ⟨.annex 'G' [2], "XML elements"⟩,
  ⟨.annex 'G' [3], "XML attributes"⟩,
  ⟨.annex 'G' [4], "XML enumeration values"⟩,
  ⟨.annex 'G' [5], "XML simple types"⟩,
  ⟨.annex 'G' [6], "Part names"⟩,
  ⟨.annex 'H' [1], "General"⟩,
  ⟨.annex 'H' [2], "Abstract package"⟩,
  ⟨.annex 'H' [3], "Physical package"⟩
]

/-- Every numbered heading of the specification, in document order. -/
def headings : List Heading := headings0

end Ledger.Outline.Ecma376Part2
