import Ledger.Ref

/-!
The clause outline of [MS-EMF]: Enhanced Metafile Format,
derived from the specification text by `tools/outline.py`. Regenerate rather than edit.
-/

namespace Ledger.Outline.MsEmf

/-- Chapter titles by number. -/
def chapters : List (Nat × String) := [
  (1, "Introduction"),
  (2, "Structures"),
  (3, "Structure Examples"),
  (4, "Security Considerations"),
  (5, "Appendix A: Product Behavior"),
  (6, "Change Tracking"),
  (7, "Index")
]

/-- Annex titles by letter. -/
def annexes : List (Char × String) := [

]

def headings0 : List Heading := [
  ⟨.clause [1, 1], "Glossary"⟩,
  ⟨.clause [1, 2], "References"⟩,
  ⟨.clause [1, 2, 1], "Normative References"⟩,
  ⟨.clause [1, 2, 2], "Informative References"⟩,
  ⟨.clause [1, 3], "Overview"⟩,
  ⟨.clause [1, 3, 1], "Metafile Structure"⟩,
  ⟨.clause [1, 3, 2], "Graphics Objects"⟩,
  ⟨.clause [1, 3, 3], "Byte Ordering"⟩,
  ⟨.clause [1, 4], "Relationship to Protocols and Other Structures"⟩,
  ⟨.clause [1, 5], "Applicability Statement"⟩,
  ⟨.clause [1, 6], "Versioning and Localization"⟩,
  ⟨.clause [1, 7], "Vendor-Extensible Fields"⟩,
  ⟨.clause [2, 1], "EMF Enumerations"⟩,
  ⟨.clause [2, 1, 1], "RecordType Enumeration"⟩,
  ⟨.clause [2, 1, 2], "ArcDirection Enumeration"⟩,
  ⟨.clause [2, 1, 3], "ArmStyle Enumeration"⟩,
  ⟨.clause [2, 1, 4], "BackgroundMode Enumeration"⟩,
  ⟨.clause [2, 1, 5], "ColorAdjustment Enumeration"⟩,
  ⟨.clause [2, 1, 6], "ColorMatchToTarget Enumeration"⟩,
  ⟨.clause [2, 1, 7], "ColorSpace Enumeration"⟩,
  ⟨.clause [2, 1, 8], "Contrast Enumeration"⟩,
  ⟨.clause [2, 1, 9], "DIBColors Enumeration"⟩,
  ⟨.clause [2, 1, 10], "EmrComment Enumeration"⟩,
  ⟨.clause [2, 1, 11], "ExtTextOutOptions Enumeration"⟩,
  ⟨.clause [2, 1, 12], "FamilyType Enumeration"⟩,
  ⟨.clause [2, 1, 13], "FloodFill Enumeration"⟩,
  ⟨.clause [2, 1, 14], "FormatSignature Enumeration"⟩,
  ⟨.clause [2, 1, 15], "GradientFill Enumeration"⟩,
  ⟨.clause [2, 1, 16], "GraphicsMode Enumeration"⟩,
  ⟨.clause [2, 1, 17], "HatchStyle Enumeration"⟩,
  ⟨.clause [2, 1, 18], "ICMMode Enumeration"⟩,
  ⟨.clause [2, 1, 19], "Illuminant Enumeration"⟩,
  ⟨.clause [2, 1, 20], "Letterform Enumeration"⟩,
  ⟨.clause [2, 1, 21], "MapMode Enumeration"⟩,
  ⟨.clause [2, 1, 22], "MetafileVersion Enumeration"⟩,
  ⟨.clause [2, 1, 23], "MidLine Enumeration"⟩,
  ⟨.clause [2, 1, 24], "ModifyWorldTransformMode Enumeration"⟩,
  ⟨.clause [2, 1, 25], "PenStyle Enumeration"⟩,
  ⟨.clause [2, 1, 26], "Point Enumeration"⟩,
  ⟨.clause [2, 1, 27], "PolygonFillMode Enumeration"⟩,
  ⟨.clause [2, 1, 28], "Proportion Enumeration"⟩,
  ⟨.clause [2, 1, 29], "RegionMode Enumeration"⟩,
  ⟨.clause [2, 1, 30], "SerifType Enumeration"⟩,
  ⟨.clause [2, 1, 31], "StockObject Enumeration"⟩,
  ⟨.clause [2, 1, 32], "StretchMode Enumeration"⟩,
  ⟨.clause [2, 1, 33], "StrokeVariation Enumeration"⟩,
  ⟨.clause [2, 1, 34], "Weight Enumeration"⟩,
  ⟨.clause [2, 1, 35], "XHeight Enumeration"⟩,
  ⟨.clause [2, 2], "EMF Objects"⟩,
  ⟨.clause [2, 2, 1], "BitFIX28_4 Object"⟩,
  ⟨.clause [2, 2, 2], "ColorAdjustment Object"⟩,
  ⟨.clause [2, 2, 3], "DesignVector Object"⟩,
  ⟨.clause [2, 2, 4], "EmrFormat Object"⟩,
  ⟨.clause [2, 2, 5], "EmrText Object"⟩,
  ⟨.clause [2, 2, 6], "EpsData Object"⟩,
  ⟨.clause [2, 2, 7], "GradientRectangle Object"⟩,
  ⟨.clause [2, 2, 8], "GradientTriangle Object"⟩,
  ⟨.clause [2, 2, 9], "Header Object"⟩,
  ⟨.clause [2, 2, 10], "HeaderExtension1 Object"⟩,
  ⟨.clause [2, 2, 11], "HeaderExtension2 Object"⟩,
  ⟨.clause [2, 2, 12], "LogBrushEx Object"⟩,
  ⟨.clause [2, 2, 13], "LogFont Object"⟩,
  ⟨.clause [2, 2, 14], "LogFontEx Object"⟩,
  ⟨.clause [2, 2, 15], "LogFontExDv Object"⟩,
  ⟨.clause [2, 2, 16], "LogFontPanose Object"⟩,
  ⟨.clause [2, 2, 17], "LogPalette Object"⟩,
  ⟨.clause [2, 2, 18], "LogPaletteEntry Object"⟩,
  ⟨.clause [2, 2, 19], "LogPen Object"⟩,
  ⟨.clause [2, 2, 20], "LogPenEx Object"⟩,
  ⟨.clause [2, 2, 21], "Panose Object"⟩,
  ⟨.clause [2, 2, 22], "PixelFormatDescriptor Object"⟩,
  ⟨.clause [2, 2, 23], "Point28_4 Object"⟩,
  ⟨.clause [2, 2, 24], "RegionData Object"⟩,
  ⟨.clause [2, 2, 25], "RegionDataHeader Object"⟩,
  ⟨.clause [2, 2, 26], "TriVertex Object"⟩,
  ⟨.clause [2, 2, 27], "UniversalFontId Object"⟩,
  ⟨.clause [2, 2, 28], "XForm Object"⟩,
  ⟨.clause [2, 3], "EMF Records"⟩,
  ⟨.clause [2, 3, 1], "Bitmap Record Types"⟩,
  ⟨.clause [2, 3, 1, 1], "EMR_ALPHABLEND Record"⟩,
  ⟨.clause [2, 3, 1, 2], "EMR_BITBLT Record"⟩,
  ⟨.clause [2, 3, 1, 3], "EMR_MASKBLT Record"⟩,
  ⟨.clause [2, 3, 1, 4], "EMR_PLGBLT Record"⟩,
  ⟨.clause [2, 3, 1, 5], "EMR_SETDIBITSTODEVICE Record"⟩,
  ⟨.clause [2, 3, 1, 6], "EMR_STRETCHBLT Record"⟩,
  ⟨.clause [2, 3, 1, 7], "EMR_STRETCHDIBITS Record"⟩,
  ⟨.clause [2, 3, 1, 8], "EMR_TRANSPARENTBLT Record"⟩,
  ⟨.clause [2, 3, 2], "Clipping Record Types"⟩,
  ⟨.clause [2, 3, 2, 1], "EMR_EXCLUDECLIPRECT Record"⟩,
  ⟨.clause [2, 3, 2, 2], "EMR_EXTSELECTCLIPRGN Record"⟩,
  ⟨.clause [2, 3, 2, 3], "EMR_INTERSECTCLIPRECT Record"⟩,
  ⟨.clause [2, 3, 2, 4], "EMR_OFFSETCLIPRGN Record"⟩,
  ⟨.clause [2, 3, 2, 5], "EMR_SELECTCLIPPATH Record"⟩,
  ⟨.clause [2, 3, 3], "Comment Record Types"⟩,
  ⟨.clause [2, 3, 3, 1], "EMR_COMMENT Record"⟩,
  ⟨.clause [2, 3, 3, 2], "EMR_COMMENT_EMFPLUS Record"⟩,
  ⟨.clause [2, 3, 3, 3], "EMR_COMMENT_EMFSPOOL Record"⟩,
  ⟨.clause [2, 3, 3, 4], "EMR_COMMENT_PUBLIC Record Types"⟩,
  ⟨.clause [2, 3, 3, 4, 1], "EMR_COMMENT_BEGINGROUP Record"⟩,
  ⟨.clause [2, 3, 3, 4, 2], "EMR_COMMENT_ENDGROUP Record"⟩,
  ⟨.clause [2, 3, 3, 4, 3], "EMR_COMMENT_MULTIFORMATS Record"⟩,
  ⟨.clause [2, 3, 3, 4, 4], "EMR_COMMENT_WINDOWS_METAFILE Record"⟩,
  ⟨.clause [2, 3, 4], "Control Record Types"⟩,
  ⟨.clause [2, 3, 4, 1], "EMR_EOF Record"⟩,
  ⟨.clause [2, 3, 4, 2], "EMR_HEADER Record Types"⟩,
  ⟨.clause [2, 3, 4, 2, 1], "EmfMetafileHeader Record"⟩,
  ⟨.clause [2, 3, 4, 2, 2], "EmfMetafileHeaderExtension1 Record"⟩,
  ⟨.clause [2, 3, 4, 2, 3], "EmfMetafileHeaderExtension2 Record"⟩,
  ⟨.clause [2, 3, 5], "Drawing Record Types"⟩,
  ⟨.clause [2, 3, 5, 1], "EMR_ANGLEARC Record"⟩,
  ⟨.clause [2, 3, 5, 2], "EMR_ARC Record"⟩,
  ⟨.clause [2, 3, 5, 3], "EMR_ARCTO Record"⟩,
  ⟨.clause [2, 3, 5, 4], "EMR_CHORD Record"⟩,
  ⟨.clause [2, 3, 5, 5], "EMR_ELLIPSE Record"⟩,
  ⟨.clause [2, 3, 5, 6], "EMR_EXTFLOODFILL Record"⟩,
  ⟨.clause [2, 3, 5, 7], "EMR_EXTTEXTOUTA Record"⟩,
  ⟨.clause [2, 3, 5, 8], "EMR_EXTTEXTOUTW Record"⟩,
  ⟨.clause [2, 3, 5, 9], "EMR_FILLPATH Record"⟩,
  ⟨.clause [2, 3, 5, 10], "EMR_FILLRGN Record"⟩,
  ⟨.clause [2, 3, 5, 11], "EMR_FRAMERGN Record"⟩,
  ⟨.clause [2, 3, 5, 12], "EMR_GRADIENTFILL Record"⟩,
  ⟨.clause [2, 3, 5, 13], "EMR_LINETO Record"⟩,
  ⟨.clause [2, 3, 5, 14], "EMR_PAINTRGN Record"⟩,
  ⟨.clause [2, 3, 5, 15], "EMR_PIE Record"⟩,
  ⟨.clause [2, 3, 5, 16], "EMR_POLYBEZIER Record"⟩,
  ⟨.clause [2, 3, 5, 17], "EMR_POLYBEZIER16 Record"⟩,
  ⟨.clause [2, 3, 5, 18], "EMR_POLYBEZIERTO Record"⟩,
  ⟨.clause [2, 3, 5, 19], "EMR_POLYBEZIERTO16 Record"⟩,
  ⟨.clause [2, 3, 5, 20], "EMR_POLYDRAW Record"⟩,
  ⟨.clause [2, 3, 5, 21], "EMR_POLYDRAW16 Record"⟩,
  ⟨.clause [2, 3, 5, 22], "EMR_POLYGON Record"⟩,
  ⟨.clause [2, 3, 5, 23], "EMR_POLYGON16 Record"⟩,
  ⟨.clause [2, 3, 5, 24], "EMR_POLYLINE Record"⟩,
  ⟨.clause [2, 3, 5, 25], "EMR_POLYLINE16 Record"⟩,
  ⟨.clause [2, 3, 5, 26], "EMR_POLYLINETO Record"⟩,
  ⟨.clause [2, 3, 5, 27], "EMR_POLYLINETO16 Record"⟩,
  ⟨.clause [2, 3, 5, 28], "EMR_POLYPOLYGON Record"⟩,
  ⟨.clause [2, 3, 5, 29], "EMR_POLYPOLYGON16 Record"⟩,
  ⟨.clause [2, 3, 5, 30], "EMR_POLYPOLYLINE Record"⟩,
  ⟨.clause [2, 3, 5, 31], "EMR_POLYPOLYLINE16 Record"⟩,
  ⟨.clause [2, 3, 5, 32], "EMR_POLYTEXTOUTA Record"⟩,
  ⟨.clause [2, 3, 5, 33], "EMR_POLYTEXTOUTW Record"⟩,
  ⟨.clause [2, 3, 5, 34], "EMR_RECTANGLE Record"⟩,
  ⟨.clause [2, 3, 5, 35], "EMR_ROUNDRECT Record"⟩,
  ⟨.clause [2, 3, 5, 36], "EMR_SETPIXELV Record"⟩,
  ⟨.clause [2, 3, 5, 37], "EMR_SMALLTEXTOUT Record"⟩,
  ⟨.clause [2, 3, 5, 38], "EMR_STROKEANDFILLPATH Record"⟩,
  ⟨.clause [2, 3, 5, 39], "EMR_STROKEPATH Record"⟩,
  ⟨.clause [2, 3, 6], "Escape Record Types"⟩,
  ⟨.clause [2, 3, 6, 1], "EMR_DRAWESCAPE Record"⟩,
  ⟨.clause [2, 3, 6, 2], "EMR_EXTESCAPE Record"⟩,
  ⟨.clause [2, 3, 6, 3], "EMR_NAMEDESCAPE Record"⟩,
  ⟨.clause [2, 3, 7], "Object Creation Record Types"⟩,
  ⟨.clause [2, 3, 7, 1], "EMR_CREATEBRUSHINDIRECT Record"⟩,
  ⟨.clause [2, 3, 7, 2], "EMR_CREATECOLORSPACE Record"⟩,
  ⟨.clause [2, 3, 7, 3], "EMR_CREATECOLORSPACEW Record"⟩,
  ⟨.clause [2, 3, 7, 4], "EMR_CREATEDIBPATTERNBRUSHPT Record"⟩,
  ⟨.clause [2, 3, 7, 5], "EMR_CREATEMONOBRUSH Record"⟩,
  ⟨.clause [2, 3, 7, 6], "EMR_CREATEPALETTE Record"⟩,
  ⟨.clause [2, 3, 7, 7], "EMR_CREATEPEN Record"⟩,
  ⟨.clause [2, 3, 7, 8], "EMR_EXTCREATEFONTINDIRECTW Record"⟩,
  ⟨.clause [2, 3, 7, 9], "EMR_EXTCREATEPEN Record"⟩,
  ⟨.clause [2, 3, 8], "Object Manipulation Record Types"⟩,
  ⟨.clause [2, 3, 8, 1], "EMR_COLORCORRECTPALETTE Record"⟩,
  ⟨.clause [2, 3, 8, 2], "EMR_DELETECOLORSPACE Record"⟩,
  ⟨.clause [2, 3, 8, 3], "EMR_DELETEOBJECT Record"⟩,
  ⟨.clause [2, 3, 8, 4], "EMR_RESIZEPALETTE Record"⟩,
  ⟨.clause [2, 3, 8, 5], "EMR_SELECTOBJECT Record"⟩,
  ⟨.clause [2, 3, 8, 6], "EMR_SELECTPALETTE Record"⟩,
  ⟨.clause [2, 3, 8, 7], "EMR_SETCOLORSPACE Record"⟩,
  ⟨.clause [2, 3, 8, 8], "EMR_SETPALETTEENTRIES Record"⟩,
  ⟨.clause [2, 3, 9], "OpenGL Record Types"⟩,
  ⟨.clause [2, 3, 9, 1], "EMR_GLSBOUNDEDRECORD Record"⟩,
  ⟨.clause [2, 3, 9, 2], "EMR_GLSRECORD Record"⟩,
  ⟨.clause [2, 3, 10], "Path Bracket Record Types"⟩,
  ⟨.clause [2, 3, 11], "State Record Types"⟩,
  ⟨.clause [2, 3, 11, 1], "EMR_COLORMATCHTOTARGETW Record"⟩,
  ⟨.clause [2, 3, 11, 2], "EMR_FORCEUFIMAPPING Record"⟩,
  ⟨.clause [2, 3, 11, 3], "EMR_INVERTRGN Record"⟩,
  ⟨.clause [2, 3, 11, 4], "EMR_MOVETOEX Record"⟩,
  ⟨.clause [2, 3, 11, 5], "EMR_PIXELFORMAT Record"⟩,
  ⟨.clause [2, 3, 11, 6], "EMR_RESTOREDC Record"⟩,
  ⟨.clause [2, 3, 11, 7], "EMR_SCALEVIEWPORTEXTEX Record"⟩,
  ⟨.clause [2, 3, 11, 8], "EMR_SCALEWINDOWEXTEX Record"⟩,
  ⟨.clause [2, 3, 11, 9], "EMR_SETARCDIRECTION Record"⟩,
  ⟨.clause [2, 3, 11, 10], "EMR_SETBKCOLOR Record"⟩,
  ⟨.clause [2, 3, 11, 11], "EMR_SETBKMODE Record"⟩,
  ⟨.clause [2, 3, 11, 12], "EMR_SETBRUSHORGEX Record"⟩,
  ⟨.clause [2, 3, 11, 13], "EMR_SETCOLORADJUSTMENT Record"⟩,
  ⟨.clause [2, 3, 11, 14], "EMR_SETICMMODE Record"⟩,
  ⟨.clause [2, 3, 11, 15], "EMR_SETICMPROFILEA Record"⟩,
  ⟨.clause [2, 3, 11, 16], "EMR_SETICMPROFILEW Record"⟩,
  ⟨.clause [2, 3, 11, 17], "EMR_SETLAYOUT Record"⟩,
  ⟨.clause [2, 3, 11, 18], "EMR_SETLINKEDUFIS Record"⟩,
  ⟨.clause [2, 3, 11, 19], "EMR_SETMAPMODE Record"⟩,
  ⟨.clause [2, 3, 11, 20], "EMR_SETMAPPERFLAGS Record"⟩,
  ⟨.clause [2, 3, 11, 21], "EMR_SETMITERLIMIT Record"⟩,
  ⟨.clause [2, 3, 11, 22], "EMR_SETPOLYFILLMODE Record"⟩,
  ⟨.clause [2, 3, 11, 23], "EMR_SETROP2 Record"⟩,
  ⟨.clause [2, 3, 11, 24], "EMR_SETSTRETCHBLTMODE Record"⟩,
  ⟨.clause [2, 3, 11, 25], "EMR_SETTEXTALIGN Record"⟩,
  ⟨.clause [2, 3, 11, 26], "EMR_SETTEXTCOLOR Record"⟩,
  ⟨.clause [2, 3, 11, 27], "EMR_SETTEXTJUSTIFICATION Record"⟩,
  ⟨.clause [2, 3, 11, 28], "EMR_SETVIEWPORTEXTEX Record"⟩,
  ⟨.clause [2, 3, 11, 29], "EMR_SETVIEWPORTORGEX Record"⟩,
  ⟨.clause [2, 3, 11, 30], "EMR_SETWINDOWEXTEX Record"⟩,
  ⟨.clause [2, 3, 11, 31], "EMR_SETWINDOWORGEX Record"⟩,
  ⟨.clause [2, 3, 12], "Transform Record Types"⟩,
  ⟨.clause [2, 3, 12, 1], "EMR_MODIFYWORLDTRANSFORM Record"⟩,
  ⟨.clause [2, 3, 12, 2], "EMR_SETWORLDTRANSFORM Record"⟩,
  ⟨.clause [3, 1], "EMF Metafile Playback"⟩,
  ⟨.clause [3, 1, 1], "Abstract Data Model"⟩,
  ⟨.clause [3, 1, 1, 1], "EMF Object Table"⟩,
  ⟨.clause [3, 1, 1, 2], "Graphics Environment"⟩,
  ⟨.clause [3, 1, 1, 2, 1], "Regions"⟩,
  ⟨.clause [3, 1, 1, 2, 2], "Colors"⟩,
  ⟨.clause [3, 1, 1, 2, 3], "Text"⟩,
  ⟨.clause [3, 1, 1, 2, 4], "Drawing"⟩,
  ⟨.clause [3, 1, 2], "Byte Ordering"⟩,
  ⟨.clause [3, 2], "EMF Metafile Example"⟩,
  ⟨.clause [3, 2, 1], "EMR_HEADER Example"⟩,
  ⟨.clause [3, 2, 2], "EMR_CREATEBRUSHINDIRECT Example"⟩,
  ⟨.clause [3, 2, 3], "EMR_SELECTOBJECT Example 1"⟩,
  ⟨.clause [3, 2, 4], "EMR_BITBLT Example 1"⟩,
  ⟨.clause [3, 2, 5], "EMR_SELECTOBJECT Example 2"⟩,
  ⟨.clause [3, 2, 6], "EMR_BITBLT Example 2"⟩,
  ⟨.clause [3, 2, 7], "EMR_SETBKMODE Example"⟩,
  ⟨.clause [3, 2, 8], "EMR_EXTCREATEFONTINDIRECTW Example 1"⟩,
  ⟨.clause [3, 2, 9], "EMR_SELECTOBJECT Example 3"⟩,
  ⟨.clause [3, 2, 10], "EMR_EXTTEXTOUTW Example"⟩,
  ⟨.clause [3, 2, 11], "EMR_EXTCREATEFONTINDIRECTW Example 2"⟩,
  ⟨.clause [3, 2, 12], "EMR_SELECTOBJECT Example 4"⟩,
  ⟨.clause [3, 2, 13], "EMR_EXTCREATEFONTINDIRECTW Example 3"⟩,
  ⟨.clause [3, 2, 14], "EMR_SELECTOBJECT Example 5"⟩,
  ⟨.clause [3, 2, 15], "EMR_DELETEOBJECT Example 1"⟩,
  ⟨.clause [3, 2, 16], "EMR_EXTCREATEFONTINDIRECTW Example 4"⟩,
  ⟨.clause [3, 2, 17], "EMR_SELECTOBJECT Example 6"⟩,
  ⟨.clause [3, 2, 18], "EMR_SELECTOBJECT Example 7"⟩,
  ⟨.clause [3, 2, 19], "EMR_DELETEOBJECT Example 2"⟩,
  ⟨.clause [3, 2, 20], "EMR_DELETEOBJECT Example 3"⟩,
  ⟨.clause [3, 2, 21], "EMR_SELECTOBJECT Example 8"⟩,
  ⟨.clause [3, 2, 22], "EMR_EOF Example"⟩
]

/-- Every numbered heading of the specification, in document order. -/
def headings : List Heading := headings0

end Ledger.Outline.MsEmf
