import Ledger.Ref

/-!
The clause outline of [MS-OSHARED]: Office Common Data Types and Objects Structures,
derived from the specification text by `tools/outline.py`. Regenerate rather than edit.
-/

namespace Ledger.Outline.MsOshared

/-- Chapter titles by number. -/
def chapters : List (Nat × String) := [
  (1, "Introduction"),
  (2, "Structures"),
  (3, "Structure Examples"),
  (4, "Security Considerations"),
  (5, "Appendix A: Product Behavior"),
  (6, "Change Tracking"),
  (7, "Index")
]

/-- Annex titles by letter. -/
def annexes : List (Char × String) := [

]

def headings0 : List Heading := [
  ⟨.clause [1, 1], "Glossary"⟩,
  ⟨.clause [1, 2], "References"⟩,
  ⟨.clause [1, 2, 1], "Normative References"⟩,
  ⟨.clause [1, 2, 2], "Informative References"⟩,
  ⟨.clause [1, 3], "Structure Overview (Synopsis)"⟩,
  ⟨.clause [1, 3, 1], "Toolbar Customization"⟩,
  ⟨.clause [1, 3, 2], "Property Set Storage"⟩,
  ⟨.clause [1, 3, 3], "RefEdit Control"⟩,
  ⟨.clause [1, 3, 4], "Visual Basic for Applications Digital Signature"⟩,
  ⟨.clause [1, 3, 5], "Byte Ordering"⟩,
  ⟨.clause [1, 4], "Relationship to Protocols and Other Structures"⟩,
  ⟨.clause [1, 4, 1], "Toolbar Customization"⟩,
  ⟨.clause [1, 4, 2], "Property Set Storage"⟩,
  ⟨.clause [1, 4, 3], "Visual Basic for Applications Digital Signature"⟩,
  ⟨.clause [1, 5], "Applicability Statement"⟩,
  ⟨.clause [1, 5, 1], "Toolbar Customization"⟩,
  ⟨.clause [1, 5, 2], "Property Set Storage"⟩,
  ⟨.clause [1, 5, 3], "Visual Basic for Applications Digital Signature"⟩,
  ⟨.clause [1, 6], "Versioning and Localization"⟩,
  ⟨.clause [1, 6, 1], "Toolbar Customization"⟩,
  ⟨.clause [1, 6, 2], "Property Set Storage"⟩,
  ⟨.clause [1, 6, 3], "Visual Basic for Applications Digital Signature"⟩,
  ⟨.clause [1, 7], "Vendor-Extensible Fields"⟩,
  ⟨.clause [1, 7, 1], "Toolbar Customization"⟩,
  ⟨.clause [1, 7, 2], "Property Set Storage"⟩,
  ⟨.clause [1, 7, 3], "Visual Basic for Applications Digital Signature"⟩,
  ⟨.clause [2, 1], "Common ABNF Definitions"⟩,
  ⟨.clause [2, 2], "Data Types"⟩,
  ⟨.clause [2, 2, 1], "Common Data Types"⟩,
  ⟨.clause [2, 2, 1, 1], "ObjectUpdateEnum"⟩,
  ⟨.clause [2, 2, 1, 2], "DataViewAspectEnum"⟩,
  ⟨.clause [2, 2, 1, 3], "MSONFC"⟩,
  ⟨.clause [2, 2, 1, 4], "WebScreenSizeEnum"⟩,
  ⟨.clause [2, 2, 1, 5], "FilePointer"⟩,
  ⟨.clause [2, 2, 1, 6], "FixedPoint"⟩,
  ⟨.clause [2, 3], "Common Objects"⟩,
  ⟨.clause [2, 3, 1], "Toolbar Customization"⟩,
  ⟨.clause [2, 3, 1, 1], "TBCBitmap"⟩,
  ⟨.clause [2, 3, 1, 2], "BITMAPINFOHEADER"⟩,
  ⟨.clause [2, 3, 1, 3], "RGBQuad"⟩,
  ⟨.clause [2, 3, 1, 4], "WString"⟩,
  ⟨.clause [2, 3, 1, 5], "SRECT"⟩,
  ⟨.clause [2, 3, 1, 6], "TB"⟩,
  ⟨.clause [2, 3, 1, 7], "TBTRFlags"⟩,
  ⟨.clause [2, 3, 1, 8], "TBFlags"⟩,
  ⟨.clause [2, 3, 1, 9], "TBVisualData"⟩,
  ⟨.clause [2, 3, 1, 10], "TBCHeader"⟩,
  ⟨.clause [2, 3, 1, 11], "TBCFlags"⟩,
  ⟨.clause [2, 3, 1, 12], "TBCSFlags"⟩,
  ⟨.clause [2, 3, 1, 13], "TBCData"⟩,
  ⟨.clause [2, 3, 1, 14], "TBCGeneralInfo"⟩,
  ⟨.clause [2, 3, 1, 15], "TBCGIFlags"⟩,
  ⟨.clause [2, 3, 1, 16], "TBCExtraInfo"⟩,
  ⟨.clause [2, 3, 1, 17], "TBCBSpecific"⟩,
  ⟨.clause [2, 3, 1, 18], "TBCBSFlags"⟩,
  ⟨.clause [2, 3, 1, 19], "TBCComboDropdownSpecific"⟩,
  ⟨.clause [2, 3, 1, 20], "TBCCDData"⟩,
  ⟨.clause [2, 3, 1, 21], "TBCMenuSpecific"⟩,
  ⟨.clause [2, 3, 2], "Visual Basic for Applications Digital Signature Storage"⟩,
  ⟨.clause [2, 3, 2, 1], "DigSigInfoSerialized"⟩,
  ⟨.clause [2, 3, 2, 2], "DigSigBlob"⟩,
  ⟨.clause [2, 3, 2, 3], "WordSigBlob"⟩,
  ⟨.clause [2, 3, 2, 4], "VBA Digital Signature"⟩,
  ⟨.clause [2, 3, 2, 4, 1], "SignedData Constraints"⟩,
  ⟨.clause [2, 3, 2, 4, 2], "SignerInfo Constraints"⟩,
  ⟨.clause [2, 3, 2, 4, 3], "SignedData contentInfo Structures"⟩,
  ⟨.clause [2, 3, 2, 4, 3, 1], "SpcIndirectDataContent"⟩,
  ⟨.clause [2, 3, 2, 4, 3, 2], "SpcIndirectDataContentV2"⟩,
  ⟨.clause [2, 3, 2, 4, 4], "SignerInfo authenticatedAttributes Structures"⟩,
  ⟨.clause [2, 3, 2, 4, 4, 1], "SpcStatementType"⟩,
  ⟨.clause [2, 3, 2, 4, 4, 2], "SpcSpOpusInfo"⟩,
  ⟨.clause [2, 3, 2, 4, 4, 3], "SpcString"⟩,
  ⟨.clause [2, 3, 2, 4, 4, 4], "SpcLink"⟩,
  ⟨.clause [2, 3, 2, 4, 5], "SignerInfo unauthenticatedAttributes"⟩,
  ⟨.clause [2, 3, 2, 4, 6], "VBA Digital Signature Verification"⟩,
  ⟨.clause [2, 3, 2, 4, 6, 1], "Certificate Processing"⟩,
  ⟨.clause [2, 3, 2, 4, 6, 2], "Timestamp Processing"⟩,
  ⟨.clause [2, 3, 2, 5], "Serialized Certificate Store Structure"⟩,
  ⟨.clause [2, 3, 2, 5, 1], "SerializedCertificateEntry"⟩,
  ⟨.clause [2, 3, 2, 5, 2], "EndElementMarkerEntry"⟩,
  ⟨.clause [2, 3, 2, 5, 3], "SerializedPropertyEntry"⟩,
  ⟨.clause [2, 3, 2, 5, 4], "CertStoreCertificateGroup"⟩,
  ⟨.clause [2, 3, 2, 5, 5], "VBASigSerializedCertStore"⟩,
  ⟨.clause [2, 3, 3], "Property Set Storage"⟩,
  ⟨.clause [2, 3, 3, 1], "Property Types"⟩,
  ⟨.clause [2, 3, 3, 1, 1], "PropertySetSystemIdentifier"⟩,
  ⟨.clause [2, 3, 3, 1, 2], "VtThumbnailValue"⟩,
  ⟨.clause [2, 3, 3, 1, 3], "VtThumbnail"⟩,
  ⟨.clause [2, 3, 3, 1, 4], "Lpstr"⟩,
  ⟨.clause [2, 3, 3, 1, 5], "UnalignedLpstr"⟩,
  ⟨.clause [2, 3, 3, 1, 6], "Lpwstr"⟩,
  ⟨.clause [2, 3, 3, 1, 7], "VtVecLpwstrValue"⟩,
  ⟨.clause [2, 3, 3, 1, 8], "VtVecLpwstr"⟩,
  ⟨.clause [2, 3, 3, 1, 9], "VtVecUnalignedLpstrValue"⟩,
  ⟨.clause [2, 3, 3, 1, 10], "VtVecUnalignedLpstr"⟩,
  ⟨.clause [2, 3, 3, 1, 11], "VtString"⟩,
  ⟨.clause [2, 3, 3, 1, 12], "VtUnalignedString"⟩,
  ⟨.clause [2, 3, 3, 1, 13], "VtHeadingPair"⟩,
  ⟨.clause [2, 3, 3, 1, 14], "VtVecHeadingPairValue"⟩,
  ⟨.clause [2, 3, 3, 1, 15], "VtVecHeadingPair"⟩,
  ⟨.clause [2, 3, 3, 1, 16], "VtDigSigValue"⟩,
  ⟨.clause [2, 3, 3, 1, 17], "VtDigSig"⟩,
  ⟨.clause [2, 3, 3, 1, 18], "VtHyperlink"⟩,
  ⟨.clause [2, 3, 3, 1, 19], "VecVtHyperlink"⟩,
  ⟨.clause [2, 3, 3, 1, 20], "VtHyperlinkValue"⟩,
  ⟨.clause [2, 3, 3, 1, 21], "VtHyperlinks"⟩,
  ⟨.clause [2, 3, 3, 2], "OLE Property Sets"⟩,
  ⟨.clause [2, 3, 3, 2, 1], "Summary Information Property Set"⟩,
  ⟨.clause [2, 3, 3, 2, 1, 1], "PIDSI"⟩,
  ⟨.clause [2, 3, 3, 2, 2], "Document Summary Information Property Set"⟩,
  ⟨.clause [2, 3, 3, 2, 2, 1], "PIDDSI"⟩,
  ⟨.clause [2, 3, 3, 2, 3], "User Defined Property Set"⟩,
  ⟨.clause [2, 3, 3, 2, 3, 1], "User Defined Property Set Constraints"⟩,
  ⟨.clause [2, 3, 3, 2, 3, 1, 1], "Required Properties"⟩,
  ⟨.clause [2, 3, 3, 2, 3, 1, 2], "Supported Types"⟩,
  ⟨.clause [2, 3, 3, 2, 3, 2], "Reserved Properties"⟩,
  ⟨.clause [2, 3, 3, 2, 3, 3], "Linked Properties"⟩,
  ⟨.clause [2, 3, 4], "SmartTag Objects"⟩,
  ⟨.clause [2, 3, 4, 1], "PropertyBagStore"⟩,
  ⟨.clause [2, 3, 4, 2], "FactoidType"⟩,
  ⟨.clause [2, 3, 4, 3], "PropertyBag"⟩,
  ⟨.clause [2, 3, 4, 4], "Property"⟩,
  ⟨.clause [2, 3, 4, 5], "PBString"⟩,
  ⟨.clause [2, 3, 5], "RefEdit Control"⟩,
  ⟨.clause [2, 3, 6], "Custom XML Data Storage"⟩,
  ⟨.clause [2, 3, 6, 1], "Custom XML Data Storage Item"⟩,
  ⟨.clause [2, 3, 6, 1, 1], "Custom Property Editor"⟩,
  ⟨.clause [2, 3, 6, 1, 1, 1], "XMLNamespace"⟩,
  ⟨.clause [2, 3, 6, 1, 1, 2], "XSNLocation"⟩,
  ⟨.clause [2, 3, 6, 1, 1, 3], "showOnOpen"⟩,
  ⟨.clause [2, 3, 6, 1, 1, 4], "defaultPropertyEditorNamespace"⟩,
  ⟨.clause [2, 3, 6, 1, 1, 5], "customPropertyEditor"⟩,
  ⟨.clause [2, 3, 6, 1, 1, 6], "customPropertyEditors"⟩,
  ⟨.clause [2, 3, 6, 1, 2], "Custom Xsn"⟩,
  ⟨.clause [2, 3, 6, 1, 2, 1], "ST_TrueFalse"⟩,
  ⟨.clause [2, 3, 6, 1, 2, 2], "xsnLocation"⟩,
  ⟨.clause [2, 3, 6, 1, 2, 3], "cached"⟩,
  ⟨.clause [2, 3, 6, 1, 2, 4], "openByDefault"⟩,
  ⟨.clause [2, 3, 6, 1, 2, 5], "xsnScope"⟩,
  ⟨.clause [2, 3, 6, 1, 2, 6], "customXsn"⟩,
  ⟨.clause [2, 3, 6, 1, 3], "Schema for Content Type"⟩,
  ⟨.clause [2, 3, 6, 1, 3, 1], "ContentTypeId"⟩,
  ⟨.clause [2, 3, 6, 1, 3, 2], "IntNonNegative"⟩,
  ⟨.clause [2, 3, 6, 1, 3, 3], "UniqueIdentifierWithoutBraces"⟩,
  ⟨.clause [2, 3, 6, 1, 3, 4], "UniqueIdentifierWithoutBracesOrEmpty"⟩,
  ⟨.clause [2, 3, 6, 1, 3, 5], "DummyContentTypeElement"⟩,
  ⟨.clause [2, 3, 6, 1, 3, 6], "schema"⟩,
  ⟨.clause [2, 3, 6, 1, 3, 7], "contentTypeSchema"⟩,
  ⟨.clause [2, 3, 6, 1, 4], "Cover Page Properties"⟩,
  ⟨.clause [2, 3, 6, 1, 4, 1], "ST_PublishDate"⟩,
  ⟨.clause [2, 3, 6, 1, 4, 2], "PublishDate"⟩,
  ⟨.clause [2, 3, 6, 1, 4, 3], "Abstract"⟩,
  ⟨.clause [2, 3, 6, 1, 4, 4], "CompanyAddress"⟩,
  ⟨.clause [2, 3, 6, 1, 4, 5], "CompanyPhone"⟩,
  ⟨.clause [2, 3, 6, 1, 4, 6], "CompanyFax"⟩,
  ⟨.clause [2, 3, 6, 1, 4, 7], "CompanyEmail"⟩,
  ⟨.clause [2, 3, 6, 1, 4, 8], "CoverPageProperties"⟩,
  ⟨.clause [2, 3, 6, 1, 5], "Long Properties"⟩,
  ⟨.clause [2, 3, 6, 1, 5, 1], "LongProp"⟩,
  ⟨.clause [2, 3, 6, 1, 5, 2], "LongProperties"⟩,
  ⟨.clause [2, 3, 6, 2], "Custom XML Data Storage Properties"⟩,
  ⟨.clause [2, 3, 6, 2, 1], "ST_Guid"⟩,
  ⟨.clause [2, 3, 6, 2, 2], "schemaRef"⟩,
  ⟨.clause [2, 3, 6, 2, 3], "schemaRefs"⟩,
  ⟨.clause [2, 3, 6, 2, 4], "dataStoreItem"⟩,
  ⟨.clause [2, 3, 7], "Hyperlinks"⟩,
  ⟨.clause [2, 3, 7, 1], "Hyperlink Object"⟩,
  ⟨.clause [2, 3, 7, 2], "HyperlinkMoniker"⟩,
  ⟨.clause [2, 3, 7, 3], "CompositeMoniker"⟩,
  ⟨.clause [2, 3, 7, 4], "AntiMoniker"⟩,
  ⟨.clause [2, 3, 7, 5], "ItemMoniker"⟩,
  ⟨.clause [2, 3, 7, 6], "URLMoniker"⟩,
  ⟨.clause [2, 3, 7, 7], "URICreateFlags"⟩,
  ⟨.clause [2, 3, 7, 8], "FileMoniker"⟩,
  ⟨.clause [2, 3, 7, 9], "HyperlinkString"⟩,
  ⟨.clause [2, 3, 8], "MsoEnvelope"⟩,
  ⟨.clause [2, 3, 8, 1], "MsoEnvelopeCLSID"⟩,
  ⟨.clause [2, 3, 8, 2], "MsoEnvelope"⟩,
  ⟨.clause [2, 3, 8, 3], "EnvRecipientCollection"⟩,
  ⟨.clause [2, 3, 8, 4], "EnvRecipientProperties"⟩,
  ⟨.clause [2, 3, 8, 5], "EnvRecipientProperty"⟩,
  ⟨.clause [2, 3, 8, 6], "EnvRecipientPropertyBlob"⟩,
  ⟨.clause [2, 3, 8, 7], "PT_LONG"⟩,
  ⟨.clause [2, 3, 8, 8], "PT_NULL"⟩,
  ⟨.clause [2, 3, 8, 9], "PT_BOOLEAN"⟩,
  ⟨.clause [2, 3, 8, 10], "PT_SYSTIME"⟩,
  ⟨.clause [2, 3, 8, 11], "PT_ERROR"⟩,
  ⟨.clause [2, 3, 8, 12], "PT_STRING8"⟩,
  ⟨.clause [2, 3, 8, 13], "PT_UNICODE"⟩,
  ⟨.clause [2, 3, 8, 14], "PT_BINARY"⟩,
  ⟨.clause [2, 3, 8, 15], "PT_MV_STRING8"⟩,
  ⟨.clause [2, 3, 8, 16], "PT_MV_BINARY"⟩,
  ⟨.clause [2, 3, 8, 17], "EnvAttachmentCollection"⟩,
  ⟨.clause [2, 3, 8, 18], "EnvAttachment"⟩,
  ⟨.clause [2, 3, 8, 19], "IntroText"⟩,
  ⟨.clause [2, 3, 9], "Document Signature Serialized Certificate Store Structure"⟩,
  ⟨.clause [2, 3, 9, 1], "DocSigSerializedCertStore"⟩,
  ⟨.clause [2, 4], "Common Algorithms"⟩,
  ⟨.clause [2, 4, 1], "Unicode String to Unsigned Integer Hash"⟩,
  ⟨.clause [2, 4, 2], "Hyperlink Hash"⟩,
  ⟨.clause [2, 4, 3], "MsoCrc32Compute"⟩,
  ⟨.clause [2, 4, 3, 1], "Caching Algorithm"⟩,
  ⟨.clause [2, 4, 3, 2], "CRC Computation"⟩,
  ⟨.clause [2, 4, 4], "Date/Time Format from Format Index"⟩,
  ⟨.clause [2, 4, 4, 1], "Format Indices"⟩,
  ⟨.clause [2, 4, 4, 2], "Base Format Strings"⟩,
  ⟨.clause [2, 4, 4, 3], "Retrieve Format"⟩,
  ⟨.clause [2, 4, 4, 3, 1], "Chinese Formats"⟩,
  ⟨.clause [2, 4, 4, 3, 2], "Hindi Formats"⟩,
  ⟨.clause [2, 4, 4, 3, 3], "Japanese Formats"⟩,
  ⟨.clause [2, 4, 4, 3, 4], "Korean Formats"⟩,
  ⟨.clause [2, 4, 4, 3, 5], "Taiwanese Formats"⟩,
  ⟨.clause [2, 4, 4, 3, 6], "Thai Formats"⟩,
  ⟨.clause [2, 4, 4, 3, 7], "Yi Formats"⟩,
  ⟨.clause [2, 4, 4, 3, 8], "Formats for all other Locales"⟩,
  ⟨.clause [2, 4, 4, 4], "Apply Format Exceptions"⟩,
  ⟨.clause [2, 4, 4, 4, 1], "Bokmål (Norwegian)"⟩,
  ⟨.clause [2, 4, 4, 4, 2], "Czech"⟩,
  ⟨.clause [2, 4, 4, 4, 3], "Danish"⟩,
  ⟨.clause [2, 4, 4, 4, 4], "Dutch"⟩,
  ⟨.clause [2, 4, 4, 4, 5], "Finnish"⟩,
  ⟨.clause [2, 4, 4, 4, 6], "French Canadian"⟩,
  ⟨.clause [2, 4, 4, 4, 7], "German"⟩,
  ⟨.clause [2, 4, 4, 4, 8], "Hungarian"⟩,
  ⟨.clause [2, 4, 4, 4, 9], "Italian"⟩,
  ⟨.clause [2, 4, 4, 4, 10], "Japanese"⟩,
  ⟨.clause [2, 4, 4, 4, 11], "Kazakh"⟩,
  ⟨.clause [2, 4, 4, 4, 12], "Khmer"⟩,
  ⟨.clause [2, 4, 4, 4, 13], "Korean"⟩,
  ⟨.clause [2, 4, 4, 4, 14], "Lao"⟩,
  ⟨.clause [2, 4, 4, 4, 15], "Lithuanian"⟩,
  ⟨.clause [2, 4, 4, 4, 16], "Polish"⟩,
  ⟨.clause [2, 4, 4, 4, 17], "Portuguese"⟩,
  ⟨.clause [2, 4, 4, 4, 18], "Russian"⟩,
  ⟨.clause [2, 4, 4, 4, 19], "Spanish"⟩,
  ⟨.clause [2, 4, 4, 4, 20], "Swedish"⟩,
  ⟨.clause [2, 4, 4, 4, 21], "Tibetan"⟩,
  ⟨.clause [2, 4, 4, 4, 22], "Uzbek Cyrillic"⟩,
  ⟨.clause [2, 4, 4, 4, 23], "Vietnamese"⟩,
  ⟨.clause [2, 4, 4, 4, 24], "Bhutanese"⟩,
  ⟨.clause [3, 1], "Toolbar Customization Examples"⟩,
  ⟨.clause [3, 1, 1], "Toolbar Control Example"⟩,
  ⟨.clause [3, 1, 2], "Toolbar Delta Example"⟩,
  ⟨.clause [3, 2], "Document Summary Information Examples"⟩,
  ⟨.clause [3, 2, 1], "Document Summary Information Stream Overview"⟩,
  ⟨.clause [3, 2, 2], "Document Summary Information Property Set Overview"⟩,
  ⟨.clause [3, 2, 2, 1], "CodePage Property Example"⟩,
  ⟨.clause [3, 2, 2, 2], "Category Property Example"⟩,
  ⟨.clause [3, 2, 2, 3], "LineCount Property Example"⟩,
  ⟨.clause [3, 2, 2, 4], "LinksDirty Property Example"⟩,
  ⟨.clause [3, 2, 2, 5], "DocumentParts Property Example"⟩,
  ⟨.clause [3, 2, 2, 6], "HeadingPairs Property Example"⟩,
  ⟨.clause [3, 2, 3], "User Defined Property Set Overview"⟩,
  ⟨.clause [3, 2, 3, 1], "Dictionary Property Example"⟩,
  ⟨.clause [3, 2, 3, 2], "LinkBase Property Example"⟩,
  ⟨.clause [3, 2, 3, 3], "Hyperlinks Property Example"⟩,
  ⟨.clause [3, 2, 3, 3, 1], "LinkElement-1 Example"⟩,
  ⟨.clause [3, 2, 3, 3, 2], "LinkElement-2 Example"⟩,
  ⟨.clause [3, 2, 3, 3, 3], "LinkElement-3 Example"⟩,
  ⟨.clause [3, 2, 3, 3, 4], "LinkElement-4 Example"⟩,
  ⟨.clause [3, 2, 3, 3, 5], "LinkElement-5 Example"⟩,
  ⟨.clause [3, 2, 3, 3, 6], "LinkElement-6 Example"⟩,
  ⟨.clause [3, 2, 3, 4], "Linked Property Example"⟩,
  ⟨.clause [3, 3], "SmartTag Examples"⟩,
  ⟨.clause [3, 4], "Visual Basic for Applications Digital Signature Example Structures"⟩,
  ⟨.clause [4, 1], "Toolbar Customization"⟩,
  ⟨.clause [4, 2], "Property Set Storage"⟩,
  ⟨.clause [4, 3], "Visual Basic for Applications Digital Signature"⟩
]

/-- Every numbered heading of the specification, in document order. -/
def headings : List Heading := headings0

end Ledger.Outline.MsOshared
