import Ledger.Ref

/-!
The clause outline of [MS-WMF]: Windows Metafile Format,
derived from the specification text by `tools/outline.py`. Regenerate rather than edit.
-/

namespace Ledger.Outline.MsWmf

/-- Chapter titles by number. -/
def chapters : List (Nat × String) := [
  (1, "Introduction"),
  (2, "Structures"),
  (3, "Structure Examples"),
  (4, "Security Considerations"),
  (5, "Appendix A: Product Behavior"),
  (6, "Change Tracking"),
  (7, "Index")
]

/-- Annex titles by letter. -/
def annexes : List (Char × String) := [

]

def headings0 : List Heading := [
  ⟨.clause [1, 1], "Glossary"⟩,
  ⟨.clause [1, 2], "References"⟩,
  ⟨.clause [1, 2, 1], "Normative References"⟩,
  ⟨.clause [1, 2, 2], "Informative References"⟩,
  ⟨.clause [1, 3], "Overview"⟩,
  ⟨.clause [1, 3, 1], "Metafile Structure"⟩,
  ⟨.clause [1, 3, 2], "Graphics Objects"⟩,
  ⟨.clause [1, 3, 3], "Byte Ordering"⟩,
  ⟨.clause [1, 4], "Relationship to Protocols and Other Structures"⟩,
  ⟨.clause [1, 5], "Applicability Statement"⟩,
  ⟨.clause [1, 6], "Versioning and Localization"⟩,
  ⟨.clause [1, 7], "Vendor-Extensible Fields"⟩,
  ⟨.clause [2, 1], "WMF Constants"⟩,
  ⟨.clause [2, 1, 1], "WMF Enumerations"⟩,
  ⟨.clause [2, 1, 1, 1], "RecordType Enumeration"⟩,
  ⟨.clause [2, 1, 1, 2], "BinaryRasterOperation Enumeration"⟩,
  ⟨.clause [2, 1, 1, 3], "BitCount Enumeration"⟩,
  ⟨.clause [2, 1, 1, 4], "BrushStyle Enumeration"⟩,
  ⟨.clause [2, 1, 1, 5], "CharacterSet Enumeration"⟩,
  ⟨.clause [2, 1, 1, 6], "ColorUsage Enumeration"⟩,
  ⟨.clause [2, 1, 1, 7], "Compression Enumeration"⟩,
  ⟨.clause [2, 1, 1, 8], "FamilyFont Enumeration"⟩,
  ⟨.clause [2, 1, 1, 9], "FloodFill Enumeration"⟩,
  ⟨.clause [2, 1, 1, 10], "FontQuality Enumeration"⟩,
  ⟨.clause [2, 1, 1, 11], "GamutMappingIntent Enumeration"⟩,
  ⟨.clause [2, 1, 1, 12], "HatchStyle Enumeration"⟩,
  ⟨.clause [2, 1, 1, 13], "Layout Enumeration"⟩,
  ⟨.clause [2, 1, 1, 14], "LogicalColorSpace Enumeration"⟩,
  ⟨.clause [2, 1, 1, 15], "LogicalColorSpaceV5 Enumeration"⟩,
  ⟨.clause [2, 1, 1, 16], "MapMode Enumeration"⟩,
  ⟨.clause [2, 1, 1, 17], "MetafileEscapes Enumeration"⟩,
  ⟨.clause [2, 1, 1, 18], "MetafileType Enumeration"⟩,
  ⟨.clause [2, 1, 1, 19], "MetafileVersion Enumeration"⟩,
  ⟨.clause [2, 1, 1, 20], "MixMode Enumeration"⟩,
  ⟨.clause [2, 1, 1, 21], "OutPrecision Enumeration"⟩,
  ⟨.clause [2, 1, 1, 22], "PaletteEntryFlag Enumeration"⟩,
  ⟨.clause [2, 1, 1, 23], "PenStyle Enumeration"⟩,
  ⟨.clause [2, 1, 1, 24], "PitchFont Enumeration"⟩,
  ⟨.clause [2, 1, 1, 25], "PolyFillMode Enumeration"⟩,
  ⟨.clause [2, 1, 1, 26], "PostScriptCap Enumeration"⟩,
  ⟨.clause [2, 1, 1, 27], "PostScriptClipping Enumeration"⟩,
  ⟨.clause [2, 1, 1, 28], "PostScriptFeatureSetting Enumeration"⟩,
  ⟨.clause [2, 1, 1, 29], "PostScriptJoin Enumeration"⟩,
  ⟨.clause [2, 1, 1, 30], "StretchMode Enumeration"⟩,
  ⟨.clause [2, 1, 1, 31], "TernaryRasterOperation Enumeration"⟩,
  ⟨.clause [2, 1, 2], "WMF Flags"⟩,
  ⟨.clause [2, 1, 2, 1], "ClipPrecision Flags"⟩,
  ⟨.clause [2, 1, 2, 2], "ExtTextOutOptions Flags"⟩,
  ⟨.clause [2, 1, 2, 3], "TextAlignmentMode Flags"⟩,
  ⟨.clause [2, 1, 2, 4], "VerticalTextAlignmentMode Flags"⟩,
  ⟨.clause [2, 2], "WMF Objects"⟩,
  ⟨.clause [2, 2, 1], "Graphics Objects"⟩,
  ⟨.clause [2, 2, 1, 1], "Brush Object"⟩,
  ⟨.clause [2, 2, 1, 2], "Font Object"⟩,
  ⟨.clause [2, 2, 1, 3], "Palette Object"⟩,
  ⟨.clause [2, 2, 1, 4], "Pen Object"⟩,
  ⟨.clause [2, 2, 1, 5], "Region Object"⟩,
  ⟨.clause [2, 2, 2], "Structure Objects"⟩,
  ⟨.clause [2, 2, 2, 1], "Bitmap16 Object"⟩,
  ⟨.clause [2, 2, 2, 2], "BitmapCoreHeader Object"⟩,
  ⟨.clause [2, 2, 2, 3], "BitmapInfoHeader Object"⟩,
  ⟨.clause [2, 2, 2, 4], "BitmapV4Header Object"⟩,
  ⟨.clause [2, 2, 2, 5], "BitmapV5Header Object"⟩,
  ⟨.clause [2, 2, 2, 6], "CIEXYZ Object"⟩,
  ⟨.clause [2, 2, 2, 7], "CIEXYZTriple Object"⟩,
  ⟨.clause [2, 2, 2, 8], "ColorRef Object"⟩,
  ⟨.clause [2, 2, 2, 9], "DeviceIndependentBitmap Object"⟩,
  ⟨.clause [2, 2, 2, 10], "LogBrush Object"⟩,
  ⟨.clause [2, 2, 2, 11], "LogColorSpace Object"⟩,
  ⟨.clause [2, 2, 2, 12], "LogColorSpaceW Object"⟩,
  ⟨.clause [2, 2, 2, 13], "PaletteEntry Object"⟩,
  ⟨.clause [2, 2, 2, 14], "PitchAndFamily Object"⟩,
  ⟨.clause [2, 2, 2, 15], "PointL Object"⟩,
  ⟨.clause [2, 2, 2, 16], "PointS Object"⟩,
  ⟨.clause [2, 2, 2, 17], "PolyPolygon Object"⟩,
  ⟨.clause [2, 2, 2, 18], "Rect Object"⟩,
  ⟨.clause [2, 2, 2, 19], "RectL Object"⟩,
  ⟨.clause [2, 2, 2, 20], "RGBQuad Object"⟩,
  ⟨.clause [2, 2, 2, 21], "Scan Object"⟩,
  ⟨.clause [2, 2, 2, 22], "SizeL Object"⟩,
  ⟨.clause [2, 3], "WMF Records"⟩,
  ⟨.clause [2, 3, 1], "Bitmap Record Types"⟩,
  ⟨.clause [2, 3, 1, 1], "META_BITBLT Record"⟩,
  ⟨.clause [2, 3, 1, 1, 1], "With Bitmap"⟩,
  ⟨.clause [2, 3, 1, 1, 2], "Without Bitmap"⟩,
  ⟨.clause [2, 3, 1, 2], "META_DIBBITBLT Record"⟩,
  ⟨.clause [2, 3, 1, 2, 1], "With Bitmap"⟩,
  ⟨.clause [2, 3, 1, 2, 2], "Without Bitmap"⟩,
  ⟨.clause [2, 3, 1, 3], "META_DIBSTRETCHBLT Record"⟩,
  ⟨.clause [2, 3, 1, 3, 1], "With Bitmap"⟩,
  ⟨.clause [2, 3, 1, 3, 2], "Without Bitmap"⟩,
  ⟨.clause [2, 3, 1, 4], "META_SETDIBTODEV Record"⟩,
  ⟨.clause [2, 3, 1, 5], "META_STRETCHBLT Record"⟩,
  ⟨.clause [2, 3, 1, 5, 1], "With Bitmap"⟩,
  ⟨.clause [2, 3, 1, 5, 2], "Without Bitmap"⟩,
  ⟨.clause [2, 3, 1, 6], "META_STRETCHDIB Record"⟩,
  ⟨.clause [2, 3, 2], "Control Record Types"⟩,
  ⟨.clause [2, 3, 2, 1], "META_EOF Record"⟩,
  ⟨.clause [2, 3, 2, 2], "META_HEADER Record"⟩,
  ⟨.clause [2, 3, 2, 3], "META_PLACEABLE Record"⟩,
  ⟨.clause [2, 3, 3], "Drawing Record Types"⟩,
  ⟨.clause [2, 3, 3, 1], "META_ARC Record"⟩,
  ⟨.clause [2, 3, 3, 2], "META_CHORD Record"⟩,
  ⟨.clause [2, 3, 3, 3], "META_ELLIPSE Record"⟩,
  ⟨.clause [2, 3, 3, 4], "META_EXTFLOODFILL Record"⟩,
  ⟨.clause [2, 3, 3, 5], "META_EXTTEXTOUT Record"⟩,
  ⟨.clause [2, 3, 3, 6], "META_FILLREGION Record"⟩,
  ⟨.clause [2, 3, 3, 7], "META_FLOODFILL Record"⟩,
  ⟨.clause [2, 3, 3, 8], "META_FRAMEREGION Record"⟩,
  ⟨.clause [2, 3, 3, 9], "META_INVERTREGION Record"⟩,
  ⟨.clause [2, 3, 3, 10], "META_LINETO Record"⟩,
  ⟨.clause [2, 3, 3, 11], "META_PAINTREGION Record"⟩,
  ⟨.clause [2, 3, 3, 12], "META_PATBLT Record"⟩,
  ⟨.clause [2, 3, 3, 13], "META_PIE Record"⟩,
  ⟨.clause [2, 3, 3, 14], "META_POLYLINE Record"⟩,
  ⟨.clause [2, 3, 3, 15], "META_POLYGON Record"⟩,
  ⟨.clause [2, 3, 3, 16], "META_POLYPOLYGON Record"⟩,
  ⟨.clause [2, 3, 3, 17], "META_RECTANGLE Record"⟩,
  ⟨.clause [2, 3, 3, 18], "META_ROUNDRECT Record"⟩,
  ⟨.clause [2, 3, 3, 19], "META_SETPIXEL Record"⟩,
  ⟨.clause [2, 3, 3, 20], "META_TEXTOUT Record"⟩,
  ⟨.clause [2, 3, 4], "Object Record Types"⟩,
  ⟨.clause [2, 3, 4, 1], "META_CREATEBRUSHINDIRECT Record"⟩,
  ⟨.clause [2, 3, 4, 2], "META_CREATEFONTINDIRECT Record"⟩,
  ⟨.clause [2, 3, 4, 3], "META_CREATEPALETTE Record"⟩,
  ⟨.clause [2, 3, 4, 4], "META_CREATEPATTERNBRUSH Record"⟩,
  ⟨.clause [2, 3, 4, 5], "META_CREATEPENINDIRECT Record"⟩,
  ⟨.clause [2, 3, 4, 6], "META_CREATEREGION Record"⟩,
  ⟨.clause [2, 3, 4, 7], "META_DELETEOBJECT Record"⟩,
  ⟨.clause [2, 3, 4, 8], "META_DIBCREATEPATTERNBRUSH Record"⟩,
  ⟨.clause [2, 3, 4, 9], "META_SELECTCLIPREGION Record"⟩,
  ⟨.clause [2, 3, 4, 10], "META_SELECTOBJECT Record"⟩,
  ⟨.clause [2, 3, 4, 11], "META_SELECTPALETTE Record"⟩,
  ⟨.clause [2, 3, 5], "State Record Types"⟩,
  ⟨.clause [2, 3, 5, 1], "META_ANIMATEPALETTE Record"⟩,
  ⟨.clause [2, 3, 5, 2], "META_EXCLUDECLIPRECT Record"⟩,
  ⟨.clause [2, 3, 5, 3], "META_INTERSECTCLIPRECT Record"⟩,
  ⟨.clause [2, 3, 5, 4], "META_MOVETO Record"⟩,
  ⟨.clause [2, 3, 5, 5], "META_OFFSETCLIPRGN Record"⟩,
  ⟨.clause [2, 3, 5, 6], "META_OFFSETVIEWPORTORG Record"⟩,
  ⟨.clause [2, 3, 5, 7], "META_OFFSETWINDOWORG Record"⟩,
  ⟨.clause [2, 3, 5, 8], "META_REALIZEPALETTE Record"⟩,
  ⟨.clause [2, 3, 5, 9], "META_RESIZEPALETTE Record"⟩,
  ⟨.clause [2, 3, 5, 10], "META_RESTOREDC Record"⟩,
  ⟨.clause [2, 3, 5, 11], "META_SAVEDC Record"⟩,
  ⟨.clause [2, 3, 5, 12], "META_SCALEVIEWPORTEXT Record"⟩,
  ⟨.clause [2, 3, 5, 13], "META_SCALEWINDOWEXT Record"⟩,
  ⟨.clause [2, 3, 5, 14], "META_SETBKCOLOR Record"⟩,
  ⟨.clause [2, 3, 5, 15], "META_SETBKMODE Record"⟩,
  ⟨.clause [2, 3, 5, 16], "META_SETLAYOUT Record"⟩,
  ⟨.clause [2, 3, 5, 17], "META_SETMAPMODE Record"⟩,
  ⟨.clause [2, 3, 5, 18], "META_SETMAPPERFLAGS Record"⟩,
  ⟨.clause [2, 3, 5, 19], "META_SETPALENTRIES Record"⟩,
  ⟨.clause [2, 3, 5, 20], "META_SETPOLYFILLMODE Record"⟩,
  ⟨.clause [2, 3, 5, 21], "META_SETRELABS Record"⟩,
  ⟨.clause [2, 3, 5, 22], "META_SETROP2 Record"⟩,
  ⟨.clause [2, 3, 5, 23], "META_SETSTRETCHBLTMODE Record"⟩,
  ⟨.clause [2, 3, 5, 24], "META_SETTEXTALIGN Record"⟩,
  ⟨.clause [2, 3, 5, 25], "META_SETTEXTCHAREXTRA Record"⟩,
  ⟨.clause [2, 3, 5, 26], "META_SETTEXTCOLOR Record"⟩,
  ⟨.clause [2, 3, 5, 27], "META_SETTEXTJUSTIFICATION Record"⟩,
  ⟨.clause [2, 3, 5, 28], "META_SETVIEWPORTEXT Record"⟩,
  ⟨.clause [2, 3, 5, 29], "META_SETVIEWPORTORG Record"⟩,
  ⟨.clause [2, 3, 5, 30], "META_SETWINDOWEXT Record"⟩,
  ⟨.clause [2, 3, 5, 31], "META_SETWINDOWORG Record"⟩,
  ⟨.clause [2, 3, 6], "Escape Record Types"⟩,
  ⟨.clause [2, 3, 6, 1], "META_ESCAPE Record"⟩,
  ⟨.clause [2, 3, 6, 2], "ABORTDOC Record"⟩,
  ⟨.clause [2, 3, 6, 3], "BEGIN_PATH Record"⟩,
  ⟨.clause [2, 3, 6, 4], "CHECKJPEGFORMAT Record"⟩,
  ⟨.clause [2, 3, 6, 5], "CHECKPNGFORMAT Record"⟩,
  ⟨.clause [2, 3, 6, 6], "CLIP_TO_PATH Record"⟩,
  ⟨.clause [2, 3, 6, 7], "CLOSECHANNEL Record"⟩,
  ⟨.clause [2, 3, 6, 8], "DOWNLOADFACE Record"⟩,
  ⟨.clause [2, 3, 6, 9], "DOWNLOADHEADER Record"⟩,
  ⟨.clause [2, 3, 6, 10], "DRAWPATTERNRECT Record"⟩,
  ⟨.clause [2, 3, 6, 11], "ENCAPSULATED_POSTSCRIPT Record"⟩,
  ⟨.clause [2, 3, 6, 12], "END_PATH Record"⟩,
  ⟨.clause [2, 3, 6, 13], "ENDDOC Record"⟩,
  ⟨.clause [2, 3, 6, 14], "EPSPRINTING Record"⟩,
  ⟨.clause [2, 3, 6, 15], "EXTTEXTOUT Record"⟩,
  ⟨.clause [2, 3, 6, 16], "GETCOLORTABLE Record"⟩,
  ⟨.clause [2, 3, 6, 17], "GETDEVICEUNITS Record"⟩,
  ⟨.clause [2, 3, 6, 18], "GETEXTENDEDTEXTMETRICS Record"⟩,
  ⟨.clause [2, 3, 6, 19], "GETFACENAME Record"⟩,
  ⟨.clause [2, 3, 6, 20], "GETPAIRKERNTABLE Record"⟩,
  ⟨.clause [2, 3, 6, 21], "GETPHYSPAGESIZE Record"⟩,
  ⟨.clause [2, 3, 6, 22], "GETPRINTINGOFFSET Record"⟩,
  ⟨.clause [2, 3, 6, 23], "GET_PS_FEATURESETTING Record"⟩,
  ⟨.clause [2, 3, 6, 24], "GETSCALINGFACTOR Record"⟩,
  ⟨.clause [2, 3, 6, 25], "META_ESCAPE_ENHANCED_METAFILE Record"⟩,
  ⟨.clause [2, 3, 6, 26], "METAFILE_DRIVER Record"⟩,
  ⟨.clause [2, 3, 6, 27], "NEWFRAME Record"⟩,
  ⟨.clause [2, 3, 6, 28], "NEXTBAND Record"⟩,
  ⟨.clause [2, 3, 6, 29], "PASSTHROUGH Record"⟩,
  ⟨.clause [2, 3, 6, 30], "POSTSCRIPT_DATA Record"⟩,
  ⟨.clause [2, 3, 6, 31], "POSTSCRIPT_IDENTIFY Record"⟩,
  ⟨.clause [2, 3, 6, 32], "POSTSCRIPT_IGNORE Record"⟩,
  ⟨.clause [2, 3, 6, 33], "POSTSCRIPT_INJECTION Record"⟩,
  ⟨.clause [2, 3, 6, 34], "POSTSCRIPT_PASSTHROUGH Record"⟩,
  ⟨.clause [2, 3, 6, 35], "OPENCHANNEL Record"⟩,
  ⟨.clause [2, 3, 6, 36], "QUERYDIBSUPPORT Record"⟩,
  ⟨.clause [2, 3, 6, 37], "QUERYESCSUPPORT Record"⟩,
  ⟨.clause [2, 3, 6, 38], "SETCOLORTABLE Record"⟩,
  ⟨.clause [2, 3, 6, 39], "SETCOPYCOUNT Record"⟩,
  ⟨.clause [2, 3, 6, 40], "SETLINECAP Record"⟩,
  ⟨.clause [2, 3, 6, 41], "SETLINEJOIN Record"⟩,
  ⟨.clause [2, 3, 6, 42], "SETMITERLIMIT Record"⟩,
  ⟨.clause [2, 3, 6, 43], "SPCLPASSTHROUGH2 Record"⟩,
  ⟨.clause [2, 3, 6, 44], "STARTDOC Record"⟩,
  ⟨.clause [3, 1], "Metafile Design"⟩,
  ⟨.clause [3, 1, 1], "Device Independence"⟩,
  ⟨.clause [3, 1, 2], "Byte Ordering Example"⟩,
  ⟨.clause [3, 1, 3], "Mapping Modes"⟩,
  ⟨.clause [3, 1, 4], "Managing Objects"⟩,
  ⟨.clause [3, 1, 4, 1], "WMF Object Table"⟩,
  ⟨.clause [3, 1, 4, 2], "Object Scaling"⟩,
  ⟨.clause [3, 1, 5], "Playback Device Context"⟩,
  ⟨.clause [3, 1, 6], "Run-Length Encoding (RLE) Compression"⟩,
  ⟨.clause [3, 1, 6, 1], "Bitmaps with 4 Bits per Pixel"⟩,
  ⟨.clause [3, 1, 6, 2], "Bitmaps with 8 Bits per Pixel"⟩,
  ⟨.clause [3, 2], "WMF Metafile Example"⟩,
  ⟨.clause [3, 2, 1], "META_HEADER Example"⟩,
  ⟨.clause [3, 2, 2], "META_CREATEPENINDIRECT Example"⟩,
  ⟨.clause [3, 2, 3], "META_SELECTOBJECT Example 1"⟩,
  ⟨.clause [3, 2, 4], "META_CREATEBRUSHINDIRECT Example"⟩,
  ⟨.clause [3, 2, 5], "META_SELECTOBJECT Example 2"⟩,
  ⟨.clause [3, 2, 6], "META_RECTANGLE Example"⟩,
  ⟨.clause [3, 2, 7], "META_TEXTOUT Example"⟩,
  ⟨.clause [3, 2, 8], "META_EOF Example"⟩
]

/-- Every numbered heading of the specification, in document order. -/
def headings : List Heading := headings0

end Ledger.Outline.MsWmf
