import Ledger.Checks

/-!
`lake exe ledger-report` prints the conformance chapter of the book from the
ledger, as Markdown, to stdout. `lake exe ledger-report --check` prints the
rows, clauses and citations that would fail the gate to stderr and exits
with 1 when there are any, so a failing `lake build` has a readable cause.
-/

open Ledger

namespace Report

def statusLabel : Status → String
  | .implemented => "implemented"
  | .incomplete => "incomplete"
  | .notImplemented => "not implemented"
  | .outOfScope => "out of scope"

def codeCitations (f : Feature) : List Citation :=
  Generated.citations.filter fun c => !c.inTest && f.citedBy c

def testCitations (f : Feature) : List Citation :=
  Generated.citations.filter fun c => c.inTest && f.citedBy c

def cell (s : String) : String := s.replace "|" "\\|"

def rowFor (f : Feature) : String :=
  s!"| {f.ref.render} | {cell f.title} | {statusLabel f.status} | " ++
  s!"{(codeCitations f).length} | {(testCitations f).length} | {cell f.note} |"

def inOrder (features : List Feature) : List Feature :=
  (features.toArray.qsort fun a b => decide (a.ref.key < b.ref.key)).toList

def countWith (features : List Feature) (status : Status) : Nat :=
  (features.filter (·.status == status)).length

def statuses : List Status := [.implemented, .incomplete, .notImplemented, .outOfScope]

def summary : List String :=
  [ "| Specification | Implemented | Incomplete | Not implemented | Out of scope |",
    "|---|---|---|---|---|" ] ++
  Standard.all.map (fun s =>
    let rows := Catalogue.rows s
    s!"| {cell s.label} | " ++ " | ".intercalate (statuses.map fun st => toString (countWith rows st)) ++
      " |") ++ [""]

def tableHeader : List String :=
  [ "| Clause | Feature | Status | Code citations | Test citations | Note |",
    "|---|---|---|---|---|---|" ]

def chapterTitle (s : Standard) (key : Nat) : String :=
  if key == 100 then "Annexes" else
    match (Outline.chapters s).find? (·.1 == key) with
    | some (_, title) => s!"{key} {title}"
    | none => toString key

def standardSection (s : Standard) : List String :=
  let rows := Catalogue.rows s
  let chapters := (Outline.chapterKeys s).filter fun k => rows.any (·.ref.chapterKey == k)
  [s!"## {s.title}", ""] ++ chapters.flatMap fun k =>
    [s!"### {chapterTitle s k}", ""] ++ tableHeader ++
      (inOrder (rows.filter (·.ref.chapterKey == k))).map rowFor ++ [""]

def intro : List String := [
  "# Conformance",
  "",
  "docboss keeps a ledger of the specifications it implements in `ledger/Ledger/Catalogue/`, one",
  "row per clause with the status docboss claims: implemented, incomplete, not implemented or out",
  "of scope. The specifications are ECMA-376 Parts 1 to 3 (5th edition), [MS-DOC], [MS-CFB],",
  "[MS-OLEPS], [MS-OSHARED], [MS-ODRAW] and PKWARE's APPNOTE.TXT; `ledger/Ledger/Scope.lean`",
  "names the clauses of each that must have a row.",
  "",
  "The ledger is checked by Lean 4 on every push (`make ledger-gate`). Six theorems in",
  "`ledger/Ledger/Gate.lean` establish that every row sits in its own specification's file and",
  "names one of its chapters, that rows are unique, that every required clause has a row speaking",
  "to it, that every implemented row is cited by both implementation code and a test in the source",
  "tree, that every incomplete row is cited by implementation code and explains what is missing,",
  "that every other row explains itself, and that no citation names a clause its specification does",
  "not have. They are decided by Lean's compiled evaluator (`native_decide`), so they trust the Lean",
  "compiler as well as its kernel; the theorems of the reference implementations in",
  "`ledger/Ledger/Reference/`, whose vectors the Rust tests replay, are checked by the kernel alone.",
  "Citation counts below are the number of source comments naming the clause or a sub-clause of it,",
  "in implementation code and in tests.",
  "",
  "This page is generated by `make ledger-report`. Edit the ledger, not the page.",
  ""
]

def document : String :=
  "\n".intercalate (intro ++ summary ++ Standard.all.flatMap standardSection)

def missingFor (f : Feature) : List String :=
  let needsCode := f.status == .implemented || f.status == .incomplete
  let needsTests := f.status == .implemented
  let needsNote := f.status != .implemented
  (if needsCode && (codeCitations f).isEmpty then ["no implementation comment cites it"] else []) ++
  (if needsTests && (testCitations f).isEmpty then ["no test cites it"] else []) ++
  (if needsNote && f.note.isEmpty then ["no note explains it"] else [])

def checkReport : List String :=
  let offenders := Gate.offenders.map fun f =>
    s!"row {f.standard.label} {f.ref.render} ({statusLabel f.status}) {f.title}: " ++
      ", ".intercalate (missingFor f)
  let unaddressed := Gate.unaddressed.map fun (s, h) =>
    s!"clause {s.label} {h.ref.render} {h.title}: no ledger row speaks to it"
  let dangling := Gate.danglingCitations.map fun c =>
    s!"{c.file}:{c.line}: cites {c.standard.label} {(c.ref.map Ref.render).getD "?"}, " ++
      "which the specification does not have"
  let duplicates := Gate.duplicateRefs.map fun (s, r) =>
    s!"row {s.label} {r.render} appears more than once"
  let misfiled := Gate.misfiledRows.map fun f =>
    s!"row {f.standard.label} {f.ref.render} sits in another specification's file"
  let unsliced := Gate.unslicedRows.map fun f =>
    s!"row {f.standard.label} {f.ref.render} names a chapter its specification does not have"
  let unknown := Gate.unknownRows.map fun f =>
    let expected := (Outline.titleOf f.standard f.ref).map (s!"; the outline calls it {·}") |>.getD
      "; the outline has no such clause"
    s!"row {f.standard.label} {f.ref.render} {f.title}: not a clause of the outline by that title{expected}"
  offenders ++ unaddressed ++ dangling ++ duplicates ++ misfiled ++ unsliced ++ unknown

/-- Mentions of a specification that name no clause, listed so a typo in a
citation does not pass unnoticed. -/
def unresolved : List String :=
  (Generated.citations.filter (·.ref.isNone)).map fun c =>
    s!"{c.file}:{c.line}: mentions {c.standard.label} without a clause"

end Report

def main (args : List String) : IO UInt32 := do
  if args.contains "--check" then
    let problems := Report.checkReport
    for line in problems do
      IO.eprintln line
    for line in Report.unresolved do
      IO.eprintln s!"note: {line}"
    IO.eprintln s!"{problems.length} problem(s); {Catalogue.features.length} ledger rows, \
      {Generated.citations.length} citations"
    return if problems.isEmpty then 0 else 1
  IO.println Report.document
  return 0
